### ISSUE TITLE
Keyboard tree navigation

### ISSUE THREAD

**Issue by Seth-Rothschild** [SabakiHQ/Sabaki#227]
Summary: Keyboard navigation is a complicated issue and each client has different behavior. What should the expected behavior of Sabaki be?

This was going to be a feature request until I did some research.  It is related to #174.

Consider the sgf and game tree below. I checked keyboard navigation on Sabaki, cgoban3, OGS, eidogo and gopanda2. Pretend all trees are oriented the same way. For eidogo and gopanda all keyboard navigation can only move on one branch. We'll label the four columns 1, 2, 3, and 4 and then give an *absolute* position for rows 1, 2, 3, 4, 5 and 6 (i.e. the root of the tree is at col:1 row:1, the bottom right corner is col:4 row:6).

Results:
A: At col: 2 row: 6 -> press left
sabaki - col: 3 row: 4
cgoban - nothing
ogs - col: 1 row: 6

B: At col: 1 row: 6 -> press right
sabaki - col: 2 row: 3
cgoban - nothing
ogs - col: 2 row: 6

C: At col: 2 row: 3 -> press left
sabaki - col: 1 row: 3
cgoban - highlight other branch starting at col: 2 row: 3
ogs - col: 1 row: 3

D: at col: 1 row: 2 -press right
sabaki - nothing
cgoban - highlight other branch starting at col: 1 row: 2
ogs - nothing

I think Sabaki shines here with B (go to the root of the next branch over) but that same behavior is pretty problematic visually in A. I really like the cgoban behavior in D but overall the only way to get from one place to another is to navigate through the root. The OGS behavior is the most similar to Sabaki and it always allows for moving left or right to any point that is on that level. How *should* keyboard navigation work in Sabaki?

![image](https://cloud.githubusercontent.com/assets/27442755/26134870/af940794-3a7f-11e7-9d4b-62bff397cf7e.png)

`(;GM[1]FF[4]CA[UTF-8]AP[Sabaki:0.30.3]KM[6.5]SZ[19]
;B[dd]
(;W[de]
;B[df]
;W[dg]
;B[dh]
)(;W[ee]
(;B[ef]
;W[eg]
;B[eh]
)(;B[ff]
(;W[fg]
;B[fh]
)(;W[gg]
;B[gh]
))))`

**Comment by Seth-Rothschild** [comment]
Here is an associated problem. Suppose you're in col: 1 row: 2 and want to view col: 2 in Sabaki. If you have recently been to the far right branch, the fastest path to col: 2 is
`down -> right -> down -> left`
In ogs it is `down -> right` and in cgoban it is `right ->down`. 

This actually isn't all that problematic in terms of keystrokes, but it does make it hard for the user to predict what the path to a given branch is.

**Comment by Seth-Rothschild** [comment]
So after some thought, here are what I see as the options:

1. Do nothing
2. Implement OGS style movement (i.e. remap left and right to go to the corresponding node on whatever branch is visually there)
3. Implement KGS style movement (i.e. remap left and right to do nothing unless at a branch point)
4. Find a hybrid solution

I'd be happy to work on any of these but I'm not sure what would be best. I think 2 and 3 should actually be fairly straightforward. I'm intellectually curious about 4 but I'm doubtful that there exists a sufficiently simple solution. It might be worth demoing 2 and 3 in branches and continuing to brainstorm 4?

**Comment by yishn** [comment]
Here are my thoughts: The main disadvantage of the current implementation is that it's not possible to invert a variation navigation, i.e. pressing left and then right doesn't get you back where you started and vice versa. This can be frustrating if you press left or right accidentally.

The OGS implementation may be the most intuitive, but it lacks semantic meaning. If you don't have the game tree open, you can't predict where you will end up.

The CGoban implementation only works if you have the game tree open as well, as pressing left or right doesn't have an immediate noticeable effect.

**Comment by Walther** [comment]
I would personally think about this from the average end-user usefulness perspective:

> 2. Implement OGS style movement (i.e. remap left and right to go to the corresponding node on whatever branch is visually there)

"What you see is what you get" -> potentially highest usefulness for most casual users

> 3. Implement KGS style movement (i.e. remap left and right to do nothing unless at a branch point)

Logical, but allows less movement -> potentially slightly less useful

> If you don't have the game tree open, you can't predict where you will end up.

If you don't have a game tree open and you press a key shortcut intended semantically for "switch branch" command (or similar), one would have to have the game tree memorized for this to be useful - certainly possible, but probably not the average use case. And on the other hand, if your use case is "I wonder if there are variations available here", the more useful option than to try clicking switch-branch key from each node, is to simply open the game tree visually and immediately see where the possible variations are located.

**Comment by yishn** [comment]
WYSIWYG and invertible left/right keys coming in v0.43.0.
