### ISSUE TITLE
Repeating up/down arrows on OS X isn't smooth

### ISSUE THREAD

**Issue by dfannius** [SabakiHQ/Sabaki#277]
I'm using Sabaki 0.31.1; I assume nothing important has changed lately, but I can always confirm with the latest version if desired.

When I hold down the up or down arrow to navigate the game tree, the response is clunky. There is noticeable time spent between rendering updates, and those updates sometimes skip moves, I assume because it is trying to keep up with the current position. On the other hand, when I use the mouse wheel to perform the same function, everything is very smooth and pleasant, with no noticeable lag or skipping.

When I hold down an arrow key, the Navigation menubar choice keeps flashing to indicate that I have pressed a hotkey, and I assume that this is related to the performance difference, if not necessarily the actual cause. I don't know if there's a way to tell the Mac not to flash the menubar heading for particular hotkeys (I spent 5 minutes browsing Electron docs and didn't find anything), or whether that would be sufficient to address the problem.

**Comment by aldanor** [comment]
Noticed the same thing, holding down the up/down arrow key just doesn't work, it lags and stutters.
