### ISSUE TITLE
[Feature request] Add option to log GTP console output into file

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [SabakiHQ/Sabaki#297]
Would be nice to have possibility to log GTP console output into file. 
Especially actual with bots like Ray - which generate a lot of output, especially with long time settings.

**Comment by papanera** [comment]
Why can't I see the File Play Edit Bar?

**Comment by xiarx2016** [comment]
Dear yishn , when AI run a "genmove" command , how can I get all the GTP console information ?
 I try to  use the response after the code ： " let response = await getResponse() ” in handleCommandSent function, but  I only get  a vertex . 
I want to get the other information that show in the GTP console drawer .
