### ISSUE TITLE
Add the auto-updater

### ISSUE THREAD

**Issue by ohyou** [SabakiHQ/Sabaki#323]
I see you're using electron, so it should be quite trivial with your technology stack.
We use this at work, took us about an hour to fully implement it: https://github.com/electron-userland/electron-builder
It really is quite annoying having to "install" the app every time there's an update. Especially in the year of two thousand eighteen.

**Comment by FFLaguna** [comment]
Agreed, and I also get Windows/virus scanner alerts each time I have to install the new Sabaki.

Windows hides the application behind "SmartScreen" prompt that requires a semi-hidden click-thru to run.

Separately, my virus scanner Avast! force-closes and restarts the installer after doing a "CyberCapture" scan. Then _during_ installation, Avast! does another CyberCapture scan. And when you go to run your new Sabaki for the first time, Avast! does yet another CyberCapture scan on that executable.

**Comment by yishn** [comment]
Sounds to me that you have a configuration problem in Avast. It doesn't happen with 99% of the anti-virus software I install.

Joking aside, this is an open source project and I'm encouraging everyone to contribute to it. @ohyou If you have experience with the auto-updater of electron-builder, I would appreciate if you can lend us a hand here.

**Comment by FFLaguna** [comment]
Perhaps there is some sort of signing issue with Sabaki releases that causes SmartScreen and antivirus flags to be raised. I'm not knowledgeable enough about this, unfortunately.

**Comment by yishn** [comment]
Subscribe to #364 for updates

**Comment by Ishinoshita** [comment]
Hi @yishn. FYI: Just got an Avast alert today, for the first time, whereas I use Sabaki with Avast backgroud since months, without any issue... Avast classifies the threat as "Win64:MdeClass".

Win7 64bits. Did install Sabaki from Windows binaries release, then accepeted the update as they came.
Regards.

**Comment by yishn** [comment]
I don‘t know where this may come from. [As you can see](https://www.virustotal.com/de/url/1df1879f6a775b266044f20df178c2565c7c96a752f49b82500c4326a3520a39/analysis/), lots of other anti-viruses don’t detect anything. Please submit a false positive claim to Avast.

**Comment by Ishinoshita** [comment]
Thank you. I have submigtted a flase positive request to Avast.
