### ISSUE TITLE
Sometimes AI will suddenly pass If I go to another branch

### ISSUE THREAD

**Issue by OneMoreSecond** [SabakiHQ/Sabaki#331]
This occurs with both AQ and LeelaZero frequently.

I like watching AI playing with themselves.
Sometimes I will try to modify a step, but AI will suddenly pass in the new branch or the old branch.
Going back and regenerating the step can help, but it is possible that the problem occurs in the next step.

A simple example is attached. AQ was used in it.
[bug.zip](https://github.com/yishn/Sabaki/files/1693975/bug.zip)

**Comment by yishn** [comment]
What does the GTP console say? Is the engine actually passing?

**Comment by OneMoreSecond** [comment]
> What does the GTP console say? Is the engine actually passing?

It seems that Sabaki gives the new board sequence to the engine, and then the engine passes.

It's not hard to reproduce the problem in my experience.
Just try to manually branch several times on a board with over 100 moves.

**Comment by yishn** [comment]
If the engine is passing of its own accord, there's nothing Sabaki can do... BTW which Sabaki version are you using? Before v0.32.2, Sabaki wasn't sending moves in order to the engine which might have caused some problems.

**Comment by yishn** [comment]
I'm closing this as no more information has been provided.
