### ISSUE TITLE
npm run build fails when trying to import zerorpc

### ISSUE THREAD

**Issue by cboittin** [SabakiHQ/Sabaki#332]
I'm trying to integrate zerorpc to sabaki so that i can communicate with a python script. I don't know much about JS in general, but it seems like what i'm trying to do should work.

I can `npm install zerorpc` just fine, then from node_modules/zerorpc, i can run `node index.js` and it doesn't give any error.

However, when i require zerorpc from sabaki and i run `npm run build`, i get an error in msgpack, a dependency for zerorpc.
```
ERROR in ./node_modules/zerorpc/node_modules/msgpack/lib/msgpack.js
Module not found: Error: Can't resolve 'C:\Users\Moi\Desktop\Go\review_stuff\Sabaki-master\
node_modules\msgpack\lib/../build/Release/msgpackBinding' in 'C:\Users\Moi\Desktop\Go\
review_stuff\Sabaki-master\node_modules\zerorpc\node_modules\msgpack\lib'
 @ ./node_modules/zerorpc/node_modules/msgpack/lib/msgpack.js 6:13-68
 @ ./node_modules/zerorpc/lib/events.js
 @ ./node_modules/zerorpc/lib/socket.js
 @ ./node_modules/zerorpc/lib/server.js
 @ ./node_modules/zerorpc/index.js
 @ ./src/components/App.js
```

msgpackBinding isn't a js file, it's packed as a .node file.

Any idea why this doesn't work ?

**Comment by yishn** [comment]
It seems like zerorpc depends on the module msgpack which is a native addon to node.js. Native addons work out of the box in a pure node.js setting, however using them in Electron requires [some extra steps](https://electronjs.org/docs/tutorial/using-native-node-modules). Unfortunately, I haven't tried doing that myself yet, so I can't help you.

**Comment by cboittin** [comment]
I ended up using websockets, zerorpc really didn't want to work. Thanks for your help !

I also forked sabaki into my own project, if you're interested : https://github.com/cboittin/twitch-sabaki-bot .
