### ISSUE TITLE
The game tree window sometimes becomes unclickable

### ISSUE THREAD

**Issue by ikirill** [SabakiHQ/Sabaki#333]
I couldn't find a good way to reproduce this reliably, so apologies for that, but it keeps occasionally happening (this is 0.33.2 on macOS 10.12.6).

- start a game with LeelaSabaki (thank you for writing it, btw!)
- play a move
- press Command-T, it brings up the game tree window, press Command-T to remove it
- play a move
- press Command-T, it doesn't bring the game tree window up, the bottom looks a tiny bit messed up (see bottom here: https://i.imgur.com/RQcVfE2.png, the edit button is in the wrong place), press Command-T to undo whatever this effect is.
- press Command-T, it brings the game tree window up, but none of the nodes within the game tree are clickable, and don't highlight when you hover over them. It stays unclickable even if I toggle it again and again, and I haven't found a way to interact with it without restarting Sabaki.

It's happened to me before also when creating sgf files with many variations and toggling the game tree window, but only every now and then, it's not common.

**Comment by yishn** [comment]
Wow, thank you for the report, I can reproduce this on my Windows 10 machine. This is definitely not what is supposed to happen; it seems there's an internal error happening and crashing the game tree.
