### ISSUE TITLE
Allow sorting games by number of moves in the game (and/or by file size)

### ISSUE THREAD

**Issue by wctgit** [SabakiHQ/Sabaki#336]
This may be a little specific, but I happened to be looking for a way to find LeelaZero self-play games which ended with a ladder early in the game. I thought by using Sabaki's 'Manage Games' feature, I might be able to find some games like that by looking at the board previews. Unfortunately, that doesn't show the end position as I thought it did.

So, the next idea I had was to sort the games by number of moves, since early ladders lead to short games. I got all excited when I saw that Sabaki does indeed include a Sort feature. But it doesn't include number of moves... ah, so close! Anyway, I thought I'd submit an issue for this since it was a real-world use case.

As a kind of cheap work-around, even sorting by the size of the file would probably help. I'm going to try that on my file system to see if anything turns up, in the meantime.

**Comment by gcentauri** [comment]
Hi there!  I'm a fan of Sabaki as well, and thought I'd try my hand at contributing to the project.  I have submitted PR #391 to sort games by number of moves.
