### ISSUE TITLE
Mac OS couldn't load leela GTP.

### ISSUE THREAD

**Issue by ellioootd** [SabakiHQ/Sabaki#338]
<img width="1668" alt="1" src="https://user-images.githubusercontent.com/32831922/36276781-eb63adec-12c9-11e8-8561-95f9139ff165.png">
<img width="1672" alt="2" src="https://user-images.githubusercontent.com/32831922/36276782-eb93cafe-12c9-11e8-95b4-70fdf3f96e30.png">
for the setting as seen above, My imac still couldn't load Leela GTP( including opencl version). I wondered if the graphics card (AMD R9 M390) do not support or any the other setting problems? Thanks.

**Comment by yishn** [comment]
If you specify `--help`, LeelaSabaki will only display a help message; it won't start Leela or enter GTP mode.
