### ISSUE TITLE
Autolink variations

### ISSUE THREAD

**Issue by aixpen** [SabakiHQ/Sabaki#340]
Auto linking board coordinates is great 😄
Maybe it would be possible to autolink variations like gokibitz?
https://github.com/neagle/gokibitz/blob/master/server/utils/parseLabels.js#L6

**Comment by yishn** [comment]
While I like GoKibitz's variation animation feature, it's only a workaround for its lack of real variation support. I want to encourage people to use real variations instead of spewing some coordinates into the comment section.

**Comment by yishn** [comment]
Will be in the next release.
