### ISSUE TITLE
Separate button and score display in score/estimate bar

### ISSUE THREAD

**Issue by wctgit** [SabakiHQ/Sabaki#341]
Is it just me, or does Sabaki not allow making games with different rule sets, e.g. Chinese, Japanese, Tromp Taylor, etc.?

It even doesn't show which rule set is being used in a loaded SGF file (under Game Info). 

I think the scoring is restricted to Japanese only.

If I'm correct, then please consider this an enhancement request to allow for at least Chinese and Japanese rules, and perhaps even Tromp Taylor rules, as this would be very useful for looking at games created by Leela Zero.

Even if you don't fully implement different rule sets in game play, at least please display the rule set defined in the game's SGF file under Game Info.

**Comment by yishn** [comment]
There's no concept of a ruleset in SGF, because the user can do anything they want. Sabaki only show warnings for simple Ko and suicide which can be disabled in Preferences. As for scoring, there is an option to toggle between area and territory scoring.

**Comment by wctgit** [comment]
There is a tag, RU (see https://www.red-bean.com/sgf/properties.html#RU for specification. NZ rules would be roughly equivalent to Tromp-Taylor, as far as I know, just FYI), which defines the assumed overall rule set for the SGF. Any moves in the SGF which violate the specified rules could be considered illegal moves, perhaps making the SGF invalid. However, to say there's 'no concept' of ruleset in SGF is simply incorrect.

As for the option to toggle scoring, it is definitely not obvious in the UI. I looked for it before posting this, although I was looking for changing the rule set, not for 'area vs. territory'. I'll look again.... Okay, that is **definitely** not obvious. Instead of being under Preferences or Game Info, you have to click on the score display within Score or Estimate, and the score certainly does not appear to be a button of any kind at first glance.

Personally, I would try to follow the principles laid out in [The Design of Everyday Things](https://www.amazon.com/Design-Everyday-Things-Donald-Norman/dp/1452654123), by [Don Norman](https://en.wikipedia.org/wiki/Don_Norman), a very well-known design and usability researcher. For example, one of his principles is that a single control on an interface should ideally have a single function: the score display violates this principle by acting as both a simple display and as a button, with no additional visual [affordance](https://en.wikipedia.org/wiki/Affordance#As_perceived_action_possibilities) to indicate that it might be a button (although mouse hovering does indicate this, but who would think to hover over the score display? I didn't, until prompted by your comment). Compare this with a hyperlink, which is also a clickable display object, but which provides the visual affordances of being a different colour to the surrounding text and is also usually with an adornment such as being underlined. Just my opinion.

**Comment by yishn** [comment]
@wctgit Perhaps you have a suggestion instead of criticizing with a quote from a 16 year old book? (Actually, the book is 30 years old. I wouldn't be surprised if things have changed since then. But then again, I haven't read that book, so I can't say for sure.) Previously, the button would only display 'Done', but I changed it so it would display useful information instead of just being a waste of space.

Also, the data for both area and territory are visible, just the end result changes when you toggle between them.

I agree there is a property for specifying the ruleset, but it shouldn't have an effect on someone who edits the game. That's what I meant by 'no concept'. It's only there for reference purposes, like game name/date, handicap stones, and copyright. That said, we could display the value of the property somewhere in game info.

**Comment by wctgit** [comment]
> Perhaps you have a more concrete suggestion instead of criticizing with a quote from a 16 year old book?

It is meant as constructive criticism. It's a very good book, which is why it's still in print, and the principles are time-tested. Also, I didn't quote the book, but referenced it from my memory of it. My Computer Science degree was specialized in Human-Computer Interaction, and Don Norman is well-known in that field. That's how I know about the book, and why I read it.

Also, I did give a concrete suggestion, but since I added it later as an edit, perhaps you missed it: 
>[ETA: Perhaps making the score estimator have two lines, one for area, one for territory, would be reasonable, and reduce the need to switch 'modes'. ... ]

...
>Previously, the button would only display 'Done', but I changed it so it would display useful information instead of just being a waste of space.

Which button are you referring to? I'm referring to the score display control that shows up when you do Estimate, and it shows, for example, something like "W+50.5", and when you hover over it, it says "Details". Clicking on that control/button brings you to the Score calculation dialog where you can finally select Area or Territory. It's this dual-purpose control that both displays the score and is also a Details button that I'm referring to. It doesn't sound the same as the Done button you're referring to.

> The reason why there is a mode switcher is, that I don't think people would want to see both of them at the same time, or even switch between them very often.

Just for reference, other Go UIs such as the WGo UI display both territory and area scoring when you select Count Score from its hamburger menu.

The real issue here is that I was opening SGF files which had their RU tag set to 'Chinese', but Sabaki was showing scoring based on territory/Japanese, rather than area/Chinese. If the scoring defaulted to area for 'Chinese', and territory for 'Japanese', that would be better, IMO.

> I think it's more often the case that they stick to one or the other.

Unless they are opening multiple SGF files, in which case, the users would expect that the 'score' should be based on the ruleset specified by the existing SGF. Games from different sources, or even the same source (such as OGS), can use different rulesets from one game to the next. If the user has to open up the SGF file in a text editor to discover what the ruleset is, and then locate the difficult-to-find Details/Score calculation dialog just to toggle to the right scoring method, that's a pretty big pain in the UI. Sabaki can easily figure out which scoring should be default and toggle to that. Or, alternatively, just show both scoring methods, each on its own line, when the user clicks Estimate.

> It's only there for reference purposes, like game name/date, handicap stones, and copyright.

Presumably, it also specifies how the score in the game result property was calculated.

**Comment by yishn** [comment]
> It is meant as constructive criticism. It's a very good book, which is why it's still in print, and the principles are time-tested. 

It's hardly constructive criticism, since you didn't say what exactly can be changed. Also I don't know the book and am hardly willing to read it just for you. Furthermore, I didn't study Human-Computer Interaction.

> Also, I didn't quote the book, but referenced it from my memory of it.

Let's not argue about formal definitions. My argument still stands if you change one wording for another.

> Also, I did give a concrete suggestion, but since I added it later as an edit, perhaps you missed it: 
> >[ETA: Perhaps making the score estimator have two lines, one for area, one for territory, would be reasonable, and reduce the need to switch 'modes'. ... ]

I did indeed miss this, but please do explain yourself further.

>>Previously, the button would only display 'Done', but I changed it so it would display useful information instead of just being a waste of space.
>
> Which button are you referring to? I'm referring to the score display control that shows up when you do Estimate, and it shows, for example, something like "W+50.5", and when you hover over it, it says "Details".

That's exactly the button I'm referring to.

>> The reason why there is a mode switcher is, that I don't think people would want to see both of them at the same time, or even switch between them very often.
>
>Just for reference, other Go UIs such as the WGo UI display both territory and area scoring when you select Count Score from its hamburger menu.

No contradictions here. And I think WGo can be customized either way.

> The real issue here is that I was opening SGF files which had their RU tag set to 'Chinese', but Sabaki was showing scoring based on territory/Japanese, rather than area/Chinese. If the scoring defaulted to area for 'Chinese', and territory for 'Japanese', that would be better, IMO.

I'm not a fan of how opening an SGF file can change a user's setting. Also, if the score has already been calculated, there is no need to calculate it again with the scoring tool.

> [ETA: Another alternative would be to have two separate controls, one to display the score, "W+50.5", and a button next to it labelled Details.]

This is actually a good idea.

**Comment by wctgit** [comment]
>It's hardly constructive criticism, since you didn't say what exactly can be changed. 

But I did. Maybe not as directly as I could have, but here are examples from that comment:

> _Instead of being under Preferences or Game Info,_ you have to click on the score display within Score or Estimate _[with the implied suggestion being that this toggle could be put under Preferences or Game Info.]_
> ...
> For example, one of his principles is that _a single control on an interface should ideally have a single function:_ the score display violates this principle by acting as both a simple display and as a button, with no additional visual affordance to indicate that it might be a button _[with the implied suggestions that you could either make the one control into two separate controls, or add some visual affordance to indicate it is a clickable control.]_
> ...
> _Compare this with a hyperlink, ..._ [with the implied suggestion that you could change the control into a hyperlink, possibly, as one example.]

...
>Also I don't know the book and am hardly willing to read it just for you. 

Obviously, I didn't suggest for you to read it _just for me_. In fact, I didn't even suggest for you to read it at all. I simply referenced it by link so that you'd know what book I was referring to. If you _were_ to read it, it would be for your own sake, obviously, not mine. I don't suggest people do things _just for me_ in the first place. If I didn't care about the success of this project at some level, I wouldn't have posted anything here at all. It takes time and effort to write an Issue report and follow up on the comment thread. There are plenty of other things I could spend my time and effort on. I chose to contribute to _this_ project rather than some other.

> Furthermore, I didn't study Human-Computer Interaction.

You needn't have had to. I'm just explaining how I know about the book and what field it is typically associated with (though it's even more general than HCI). You seemed to be wondering why I referenced a 15-30 year old book. Hence, I explained why.

But all of that is kind of irrelevant as to whether or not to support different Go rule sets, or how to make the scoring mode more accessible and usable. It's just background information. 

>> Also, I didn't quote the book, but referenced it from my memory of it.
>
> Let's not argue about formal definitions. My argument still stands if you change one wording for another.

Actually, regarding whether I quoted the book or referenced it from memory, I'm not exactly sure what your argument is, to be honest. What would it matter either way?

>> [ETA: Perhaps making the score estimator have two lines, one for area, one for territory, would be reasonable, and reduce the need to switch 'modes'. ... ]
>
> I did indeed miss this, but please do explain yourself further.

Not sure what else to say. Right now it has a single line saying:
```
[W+50.5]    Toggle group status     [x]
```

Just make it two lines:
```
Area:      [W+50.5]    Toggle group status     [x]
Territory: [W+45.5]
```

> That's exactly the button I'm referring to.

Okay then, that's the button that has two functions, and one of them is not obvious (being the Details button where scoring mode toggling is hidden). That's the button I'm suggesting to either: 
1) Make it two controls, a Score display, and a separate Details button, or 
2) Make it more obvious it's a button by adding visual affordances to it, such as by making it a hyperlink instead, or 
3) Don't hide the scoring method toggle inside it; instead put the scoring method toggle in Preferences or Game Info, or 
4) Partially eliminate the need for a scoring method toggle by showing both area and territory scoring on the same panel, as above, or 
5) Something else if you prefer.

>> Just for reference, other Go UIs such as the WGo UI display both territory and area scoring when you select Count Score from its hamburger menu.
>
> No contradictions here. And I think WGo can be customized either way.

I wasn't pointing out a contradiction, I was giving an example of another Go UI that already partially eliminates the need for a scoring method toggle by simply showing both scoring methods simultaneously, as above, suggestion 4. 

> I'm not a fan of how opening an SGF file can change a user's setting.

I disagree with your assumption that the scoring method is a property of the user's settings. IMHO, it should be a property of the _game's_ settings. Therefore, it can and should be different depending on the SGF file, because that's where the scoring method (i.e. rule set) is specified. IMHO. Maybe the user's settings could include a 'default scoring method' for when they make a new game from scratch, but when loading existing games, which used pre-determined (i.e. before the game even began) scoring methods, I think the UI should reflect the game's settings primarily, and the user's settings should only be a default, if the game has no rule set specified. IMHO, of course. (Just assume I have 'IMHO' tacked on at the end of each sentence.)

> Also, if the score has already been calculated, there is no need to calculate it again with the scoring tool.

I'm not sure what this is referring to. Perhaps you mean the final game result?

>> [ETA: Another alternative would be to have two separate controls, one to display the score, "W+50.5", and a button next to it labelled Details.]
>
>This is actually a good idea.

Thanks, but it's not really my idea. It's Don Norman's (or rather, I got it from his book; he probably learned it somewhere else, I'm guessing), namely the principle that each user control should have only one obvious function -- the corollary being that if you need to put in two functions, put in two separate controls. It's not a 100% all the time thing, it's just a principle. But a good one. From a time-tested book by a well-known researcher and engineer. (In case you were wondering where I got it from. Whether you read it or not is not my concern.)

**Comment by yishn** [comment]
> Perhaps you have a more concrete suggestion instead of criticizing with a quote from a 16 year old book? *[with the implied suggestion you might want to say something more concrete than implied suggestions... Oh wait, it's an actual suggestion]*

Anyway, to simplify this thread: 

* 		Area:      [W+50.5]    Toggle group status     [x]
		Territory: [W+45.5]

	Don't like it since it takes up two lines instead of one.
* > Also, if the score has already been calculated, there is no need to calculate it again with the scoring tool.

	Not sure what else to say. Scoring the game only makes actual sense if it is your own game, since finished SGF files already have the score in its result field. One can take an SGF file and start playing from somewhere in the middle with an engine and score the game their way.
* I think the best way to avoid the double concern is to let the button show 'Details' and have another label to show the score for those who don't realize the 'visual affordance' I put into the button.
* In any case, I wanted some good reasoning to do something, not just a quote or a reference or whatever to a 'well-known researcher'. Controls which have more than one function are quite common nowadays. It's a great way to provide functionality without cluttering the UI. You just have to look at Apple's iOS, well-known for its design and UX. 

While I appreciate everyone who takes their time with my projects, your [second post](https://github.com/SabakiHQ/Sabaki/issues/341#issuecomment-368487696) wasn't constructive criticism at all despite your flimsy justifications and hit a nerve. Especially by referencing a book to avoid giving any reasons yourself raised a red flag in me.
