### ISSUE TITLE
Include player rankings in player name display

### ISSUE THREAD

**Issue by wctgit** [SabakiHQ/Sabaki#343]
Currently, you have to go to game info to see the player rankings. It would be much more convenient, when browsing multiple games, to also show the rankings right next to the names in the main window. Perhaps in brackets or slightly visually distinguished from the name itself.

**Comment by yishn** [comment]
Currently, the ranks are also displayed in tooltips: When you hover over the names and wait for a bit, its rank will show up. I agree it can be tedious and it would be better to display the ranks next to the names.
