### ISSUE TITLE
Set keyboard focus to main game window after loading a game

### ISSUE THREAD

**Issue by wctgit** [SabakiHQ/Sabaki#344]
Currently, you have to click somewhere on the main game window (but don't click on the actual board, or you might accidentally add a new move/variation to the game!) in order to be able to use the keyboard shortcuts to navigate the game (e.g. up and down arrows). This extra step is really unnecessary and counter-intuitive (i.e. frustrating), especially when browsing through multiple games. Please have the keyboard focus default to the proper context for allowing game move navigation immediately after a game has been loaded.

**Comment by yishn** [comment]
I don't know what you mean... Where is the keyboard focus if not on the main game window?

**Comment by wctgit** [comment]
I don't know where it is, but it's not on the main window. To replicate: Use Ctrl-Shift-M to open Manage Games dialog, select one of the games in the dialog (add some first if none there) using the mouse -> the game opens. Now try using down arrow to navigate to the first/next move -> it doesn't work. Now click on the main window somewhere, then try down arrow again -> Now it works.

**Comment by yishn** [comment]
I can reproduce this now, thanks!
