### ISSUE TITLE
Teach beginners basic shapes by highlighting shape stones based on auto-annotation

### ISSUE THREAD

**Issue by wctgit** [SabakiHQ/Sabaki#346]
Enhancement request: If the auto shape annotation lists Tippy Table, for instance, slightly highlight the stones which comprise that shape: change colour slightly, background, add an overlay highlight, whatever. This would be helpful for noobs like me to be able to visually spot the shapes better. Can be enabled/disabled in preferences.

**Comment by yishn** [comment]
This feature will be available in the upcoming Sabaki release.
