### ISSUE TITLE
Handling of conflict in discussion threads

### ISSUE THREAD

**Issue by wctgit** [SabakiHQ/Sabaki#348]
@yishn,
I have no problem with the fact that you responded to me with your comment https://github.com/SabakiHQ/Sabaki/issues/341#issuecomment-368690688. The problem I have is that you locked the discussion after writing several 'jabs' at me to which I apparently am not supposed to respond to. That's just not a fair way to handle conflict in discussion threads. A fair way would be to either close the thread with a neutral comment (or no comment), or allow for the [right of reply](https://en.wikipedia.org/wiki/Right_of_reply).

I'm not going to bother dragging this on, since it's clear you don't want me to. I'll just state my overall opinion and be done with it: Speaking of 'not being constructive criticism', your reply is extremely hypocritical, being the most nonconstructive comment in the thread, and not conducive to an atmosphere of cooperation. People don't like being treated unfairly. That's just human nature. You say my second post 'hit a nerve' and 'raised a red flag' in you. That's entirely on you. It was written as constructive criticism. You interpreted it in some other way. But to say it wasn't constructive criticism, especially after I laid out the suggestions it contained in detail, is simply doubling down on your initial misinterpretation. Again, that's entirely on you. Neither of those are justification for handling the thread unfairly.

It's too bad you react to the mention of books and other references with 'red flags', but I'm not responsible for your reactions. I **am** responsible for my own reactions. And my final reaction is, "Whew! This is not worth the bother. I'll just make a final statement for the record, and that'll be that." And that's that.

[And for the record, I initially was going to send a private message instead, but could not find a way to do so on his user page. I presume because we aren't 'friended' or whatever. Hence, this public response.]

**Comment by yishn** [comment]
I already said I do not want to discuss any further. Any more of this and you will be blocked.
