### ISSUE TITLE
How to add Engines in  Web Version?

### ISSUE THREAD

**Issue by fredzhang2018** [SabakiHQ/Sabaki#349]
Sabaki has a web branch，It‘s great. How to add Engines in  Web Version? There is no menu in web. Tks!

**Comment by yishn** [comment]
There are no engine functionalities in the web version since the web doesn't allow the web page to run system applications for security reasons.

**Comment by fredzhang2018** [comment]
I have configured leela  engine in windows sabaki engine ,Now I want to know how to attach leela  engine in the web version. then I can play against leela via internet. 
       Pease browse this site: https://langwiki.org/tools/weigo/ .this is other person's web site , this site  can change engin to '机器人小薇', then play with '机器人小薇' via internet.
