### ISSUE TITLE
How to attach engines in Web Version? 

### ISSUE THREAD

**Issue by fredzhang2018** [SabakiHQ/Sabaki#350]
I have configured leela  engine in windows sabaki engine ,Now I want to know how to attach leela  engine in the web version. then I can play against leela via internet. 
Pease browse this site: https://langwiki.org/tools/weigo/ .this is other person's web page , you  can change engin to '机器人小薇' in this web page, then play with '机器人小薇' via internet.

**Comment by yishn** [comment]
That's pretty neat! Please contact the owner of langwiki.org to find out how they did it. Sabaki doesn't support this feature out of the box.

**Comment by fredzhang2018** [comment]
@yishn 
Can you add this function into web version?

**Comment by yishn** [comment]
I don't know how; as I said, I'm very interested in how this person did it.
