### ISSUE TITLE
Horizontal lines for alternative variations disappear from the tree if they're far away

### ISSUE THREAD

**Issue by ohyou** [SabakiHQ/Sabaki#354]
If the sgf file has many variations for every single move (e.g. a joseki dictionary), when you drag right to see them, the lines towards them disappear. The lines reappear as you approach them closer.

Steps:

1. Open a big sgf file (e.g. kogo's joseki dictionary: http://waterfire.us/joseki.htm)

2. Start dragging right to get to the other variations for the first few moves

Expected behavior: it would be possible to trace the lines until you reach the alternative move  
Current behavior: the lines disappear, but when you approach the alternative moves closer they reappear again

Gif demonstration: https://i.imgur.com/sVyPXdX.gifv

Sabaki version: v0.33.3  
OS: Windows 10

**Comment by yishn** [comment]
For performance reasons, Sabaki only renders nodes if they are visible and lines if one of their endpoint nodes is visible (or nearly visible). This is something that can't be fixed without sacrificing performance severely, especially in the case of Kogo's Joseki Dictionary, so I'm marking this as wontfix.
