### ISSUE TITLE
Can sabaki offer/adopt the waltheri/wgo.js theme/color/style 

### ISSUE THREAD

**Issue by hydrogenpi** [SabakiHQ/Sabaki#355]
I like the look and style of this better

https://github.com/waltheri/wgo.js

Can it be made an optional theme?

**Comment by yishn** [comment]
Check out the [theme directory](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/theme-directory.md) or [make your own userstyle](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/userstyle-tutorial.md).

**Comment by 3kakakhel** [comment]
I understand this issue thread is closed, but this issue thread inspired me to make just such a theme. See my [repository](https://github.com/3kakakhel/sabaki-wgojs-theme). I welcome any feedback to improve the theme.
