### ISSUE TITLE
Use GTP Engine without assigning it to a player

### ISSUE THREAD

**Issue by bdrose** [SabakiHQ/Sabaki#356]
It might be nice to enable the generate move function without having to assign an Engine to a player first. Perhaps it could be done as selecting an engine to be active for the session or something like that. This would make reviewing .sgf games slightly easier and cleaner.

**Comment by yishn** [comment]
So... instead of assigning an engine to a player, we would assign an engine globally? What difference in behavior do you have in mind?

**Comment by bdrose** [comment]
Currently the F5 hotkey does work for both players, but you need to assign an engine to at least one player for this to work. The idea being that you can scroll through an sgf and get to the more difficult moves and have the engine do that step for whichever player that is. Assigning an engine to a specific player is a minor nuisance is all. It slightly misrepresents that the bot can play for both players if you force the engine to make a move.

**Comment by bdrose** [comment]
Fair enough. Thanks for the clarification and history.
