### ISSUE TITLE
Sabaki unresponsive at game end when using 2 engines

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#359]
On Windows 8 at least, when I attach 2 engines, and the game ends (either due to resignation or double-pass) Sabaki becomes unresponsive and unable to accept any input.

(As an exception, the New Window command in the menu still works.)

The standard Windows "busy" icon (a rotating circle) shows up.

**Comment by fohristiwhirl** [comment]
Are you able to reproduce this, or is it something about my setup?

**Comment by yishn** [comment]
Yes, I can reproduce this, thank you!

**Comment by fohristiwhirl** [comment]
The patch seems to fix the issue for double-pass, but not for resignation.

**Comment by yishn** [comment]
Thanks for the pointers; can you try if it's fixed now?

**Comment by fohristiwhirl** [comment]
That seems to work now.
