### ISSUE TITLE
Custom Theme: Coordinates are difficult to read.

### ISSUE THREAD

**Issue by 3kakakhel** [SabakiHQ/Sabaki#361]
I made a custom theme for Sabaki which you can find [here](https://github.com/3kakakhel/sabaki-walnut-theme). I made an [issue](https://github.com/3kakakhel/sabaki-walnut-theme/issues/1) for this issue on my repository. Not sure if putting the issue here is better or not.

As you can see from the screenshot, the coordinates are difficult to read. They look almost as though the intention was to have a sort of carved or inset look but it does not match with my theme. I took a quick look at the `styles.css` and `package.json` files, but was unable to figure out how to fix the issue.

Note: The lines may appear blueish. This effect pay be due to jpg compression or size of the image or something. The lines are actually black on my computer and in the screenshot in the main readme file.

![screenshot-coords-problem](https://user-images.githubusercontent.com/4513966/38158589-bed2c86a-3454-11e8-9754-e42c0e800b56.jpg)

**Comment by yishn** [comment]
Look at `goban.css` for Goban styles. Also you can [turn on the developer tools](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/debugging.md) to debug styles. For text color, the following rules should overwrite it:

~~~css
.goban {
  color: black;
  text-shadow: none;
}
~~~

**Comment by 3kakakhel** [comment]
Thanks for the help! I did not find a goban.css file, but I was able to
modify my style.css file in the manner you suggested. And it worked. I was
intending to document the fix in the issue thread, but I see you already
closed it. No matter. Thank you again!

**Comment by 3kakakhel** [comment]
How convenient: replying to the email automatically posts the response here on github as well.

I see. You meant Sabaki's own internal `goban.css`. I thought you were referring to a `goban.css` from the style itself. I like it being in the style itself so I will go with that. Other themes do not seem to have this same issue anyway.

And now to show that the fix worked.

![screenshot-coords-fixed](https://user-images.githubusercontent.com/4513966/38259068-5972784c-3721-11e8-951f-17b135c56792.jpg)

**Comment by yishn** [comment]
I think you're misunderstanding me. I'm not saying you should *change* `goban.css` to adapt it to your style, but rather *study* it, so you know which rules to overwrite in your style. I hope that clears up the confusion.

**Comment by 3kakakhel** [comment]
Ah. So the `style.css` file overwrites the info I the `goban.css` file. So
I can use that file to find out what the formatting is and what options
there and what values they have. Knowing that, I can know what to overwrite.
