### ISSUE TITLE
Feature request: save as gif

### ISSUE THREAD

**Issue by ivysrono** [SabakiHQ/Sabaki#366]
https://github.com/hex2010/sgf2gif : crash on Win10
https://github.com/alcortesm/sgf2gif : Dead stones are not removed from the board.

**Comment by yishn** [comment]
Thank you for your suggestion, but I don't think this feature has a place in Sabaki. Why don't you open issues on the projects you've posted to let them know about the bugs?

**Comment by fohristiwhirl** [comment]
@ivysrono - I was bored and this was an interesting idea for a project.

https://github.com/fohristiwhirl/sgf_to_gif

Let me know if this works for you.
