### ISSUE TITLE
I cannot restore top menu.

### ISSUE THREAD

**Issue by Marcin1960** [SabakiHQ/Sabaki#368]
I was checking display options and I turned off the top menu bar.

Now I cannot turned it on back, I guess because it is in the menu bar :(

**Comment by Marcin1960** [comment]
I "solved" it.

C:\Users\Win7\AppData\Roaming\Sabaki\settings.json can be edited manually

**Comment by yishn** [comment]
Press Alt key to bring up the menu

**Comment by yishn** [comment]
Every time you hide the menu bar, a notification will pop up for ~3sec saying you can press the Alt key to show the menu bar.
