### ISSUE TITLE
Detach seems broken

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#371]
I upgraded to current (i.e. the tip of the master branch). But detach seems broken. Not sure if it was broken before.

Reproduction

* Start a game with 2 engines.
* Let them play a few moves.
* Press escape.
* Detach.
* Play a move by yourself.

The engines will now start again.

**Comment by yishn** [comment]
Thanks for the report. I think it has something to do with the recent restructuring of engine handling in master.

**Comment by 5525345551** [comment]
Phew,

I thought it was something I broke when i started adding hacking on Sabaki and leelasabaki,
What a relief to know it was broken before. :)
