### ISSUE TITLE
Compile/Building error on Linux

### ISSUE THREAD

**Issue by kerra** [SabakiHQ/Sabaki#373]
I am currently under Linux  and trying to compile Sabaki. After following the commands at [Building & Tests](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/building-tests.md) I get the following Exception/Error:

`NotImplementedError: The plugin used by 'desktop-gtk2' does not support cross-compiling to a different target architecture
  ⨯ exit status 1
`

[log.txt](https://github.com/SabakiHQ/Sabaki/files/1934862/log.txt)

**Comment by yishn** [comment]
It seems like the new electron-builder version automatically builds snap packages on Linux which causes this error. I've edited the config so it only builds AppImages.
