### ISSUE TITLE
Refactor broke rotation

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#383]
In rotation.js I used custom min and max functions because the things being compared were strings. Math.min and max won't work.

(I'm sure there's a better way but it's broken for rectangular point lists e.g. try this...)

```
(;GM[1]FF[4]CA[UTF-8]SZ[19:17]AB[bb:jc];B[pq];W[cp];B[ep];W[eq];B[fq];W[dq];B[fp];W[cn]
;B[jp]AR[dj:jd]LN[ld:jj]MA[cn][cp]TR[ep][fp][fq]SQ[jp]
LB[nj:A][nl:B][nn:C][pj:1][pl:2][pn:3]CR[pq]LB[cd:hi])
```

**Comment by yishn** [comment]
I see, it seems I was a little bit overzealous... Thanks for the clarification!
