### ISSUE TITLE
Can fb's new OpenGo be compatible with Sabaki

### ISSUE THREAD

**Issue by hydrogenpi** [SabakiHQ/Sabaki#385]
https://github.com/gcp/leela-zero/issues/1311

https://github.com/pytorch/ELF/issues/1

**Comment by yishn** [comment]
What's the issue here exactly?

**Comment by hydrogenpi** [comment]
Facebook put out an open source AI program that plays at the level of AGZ.
However they did not publish the training data/ raw self playing games. 

Leela Zero Project took the network of the Facebook Go bot and converted it into LeelaZ format and now its up and running like a native network, Leela Zero also did a recompile for that to work seemlessly.

So actually there is not any more issue. 
I have tested LZ-ELF in Sabaki and it works fine.
