### ISSUE TITLE
Coordinate Themeing

### ISSUE THREAD

**Issue by myrmidongs** [SabakiHQ/Sabaki#386]
I've been digging around, but from what I can tell currently it is extremely difficult to change anything about the coordinates. At the very least, it would be nice to be able to modify their color and the yellow "drop shadow" on them.

**Comment by ParmuzinAlexander** [comment]
.goban {
color: black;
text-shadow: none;
}

**Comment by myrmidongs** [comment]
Thanks, probably would have tinkered around and found it evnetually but that certainly clears it up
