### ISSUE TITLE
How long would it take Sabaki dev to fork Lizzie

### ISSUE THREAD

**Issue by hydrogenpi** [SabakiHQ/Sabaki#387]
How long would it take Sabaki dev to fork Lizzie, refactor it for Electron, and to integrate autogtp self training and contact the official devs of Leela Zero for them to embed Sabaki into each download?

**Comment by hydrogenpi** [comment]
https://github.com/SabakiHQ/Sabaki/issues/358

**Comment by yishn** [comment]
Probably as long as it takes

Until the stars fall from the sky
Until the rivers all run dry
In other words, until I die

Until the sun no longer shines
Until the poets run out of rhymes
In other words, until the end of time

Until two and two is three
Until the mountain crumbles to the sea
In other words, until eternity

###### Lyric courtesy of Arctic Monkeys
