### ISSUE TITLE
Tencent open sourced, AlphaGo still closed

### ISSUE THREAD

**Issue by hydrogenpi** [SabakiHQ/Sabaki#388]
One benefit of pushing forward open bots that are superhuman is it may force the hand of others as well, now that Fb and Tencent have open sourced their bots that are both much stronger than LZ, maybe Deepmind will come back for thirds and get a fourth place prize in openness to cheapshot score one last PR hooray for Google by open sourcing their AGZ weights to spit in fb's face and to show whos the alpha by mastering the Chinese competition once again.. open competition is good for go. This is truly the end of a human era.

**Comment by yishn** [comment]
The issues section of this project is for issues only. For having discussions, please do it on lifein19x19.com or somewhere else.
