### ISSUE TITLE
GTP console output not matching reality

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#393]
I'm not quite sure what's happening but when I watch two copies of Leela Zero play each other something becomes confused in the GTP output. (As far as I can see, the actual game proceeds normally).

e.g. https://i.imgur.com/5fbTANm.jpg

Here D12 has been played, and is seen in the console, but when the move is being relayed to the other engine, it says "play W G4" instead. (Again, I think this is not affecting the actual GTP messages, just this display.)

**Comment by yishn** [comment]
Does it happen sporadically or all the time? Does it happen with other engines? Did you start generating moves in the middle of the game tree?

Internally, Sabaki does not relay the result of `genmove` to the other engine directly, but rather keeps the board state of both engines and try to sync them to Sabaki's board state before `genmove`.

**Comment by fohristiwhirl** [comment]
It seems to start after a while. LZ is really the only engine I have. But a fastish reproduction might use `time_settings 0 2 1` as an initial GTP command to LZ.

**Comment by fohristiwhirl** [comment]
Are the GTP commands sent and the engine responses stored in some sort of list? I feel like such a list is becoming shuffled, or something.

**Comment by fohristiwhirl** [comment]
Were you able to reproduce this at all?

**Comment by yishn** [comment]
Yes, I could reproduce it... There's a mismatch of commands and responses somehow.

**Comment by yishn** [comment]
@fohristiwhirl I think I fixed it... Can you see if this issue still persists on your end?

**Comment by fohristiwhirl** [comment]
Thanks - things seem to line up correctly now, as far as I can tell.
