### ISSUE TITLE
Putting Sabaki in a div box and resizing it

### ISSUE THREAD

**Issue by czabo** [SabakiHQ/Sabaki#394]
Hi,

I want to integrate Sabaki as part of a website. It works fine, but no matter how I resize the div box I am putting the interface in, the website always shows the Sabaki interface in the whole window. I would like to be able to put the interface in a div box, resize it and finally place it somewhere on a particular website. 

At the moment it seems the interface fills up the whole <body> and ignores div boxes.

I already played around with css files, but I wasn't able to fix that.

Thanks,
Any help is greatly appreciated

**Comment by yishn** [comment]
Have you tried assigning your container `div` the `position: relative;` style? A cursory search on the code base reveals that some elements (Busy overlay, drawers, ...) have fixed positioning, which is not optimal for including Sabaki in a container `div`. I think we can change those to absolute positioning without any complications.

**Comment by czabo** [comment]
I just tried it out, but still the same issue. I see. OK thanks for the help!

**Comment by yishn** [comment]
Oh, I see, Sabaki uses Preact, a view framework. Currently, Preact will inject all the elements into `document.body` [here in App.js](https://github.com/SabakiHQ/Sabaki/blob/web/src/components/App.js#L1989), so that has to be changed to your `div` container... Let me know if this helped!

**Comment by czabo** [comment]
Ok, I changed it to the div container but still no different result it seems.

**Comment by climu** [comment]
Hi,

Changing `document.body` to `document.getElementById("sabaki")` in `App.js` indeed loads sabaki inside the `<div id="sabaki">`.

Then it's just css. I fear there will be quite some css tweaks to have it work properly but that's doable. I ll dig into that later.

**Comment by climu** [comment]
Sure thing. At some point, I ll fork so you can follow what we are doing and we can discuss PR.

**Comment by climu** [comment]
Allright, I pushed a first draft in [this commit](https://github.com/climu/Sabaki/commit/3fa1321285502c5ad181d321a6df5d053b4edf0f).

Issues so far:

- The `#input-box > .inner` element is wrongly placed (top black rectangle on printscreen). I failed to understand what this element does so I don't know where to place it.

- The menu toggle icon behaviour is wrong now: 
    - click a on the menu icon once open it.
    - click again will open another menu on top of the other instead of closing it.

Do you have any idea how I could have mess with the menu behaviour?

![sabaki-in-div](https://user-images.githubusercontent.com/2648653/40414098-b096592c-5e77-11e8-9268-edc5c0e4c379.png)

**Comment by yishn** [comment]
The input box and drawers are visible because Sabaki does not hide them explicitly, it just moves them out of the viewport, in this case `#sabaki`. Maybe add `overflow: hidden;` to `#sabaki`?

As for the menu, Sabaki creates a `#popupmenu-overlay` element which covers the entire UI when the menu opens. It will intercept any clicks from outside the menu itself so Sabaki can close the menu. Maybe it's somehow positioned wrongly? The styles for the menus in the web versions are [located here](https://github.com/SabakiHQ/Sabaki/blob/web/src/modules/shims/Menu.js#L40).

**Comment by climu** [comment]
Thanks. `overflow: hidden;` on '#sabaki' worked fine.

There is still quite some issues with elements being wrongly positioned and sized. I ll keep digging

**Comment by climu** [comment]
@yishn : Are the elements size calculated by some js function? Would such calculation be relative to the viewport size?

If no it's only css. If yes, we might need to change this resize js function. 

Thanks for your help!

**Comment by yishn** [comment]
@climu I've fixed the bugs in the most recent version of Sabaki Web. Can you try and see if the menu is working on your end now?

I think size calculations are always relative to the viewport size, but I'm not entirely sure.

**Comment by yishn** [comment]
I've slept on this and I think in general, the easiest and correct way to include Sabaki into a web page is via an `<iframe>`. There are several issues when including Sabaki in a `div`:

- Styles: Sabaki's styles are not isolated; they can interfere with the parent web site and vice versa
- Sabaki uses `id` on HTML elements, which can interfere with the parent web site. This also prevents one from having multiple instances of Sabaki on a web site.

**Comment by climu** [comment]
Makes sense. I guess we will go this way.

Thanks for your work.

**Comment by climu** [comment]
For the record we never added sabaki using `iframe`.

I think the proper way would be to use your work to create a sgf viewer that would load inside a html element of a website as [wgo](http://wgo.waltheri.net/) does. It could be usefull for website who wants to show a sgf viewer easily.

One could create that using your libraries (shudan, go-board, sgf) with inspiration from sabaki.

I fear it's a bit over my head so I will pass on that. Just sharing thoughts in case anyone comes here.

**Comment by climu** [comment]
[Here](https://github.com/Awea/wshudan) is an attempt.
