### ISSUE TITLE
a question in savefile function

### ISSUE THREAD

**Issue by xiarx2016** [SabakiHQ/Sabaki#396]
Hi! My friend, thank you to develop this wonderful software --- sabaki ,It's really good and useful !
But I find when I save a game to sgf files，some node will be ';W[pi];B[qi] ' .
As you know ,the letter 'i' is not allow to use in sgf files. This will make some mistake when I want to use the file. Can you  help me to correct it ? 
Thanks!

**Comment by yishn** [comment]
Thank you! Please consult the [SGF specification](https://www.red-bean.com/sgf/), especially the [page on Go](https://www.red-bean.com/sgf/go.html). You will see that SGF indeed uses the character `i` for coordinates.

**Comment by xiarx2016** [comment]
Yes , you are right!
The letter 'i' is not allow to use in gtp engines.
