### ISSUE TITLE
When 34 release is planned?

### ISSUE THREAD

**Issue by Marcin1960** [SabakiHQ/Sabaki#398]
When 34 release is planned?

**Comment by yishn** [comment]
Sometime today

**Comment by Marcin1960** [comment]
It would be great to have option to play several games for testing. Let us say 10 games or unlimited.

Tabled results would be perfect, but I even do not dare to ask ;)

**Comment by yishn** [comment]
Please open a new issue with a detailed description of the workflow you'd like, which UI changes you propose, etc...
