### ISSUE TITLE
Leela Zero not working

### ISSUE THREAD

**Issue by ParmuzinAlexander** [SabakiHQ/Sabaki#400]
Sabaki 34 and Leela Zero not working. After thinking time move not play.

**Comment by d7urban** [comment]
They work for me

**Comment by yishn** [comment]
What OS are you using? Did it work in previous versions? Does the GTP console show any activity?

**Comment by ParmuzinAlexander** [comment]
Windows 8.1 x64. Leela Zero 0.15. Work in v0.33.4. PhoenixGo work in v0.34.0. In log file i see move, in Sabaki console not.

**Comment by ParmuzinAlexander** [comment]
The problem was time_settings 0 10 1;  need without ;

**Comment by yishn** [comment]
Is this issue resolved now or why did you close.it?

**Comment by ParmuzinAlexander** [comment]
Yes solved.
time_settings 0 10 1; not work
time_settings 0 10 1 work
