### ISSUE TITLE
Shortcut key for comments box

### ISSUE THREAD

**Issue by ashleylester** [SabakiHQ/Sabaki#402]
I really like how Sabaki feels, great job.

Is it possible to implement the ability to reach the comments box without having to use the mouse? I understand that ctrl+e puts me into edit mode, and that my right hand is free to use the mouse straight away to edit stones. But often I am commenting on my moves, or the moves of other players, without wanting to edit the pieces on the board. E.g. I hit ctrl+e and then make a comment and then hit ctrl+e and then play a variation and then hit ctrl+e and then make a comment (etc). Having to reach for the mouse each time after I hit ctrl+e in order to put the cursor in the comments box feels a bit awkward. E.g. we could have ctrl+e TAB to put us into the comments box.

Thanks for your input!

**Comment by yishn** [comment]
I think we can focus the comments box right away when entering edit mode.
