### ISSUE TITLE
Leela Zero doesn't do anything? Version 0.34 broken?

### ISSUE THREAD

**Issue by Marcin1960** [SabakiHQ/Sabaki#404]
https://github.com/gcp/leela-zero/issues/1508

**Comment by yishn** [comment]
Can you please share your engine settings?

**Comment by Marcin1960** [comment]
I did not try version 0.34 on my machine yet.

I was considering updating but the report https://github.com/gcp/leela-zero/issues/1508 made me reconsider.

0.33 works for me and I will wait until this issue gets resolved.

**Comment by yishn** [comment]
It seems this is the same issue as #400. I'll release a patch today.
