### ISSUE TITLE
Is there a setting that displays the order number when opening the chess score?

### ISSUE THREAD

**Issue by lovepoem** [SabakiHQ/Sabaki#405]
![image](https://user-images.githubusercontent.com/827112/40887350-2eddcbfc-677a-11e8-91ee-c8222107db92.png)
Is there a setting that displays the order number when opening the chess score?  
As the picture displays。

**Comment by yishn** [comment]
No.

**Comment by lovepoem** [comment]
Can it be added？

**Comment by yishn** [comment]
Please subscribe to #154 for updates.
