### ISSUE TITLE
Thoughts on property editor

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#408]
The new feature is nice. Some comments...

I see you block B and W. But AB, AW, and AE can also potentially render the tree inconsistent. In the normal Edit Mode, using these things creates a new node, so should they be blocked in the advanced editor?

Second, the editor is a bit fragile to newlines, i.e. if I create a property, say TR, and type pq or whatever, and press return, it adds a newline, which isn't what I expected. I think a simple solution would be to strip/trim all leading/trailing whitespace before committing the property. If someone deliberately makes a multi-line value, well that's on them...

(Ideally, pressing return would exit the line editor for any property except C, I guess. But that sounds tricky to code.)

**Comment by yishn** [comment]
Thanks for your thoughts and suggestions.

I'd like to unblock B and W in the near future; I just don't have a clear plan on how to implement that yet without performance loss. As for the newline, maybe actual new lines can be inserted with <kbd>Shift</kbd>+<kbd>Return</kbd> instead?
