### ISSUE TITLE
Handicap games need special gtp commands

### ISSUE THREAD

**Issue by lemonsqueeze** [SabakiHQ/Sabaki#409]
Hi,
Following up on https://github.com/pasky/pachi/issues/82, it seems sabaki is sending handicap stones as `play b` commands instead of using dedicated gtp commands, so engines are mislead into thinking it's an even game. Pachi resigns high handicap games when playing through sabaki right now because of this.

For chinese rules `set_free_handicap` / `place_free_handicap` command should be used to send/get handicap stones. Or just `fixed_handicap` with japanese rules.

gtp2ogs had the same issue some time ago, could check https://github.com/online-go/gtp2ogs/issues/65 for details.

**Comment by lemonsqueeze** [comment]
Thanks, that was fast !
Just tried latest master with d755f2b, looks like it's still resigning though,
getting play b commands like before. Or did i miss something ?

**Comment by yishn** [comment]
Hmm... Did you check the GTP console if Sabaki was sending the right commands?

**Comment by lemonsqueeze** [comment]
Yes, looking at pachi's log actually. This is the commands i'm seeing for an 8-stones game:
```
boardsize 19
clear_board
play B D16
play B D10
play B D4
play B K16
play B K4
play B Q16
play B Q10
play B Q4
genmove W
```

**Comment by yishn** [comment]
How did you create the game? When I create an 8-stone handicap game in Sabaki and attach an engine, I get the following commands:

~~~
name
version
protocol_version
list_commands
komi 7.5
clear_board
set_free_handicap D10 D16 D4 K16 K4 Q10 Q16 Q4
genmove W
~~~

**Comment by lemonsqueeze** [comment]
Something weird going on then, i did:
Alt->File->New, (Don't save), then setup game and click ok.

**Comment by fohristiwhirl** [comment]
[Works for me](https://pastebin.com/TyiBVazb) (albeit I don't have Pachi to try it with).

**Comment by lemonsqueeze** [comment]
Wait, do i have to npm update or something to pick up the changes ?

**Comment by fohristiwhirl** [comment]
Yeah I think you'll need `npm install` and `npm run build` (it used to be that one could run `electron .` but that doesn't seem to work now...)

**Comment by lemonsqueeze** [comment]
Ok, working now, yay.
Basic npm commands in README would be helpful for those of us that are hopelessly unfamiliar with it =)

**Comment by fohristiwhirl** [comment]
`electron .` or `npm start` just hangs for me with no output in the console. (Electron is a bit useless if something stops it from working, I've found previously. I can't say exactly what the problem is.)

**Comment by fohristiwhirl** [comment]
Uh, I upgraded Electron and now `npm start` seems to work though `electron ./` doesn't. Odd.

**Comment by fohristiwhirl** [comment]
Arg! The upgrade hadn't taken me to Electron 2. Having fixed that, now it works properly.

**Comment by omidmnz** [comment]
This issue was fixed in version 0.35, but I just upgraded to version 0.40 and the issue seems to be back. Can anyone confirm?

**Comment by fohristiwhirl** [comment]
Tried just now, it used `set_free_handicap D16 D4 K10 Q16 Q4` for an H5 game.

**Comment by omidmnz** [comment]
Thank you.
I tried building 0.40.1, which has the same problem for me. I guessed it might be a cache issue, but the problems persists using the AppImage too.
But I'm still guessing this is a cache issue or something. I just tried removing the configuration directory, but it didn't help. It still plays all the handicap stones.
Any ideas what to look for next?

**Comment by fohristiwhirl** [comment]
Actually - the behaviour seems to differ based on how play is started.

With preferences "start game right after attaching" and "automatically generate engine moves" OFF, then when you do start, the `set_free_handicap` command is used.

But with those preferences set to ON, the `play` command is used instead.

**Comment by yishn** [comment]
Ok, I was able to reproduce it on v0.40.1, but it has already been fixed on master branch.

**Comment by omidmnz** [comment]
> Actually - the behaviour seems to differ based on how play is started.
> 
> With preference "start game right after attaching" OFF, the `set_free_handicap` command is used.
> 
> But with that preference set to ON, the `play` command is used instead.

Thanks. I can reproduce this exact behavior.



> Ok, I was able to reproduce it on v0.40.1, but it has already been fixed on master branch.

So the issue is still closed. :)
