### ISSUE TITLE
Can't compile correctly/run - Ubuntu 18.04 x64

### ISSUE THREAD

**Issue by joeftiger** [SabakiHQ/Sabaki#410]
I am trying to build the current version on a fresh Ubuntu 18.04 install, but I keep getting some warnings and a non-functional AppImage. 
`npm install` yields:

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
> npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.

Building the application (no warnings/errors) and running results in following error :
> module.js:545
>    throw err;
>    ^
>
> Error: Cannot find module '/tmp/.mount_sabakiBi8nUb/resources/electron.asar/browser/init.js'
>     at Function.Module._resolveFilename (module.js:543:15)
>     at Function.Module._load (module.js:473:25)
>     at Function.Module.runMain (module.js:683:10)
>     at startup (bootstrap_node.js:196:16)
>     at bootstrap_node.js:622:3

Sabaki won't open in any way and above error is only visible in terminal.

**Comment by yishn** [comment]
There's currently an issue with electron-builder building AppImages (see electron-userland/electron-builder#2958), please subscribe to #403 for updates. In the meantime, you can use `npm run build` to build executables on Linux.
