### ISSUE TITLE
Nothing shows up using remote display

### ISSUE THREAD

**Issue by SongXinkai** [SabakiHQ/Sabaki#411]
I'm using windows putty to login and do things on another linux(ubuntu 16.04) machine. When I downloaded the binary file "sabaki-v0.34.1-linux-x64.AppImage" in ubuntu machine and executed it, nothing shows up. It just waited for several seconds and then exit.
Did anyone try this way? And how it work?
I'm using Xming in Windows for remote display.

**Comment by yishn** [comment]
Can you try executing the AppImage file from the command line and see if there are any errors? Also make sure you have the rights to execute the file.

**Comment by yishn** [comment]
Did you try executing AppImage on your Ubuntu machine directly, without Putty or Xming?

**Comment by SongXinkai** [comment]
I tried executing it on the machine directly, it still don't work and shows "no protocol specified". Did I miss some steps?
Thx for your reply.

**Comment by yishn** [comment]
Can you try [building Sabaki yourself](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/building-tests.md) using 'npm run build' and see if you can execute the plain executable?

**Comment by SongXinkai** [comment]
Today I tried double click it in ubuntu-desktop and it worked fine. I will use it through iDRAC in windows machine. Thank you yishn and thanks for making sabaki. Really appreciate.

**Comment by yishn** [comment]
I’m glad you sorted it out!
