### ISSUE TITLE
Sabaki can't open correctly on MacOS 10.13.5

### ISSUE THREAD

**Issue by DingoT** [SabakiHQ/Sabaki#414]
can't open the Sabaki.app on my mac (OS 10.13.5)

**Comment by DingoT** [comment]
TelenggudDingodeMacBook-Pro-2:Applications Dingo$ open /Sabaki.app
The file /Sabaki.app does not exist.
TelenggudDingodeMacBook-Pro-2:Applications Dingo$ 

I copied the Sabaki.app to /Applications/ and I have no idea about this.

**Comment by yishn** [comment]
You're opening `/Sabaki.app`  instead of `/Applications/Sabaki.app`.

**Comment by DingoT** [comment]
It still can’t open. By the way, It also does not work when I double click the Sabaki.app icon.
Dr. Yuchao Liang
From Beijing Tian Tan Hospital

**Comment by yishn** [comment]
What happens when you open Sabaki by double clicking the Sabaki.app icon?

**Comment by DingoT** [comment]
It says: 

Application “Sabaki.app” can not open.

I used the “chmod” command on the app, but it still can’t open.

**Comment by yishn** [comment]
Hm... that is weird. Can you follow the [build instructions](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/building-tests.md) using `npm run build` and see if you can run your own build?

**Comment by DingoT** [comment]
It worked. 

Thanks all the same.

**Comment by yishn** [comment]
Then there's no bug in Sabaki, maybe you didn't enable installation from non-App Store apps? Either way, I'm closing this issue.
