### ISSUE TITLE
It's unclear how to resume an enigne vs engine game

### ISSUE THREAD

**Issue by jokkebk** [SabakiHQ/Sabaki#415]
I like to use Sabaki to play two GTP bots against each other (e.g. Leela vs. ELF). There's a helpful message that "press ESC to stop generating moves". I've done that a couple of times.

Now how do I resume generating moves?

There is no "resume". There is no "Play" button. There is no menu item that seems to directly do what I want. Most options that sound like they could work are dubious and I'm afraid it changes some settings. Like:

Play -> Toggle player -- does this "Toggle on" the engine, or does it switch players? What is this option?
Engines -> Attach... -- I already attached engines, should I maybe do it again? Or is this a wrong option?
Engines -> Detach and Suspend sound like they do the opposite. Suspend sounds like the ESC I just pressed. But there is no "Resume"? Why?
Engines -> Generate Move -- This sounds like what I'd like to do, but obviously it only generates one move. (Spoiler alert: It actually resumes the suspended game)
Tools -> Toggle Autoplay Mode -- sounds correct, but did nothing.

Maybe some kind of instructional message when pressing ESC to console "Resume with F5"?

Actual help file would of course be perfect.

Btw. excellent app otherwise!

**Comment by jokkebk** [comment]
I see, thanks, and also thanks for someone for clarifying the subject. 😄

**Comment by fohristiwhirl** [comment]
On the subject of engine vs engine games, one annoyance is that, on resignation, a new node is created with a pass from the resigning side, which is not what you want if you decide to resume the game somehow.

**Comment by yishn** [comment]
@jokkebk Now 'Generate Move' will generate one move only, and 'Start Playing' will resume an ongoing engine vs. engine game. In case only one engine is attached those two will do the same thing.
