### ISSUE TITLE
 Can't use ELFgo with sabaki?

### ISSUE THREAD

**Issue by 22nsuk** [SabakiHQ/Sabaki#416]
Hi, I'm a big fan of sabaki.
I have a problem and write about it.
I'm using ELFgo on Ubuntu 18.04.
ELFgo is available in gogui but not in sabaki.
On sabaki, ELFgo runs and selects move, but sabaki can't read it.
Then a popup appears. "current board arrangement can not be recreated on the gtp engine."
I wonder if this can be solved.
ELFgo is here : https://github.com/pytorch/ELF
Thanks

**Comment by yishn** [comment]
Are you starting with an empty board? Make sure the board doesn’t contain illegal stuff like stones with no liberties, non-square dimension, etc.

**Comment by 22nsuk** [comment]
@yishn I started on an empty board. ElFgo played but sabaki did not recognize it, and the popup came out the next time.

**Comment by yishn** [comment]
It doesn't seem like ELF is responding in a GTP-compliant fashion. Please make sure you have the engine set up correctly in GTP mode.

**Comment by yishn** [comment]
Ah, I'm perusing the issues in the official [ELF repository](https://github.com/pytorch/ELF/). Seems the engine doesn't correctly support GTP yet (see pytorch/ELF#33).

**Comment by 22nsuk** [comment]
@yishn 
According to the above link, and in my case, gogui will cause an error message, but actually ELFgo works well. But Sabaki does not work. Is there anything we can think of about this in sabaki?

**Comment by yishn** [comment]
No, we won't support it. Please contact the developers of ELF, so that they can fix the problem on their end.

**Comment by 22nsuk** [comment]
@yishn OK I see. Thank you for your reply.
