### ISSUE TITLE
About multilingual version，Chinese, Korean, Japanese，etc

### ISSUE THREAD

**Issue by SilverLeaves** [SabakiHQ/Sabaki#417]
Menu language is hard coded into the program. How can I contribute to other language versions of the menu? 
![snipaste_2018-06-30_18-02-14](https://user-images.githubusercontent.com/31165554/42124126-d9a38ec6-7c8f-11e8-8926-c2aa6b0d7f38.png)

**Comment by yishn** [comment]
You can't yet. Sabaki is not prepared for localization. Please subscribe to #384 for updates.
