### ISSUE TITLE
Missing images when built?

### ISSUE THREAD

**Issue by rooklift** [SabakiHQ/Sabaki#422]
I rebuilt Sabaki yesterday (also using npm install to update the dependencies). When I run `electron .` everything seems fine, but when I build a standalone app with `npm run build` the result seems to be missing some of its images somehow, e.g.

https://i.imgur.com/TOt3Lwf.jpg

This also affects the "hamburger" in the main screen, and the edit pencil.

The console gives:

https://i.imgur.com/oCiqyaJ.jpg

**Comment by yishn** [comment]
That’s interesting... I’ve updated the dependencies yesterday, so my guess is the new version of electron-builder somehow doesn’t include the dependencies anymore.
