### ISSUE TITLE
[REQUEST] - File name in managed games

### ISSUE THREAD

**Issue by rekolteur** [SabakiHQ/Sabaki#424]
Hi yishn,

First of all, thank you for your amazing work.
I would be very pleased if the name of sgf file would be displayed in the "manage game" view.
When I do some tsumegos, I  have no clue (except the 30th move screenshot) to guess what the file is (see hereunder, coming from the Cho Elementary collection).
![capt-20180711_192952](https://user-images.githubusercontent.com/41124888/42589414-2cee0dd6-8541-11e8-903e-0d842ba09eb2.png)

All thumbnail has the same name.
Thank you by advance to take into account this request.
Keep up the great job!!!
Regards,
Rekolteur

**Comment by yishn** [comment]
SGF collections are just multiple games inside one file. It doesn't make sense those games to have 'filenames'. Where did you find the SGF collection? Maybe you can contact the curator to let him know that you'd want to have different names for the games?

**Comment by rekolteur** [comment]
yishn,

No, it is not a single sgf file, but a one sgf file per problem.
Thus I have 900 sgf files for 900 problems.
You can find this archive (Cho Chikun Elementary) here : http://www.szabadsolyom.hu/go/?page_id=231

Regards,

**Comment by yishn** [comment]
I'm sorry, but we seem to have some sort of misunderstanding here... The 'Manage Games' dialog is for managing multiple games inside one SGF file. The fact that you have the games inside the 'Manage Games' dialog in one single window of Sabaki means you only have one file.

**Comment by fohristiwhirl** [comment]
I think he's importing a bunch of files at once with "Add Existing Files...". From a user perspective, you seem to be working with many files until you save, which you might never do.

**Comment by mlopezviedma** [comment]
Actually, in my opinion this request is very logical. Keep in mind that:
1) SGF format has a GN property for the name of the game record; and
2) The most common way of creating SGF collections on Sabaki is by loading more than one SGF file at once.

**Comment by rekolteur** [comment]
@fohristiwhirl:
You are perfectly right:
> I think he's importing a bunch of files at once with "Add Existing Files...". From a user perspective, you seem to be working with many files

@mlopezviedma : 
I thought, intuitively, that would be the process (loading more than one SGF file)

@yishn:
I will try to "clean" the game name of each single SGF file in order to fill it by the corresponding file name, then concatenate SGF files in an unique one. I will try that by the mean of a Python script.

@all: 
Thank you for having read my posts

Regards,

**Comment by yishn** [comment]
I'm closing this as the misunderstanding seems to be cleared up.
