### ISSUE TITLE
Keyboard seems unresponsive in large game collections

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#425]
* Make a fairly large game collection, e.g. importing 10 might be enough.
* Enter one of the games.
* Try navigating with arrow keys and Home / End.
* The keys seem to work only intermittently.

**Comment by yishn** [comment]
Seems related to #344

**Comment by fohristiwhirl** [comment]
Hmm, yes, it's true that clicking inside the window somewhere makes the keyboard work again.

**Comment by fohristiwhirl** [comment]
OK this is interesting: the bug only happens if there are enough games that the "manage games window" has a scroll bar. (Even though you can't see it when you're looking at the board.)

So I guess the manage games component (or whatever, I don't understand React) is still active and intercepting arrow / home / end keys.

**Comment by yishn** [comment]
Thank you for the explanation; yeah that makes total sense. I thought by setting `visibility: hidden;` on the scroll container is enough to prevent scrolling it, but it's not. So I've changed it to `display: none;`. That seems to fix this.
