### ISSUE TITLE
Compatibility with the Normal SGF files

### ISSUE THREAD

**Issue by psygo** [SabakiHQ/Sabaki#427]
First of all, I'm a huge fan of the program, I fall in love with it more and more everyday. Thanks for the contribution.

I've been having a somewhat annoying issue though, about the compatibility of the SGF files normally read by Cgoban and Sabaki. Sometimes, after edits, I get weird results when opening files with the other program. It varies from errors to stones being completely misplaced. 

I've attached two files related to the problems.

An example of an error I get sometimes:

![image](https://user-images.githubusercontent.com/11823725/43057113-8539a210-8e16-11e8-8aed-3621cec0c90d.png)

3 stones that got the wrong color when going from Cgoban to Sabaki:

![image](https://user-images.githubusercontent.com/11823725/43057129-a533c82a-8e16-11e8-99ff-2d478399216b.png)

On a sidenote, I would like to suggest some improvements to the editing bar:

1. I think the implementation of the stone tool in Cgoban is far more useful, which uses the Shift as the modifier.
2. I wish one could change the shortcuts, especially the ones for the function keys. Again, the ones from Cgoban make much more sense I think. (I also wish there could be an option to mix the editing mode with the playing mode, sometimes switching between the two is tiresome.)

**Comment by yishn** [comment]
Thanks for reaching out! It would be helpful if you could upload the invalid SGF file in question and describe reproduction steps that led to misplaced stones, especially how you created the SGF file with CGoban.

As for the stone tool, to place stones of the opposite color, you can use the right mouse click (assuming that switching colors is your pain point).

What shortcuts from CGoban make more sense? To quickly enter/exit edit mode, there's a keyboard shortcut <kbd>Ctrl+E</kbd>.

**Comment by psygo** [comment]
[Puzzle de Go.zip](https://github.com/SabakiHQ/Sabaki/files/2221887/Puzzle.de.Go.zip)

I don't really know a one-to-one procedure that will get me the bug, it happens to me sometimes and I don't really know why. It usually comes from when I do a lot of editing on the position to make an explanation clearer to the person I'm sending the SGF file (that's basically what happened with the attached files). Doing that kind of editing on either software seems to yield weird results on the other, if not just an error message.

With respect to my remark on the shortcuts, I think Sabaki could benefit from linking the function keys to the editing tools, like CGoban does. The right click on the mouse to change the color of the stone is a very nice idea, but my mouse keeps isn't very reliable for that, I don't know why. Probably only something that happens to me, so I won't complain of course. But still, being able to customize the shortcuts would solve that kind of problem and also increase the value of the software. Anyway, just a suggestion.

**Comment by yishn** [comment]
The `Puzzle 13x13.sgf` file was saved with 'UTF-8 with BOM' encoding while the `CA` property was set to `UTF-8`. After converting the file to plain UTF-8, Sabaki was able to open it. I don't know how this could have happened, since Sabaki always saves in UTF-8.

As for the other files, I don't see anything suspicious which might explain wrong stone colors. But I noticed that both `Puzzle 13x13.sgf` and `Puzzle 19x19.sgf` have an 'only child' (a subtree without any siblings) which Sabaki should have prevented. Now I'm really curious how you got to this state. Also, I noticed some SGF properties, that should only exist in the root node, in the subtree which leads me to believe that you used variation copy & paste? That also might be a problem for other editors. Sabaki should strip root properties when copying; this is a bug.

As for shortcuts of the edit tools, Sabaki uses <kbd>Ctrl+Number key</kbd> instead. This way, we can have the function keys for other things, to be consistent with other applications.

**Comment by psygo** [comment]
Both the `Puzzle 13x13.sgf` and the `Puzzle 19x19.sgf` files were created using Sabaki and then I encountered the error when trying to open it with CGoban. Indeed, I have used the `copy & paste` (there is also a paste function in CGoban, but what does it actually do there?) function when editing them. I don't know if eliminating copying the root node would be good for the users, it could make tsumego editing a bit of a pain I believe.

You might have realized it by now, but I'm not an English native speaker. I type mostly in Portuguese, but I set my Windows keyboard configurations to US English International. Could that be the reason why the file was saved with `UTF-8 with BOM`?

As for the last file, `Desafio 13x13.sgf`, it was created and edited with CGoban, and Sabaki seems to misinterpret the last node. I don't remember doing anything special actually, I really don't know what's going on there.

**Comment by yishn** [comment]
> You might have realized it by now, but I'm not an English native speaker. I type mostly in Portuguese, but I set my Windows keyboard configurations to US English International. Could that be the reason why the file was saved with UTF-8 with BOM?

I don't think so... Anyway, I think we should handle this case as well; strip BOM if we see one. I've created an issue at SabakiHQ/sgf#1.

> As for the last file, Desafio 13x13.sgf, it was created and edited with CGoban, and Sabaki seems to misinterpret the last node. I don't remember doing anything special actually, I really don't know what's going on there.

What is it supposed to look like? Looking at the SGF source code, Sabaki is interpreting everything [according to SGF spec](https://www.red-bean.com/sgf/ff5/m_vs_ax.htm).

**Comment by fohristiwhirl** [comment]
It seems like cgoban isn't handling the `W[bl]` in the penultimate node properly.

**Comment by psygo** [comment]
This is what I had edited originally in CGoban:

![image](https://user-images.githubusercontent.com/11823725/43217094-13ca5d2e-9017-11e8-86b2-9413fc14aede.png)

And this is what I get when opening it through Sabaki:

![image](https://user-images.githubusercontent.com/11823725/43217204-58e4a414-9017-11e8-9476-e6e8f6561b9a.png)

The penultimate node is also strange:

![image](https://user-images.githubusercontent.com/11823725/43217249-7de4848c-9017-11e8-8022-f87ae58e33e1.png)

According to fohristwhirl, maybe this is a bug inside CGoban and not Sabaki?
