### ISSUE TITLE
Captures not showing for white side

### ISSUE THREAD

**Issue by fmylifeuck** [SabakiHQ/Sabaki#429]
![capture not showing for white](https://user-images.githubusercontent.com/41874815/43369231-69e27902-9338-11e8-9473-a5de58ed8ad1.png)

Operating system is Windows 8.1* 64-bit and sabaki version is v0.35.0
I reinstalled the program but the problem persists. Captures made by black show up normally.

**Comment by fmylifeuck** [comment]
Yes. I saved the file, then reopened after restart and captures for white still not showing. I sent SGF file by email since I couldn't attach here. I first noticed this issue about a few weeks ago, before that it was fine. What other info do you need?

**Comment by fmylifeuck** [comment]
I couldn't upload the sgf on Github.



________________________________

**Comment by yishn** [comment]
I don't think you can upload files by sending them as attachments as email. You can just paste the source code here.

**Comment by fmylifeuck** [comment]
(
  ;GM[1]FF[4]CA[UTF-8]AP[Sabaki:0.35.0]KM[6.5]SZ[19]DT[2018-07-30]
  ;B[pd]
  ;W[pq]
  ;B[pp]
  ;W[qp]
  ;B[dd]
  ;W[dp]
  ;B[cn]
  ;W[op]
  ;B[dj]
  ;W[po]
)

Doesn't seem like there's anything wrong with the sgf.

**Comment by yishn** [comment]
Everything is okay, and on my machine, the capture count is shown correctly as well, but I only have access to Windows 10.... I honestly have no idea what is going on here.

**Comment by fohristiwhirl** [comment]
I'm on 8.1 and this doesn't happen for me. I don't suppose some theme is loaded? It certainly looks like the default in the pics.

**Comment by fmylifeuck** [comment]
Removing that folder worked. Thank you
