### ISSUE TITLE
File browser for opening files quicker

### ISSUE THREAD

**Issue by toomasr** [SabakiHQ/Sabaki#434]
Any chance of implementing a file browser on the left side of the app to open files quickly? My use case is that I solve Go problems on my PC and usually they are in folders where it is very easy to just double click on the next problem and have it open up.

I checked out the source code and will try to implement this myself but as my background is Java and not JavaScript/React/Electron then it is not very easy for me to make progress. Maybe you can provide some scaffolding and I'll try to implement this myself?

**Comment by yishn** [comment]
I do think a file browser sidebar is out of scope of this project and also tricky to implement one ourselves correctly.
