### ISSUE TITLE
Why leelasabaki can work , but cann't show heatmap in sabaki version 0.33.0 ?

### ISSUE THREAD

**Issue by xiarx2016** [SabakiHQ/Sabaki#435]
Hi，my friend.
I want to use leelasabaki in sabaki 0.33.0，because I have modified some place in the version.
When I build the leelasabaki and made it work in sabaki，but I find it just like the other gtp engines，cannn't show heatmap.
Do I make some mistake ?
thank you for your help!

**Comment by yishn** [comment]
Can you post your engine configuration?

**Comment by xiarx2016** [comment]
"name": "leelasabaki",
      "path": "leelaz015\\leelasabaki.exe",
      "args": "--heatmap leelaz -w networks\\2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9 --playouts 100 --noponder"

**Comment by xiarx2016** [comment]
I find that in version 0.35.0，leelasabaki will send a command "leelasabaki> sabaki-genmovelog " after "genmove". But in the version 0.33.0 after I modified ,It cann't send "abaki-genmovelog " command，maybe I make some wrong somewhere ?

**Comment by xiarx2016** [comment]
Thank you for your help. It's my wrong .Now I have found the bug and fixed it .Thank you again!

**Comment by yishn** [comment]
I’m glad you could solve it
