### ISSUE TITLE
Randomization of the black stones doesn't work properly in using themes

### ISSUE THREAD

**Issue by gheemuse** [SabakiHQ/Sabaki#441]
In case of using random white stones or one black stone, it works properly. But not case of random black stones. In case of using random black stones, Sabaki also displays the black stones of the default theme. Please check with 'Wgo.js Theme'. I've looked into the theme and found out it has no problem. I think Sabaki itself has the problem.
  (The latest version of Sabaki(v0.35.1), Windows 7)

**Comment by gheemuse** [comment]
Oh, I'm sorry. In fact, 'Wgo.js Theme' also has a problem and I fixed it. Please check with the attached styles.css file.
[styles.zip](https://github.com/SabakiHQ/Sabaki/files/2327476/styles.zip)

**Comment by yishn** [comment]
You fixed it, that's great! Why don't you contact the theme author to submit your fix?
