### ISSUE TITLE
(Continue the #441 issue) Randomization of black stones problem

### ISSUE THREAD

**Issue by gheemuse** [SabakiHQ/Sabaki#442]
I fixed only the problem of the theme, not the problem of Sabaki itself. Sabaki still has the black stone randomization problem. It displays it's default theme black stones. Please check with the theme and the style file I've attached.

**Comment by yishn** [comment]
This is a problem of the theme itself, not of Sabaki. Please contact the theme author for a fix. For future reference, please don't open new issues for continuations for simplicity's sake. Just comment in #441; even though it's closed I can see someone posting.

**Comment by gheemuse** [comment]
Why do you think Sabaki has no problem? The problem of the the theme was fixed by me and I attached the fixed file. Or try checkig with a new theme. I've just checked the problem again with a new theme and Sabaki still displays it's default black stones a lot.

**Comment by yishn** [comment]
The problem is, that you have to specify the background images for all the classes `.random_0`, ..., `.random_4`. Otherwise those positions with classes that you didn't define, will have the default stone image assigned.

**Comment by gheemuse** [comment]
You mean, at least five images are needed for stone randomization?
Oh, I understand. 5 is the fixed number for stone randomization, right? It's very likely to let us make mistakes.
I think it's possible not to fix the number of cases . For example, set the cases number to100 and if only three images are assinged, assign automatically stone0.png to random_3, stone1.png to random_4, ...
Anyway, thank you for your answer.

**Comment by yishn** [comment]
> I think it's possible not to fix the number of cases . For example, set the cases number to100 and if only three images are assinged, assign automatically stone0.png to random_3, stone1.png to random_4, ...

To know how many stone images are assigned, we need to parse the CSS beforehand. I don't want to do that because it's blocking the loading of the theme. Themes are just additional CSS on top of Sabaki, nothing more and nothing less; introducing such a behavior would be unpredictable. I think we would just have to live with this "limitation".

**Comment by gheemuse** [comment]
I understand.
Maybe that's not a serious problem. We can't use more than five numbers of cases but if we want to randomize using only two black stone images, we can achive that by just copying the images into five all together.

**Comment by gheemuse** [comment]
And I'm sorry for having disturbed you. I'll contact the theme author to submit my fix.
