### ISSUE TITLE
What are the keyboard shortcuts?

### ISSUE THREAD

**Issue by ChuckRBell** [SabakiHQ/Sabaki#444]
I've been bit by this twice now. There is a "View > Menu Bar" toggle where if you click it, it turns off the menu bar and how to turn it back on again is not obvious. I've searched for a list of keyboard shortcuts and cannot find one that would tell me how to turn the Menu Bar back on so I can navigate. What is the control sequence of keys to turn it back on?  For that matter, there needs to be some documentation that can be found somewhere that lists what the various keyboard shortcuts are. Perhaps this could be documented in the Read.me file at least.

**Comment by yishn** [comment]
Tap <kbd>Alt</kdb> to show the menu bar. Sabaki already dispays a short warning notice when you hide the menu bar. For a list of all keyboard shortcuts you can consult the menu; the shortcuts are displayed on the right of each menu item.

**Comment by ChuckRBell** [comment]
Oh. Just <Alt>, Thank you. I think I tried every combination of <Ctrl>, <Ctrl-Alt>, <Ctrl-Shift> and could not figure it out. Yes, there is a short warning notice but if the user fails to see it, he is kinda stuck.
