### ISSUE TITLE
The theme dosn't work after build Latest commit 14661bc

### ISSUE THREAD

**Issue by jun63cn** [SabakiHQ/Sabaki#448]
![default](https://user-images.githubusercontent.com/30382868/46181986-b4298580-c2fb-11e8-815f-7f06db8ea9b6.jpg)

**Comment by yishn** [comment]
That's correct. Sabaki has changed the way it displays the board. More information will follow before the official release for theme authors. If you want to use themes, use the v0.35.1 tag.
