### ISSUE TITLE
Top file menu not working with touch input

### ISSUE THREAD

**Issue by bdrose** [SabakiHQ/Sabaki#449]
The top menu of Sabaki is not useable using only touch input on my Surface Pro (2017 version), this is the only program that has this behavior. It is possible to place stones and do anything in the main window, the problem is isolated to expanding the the menu from the top bar, they are inaccessible. It appears to register that the menu is being selected, but it does not expand it. Once it has been selected with a mouse click it opens the menu and can work with touch input.

**Comment by bdrose** [comment]
Additionally, this issue only happens when the Surface pen is used. If using touch only Sabaki works fine, but if the pen is used even one time the program must be closed and opened to get them to menu to respond to touch.

**Comment by yishn** [comment]
Can you reproduce this issue in other Electron apps, such as VS Code? Unfortunately this is an issue I have no control of.

**Comment by bdrose** [comment]
The same issue happens in VS Code.

**Comment by yishn** [comment]
Then please open an issue on Electron's repository. This may even be a Chrome bug.

**Comment by bdrose** [comment]
This is now resolved.
