### ISSUE TITLE
Theming in Sabaki v0.40.0

### ISSUE THREAD

**Issue by yishn** [SabakiHQ/Sabaki#458]
Dear theme creators,

as you probably know, themes that worked in previous versions of Sabaki will not be working in the next release v0.40.0 anymore. This is due to the fact that I rewrote the Goban component and published it in a separate repository, under the name [Shudan](https://github.com/SabakiHQ/Shudan), so other people may use the Goban component in their projects.

You can [read about how to style Shudan](https://github.com/SabakiHQ/Shudan/blob/master/docs/README.md#styling) (and thus how to theme Sabaki). I realize this change may be quite troublesome, but I hope this new way is more resilient and future-proof than the old method, so that a breakage of all the themes won't be happening any time soon.

I have removed all the old themes from the [theme directory](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/theme-directory.md). If you migrate your themes, you can resubmit them via pull request again. To make the migration easier, I have written a [simple script](https://github.com/SabakiHQ/theme-converter) that will transform any v0.3x theme CSS file into a v0.40 theme CSS file. It works for most cases, but unfortunately, it's not perfect.

I'm really excited for the new Sabaki v0.40 release that will be coming soon. It will include a lot of new features and bug fixes, the highlight, of course, being finally able to analyze games using the new [Leela Zero v0.16](https://github.com/gcp/leela-zero).

@fohristiwhirl @geovens @ParmuzinAlexander @bdrose @3kakakhel

**Comment by yishn** [comment]
With CSS you can do whatever theoretically, but I can't ensure future compatibility. It's best to specify a board foreground color (the grid lines will assume that color) and use the default grid lines.

**Comment by fohristiwhirl** [comment]
I was hoping to get the sort of shadowed effect that used to be common (I think default had it). I'll see what I can do...
