### ISSUE TITLE
Bug: Variations from Leelaz disappear after sometime

### ISSUE THREAD

**Issue by hadim** [SabakiHQ/Sabaki#463]
When enabling the analysis move with leelaz: `./leelaz -w best-network --gtp -t 8 -v 500` the colored variations are displayed on the Goban but then they disappear when the number of visits reaches its maximum (set with the `-v` option).

You probably didn't see it because you don't use the `-v` option.

**Comment by hadim** [comment]
(using 048348b616ead5194fbae6d7d796a67e0a44f804)

**Comment by yishn** [comment]
That's because Leela Zero is ending the response after maximum number of visits has been reached. On Sabaki's side, we'll stop showing the heatmap when the response ends to avoid synchronization issues. I'm not sure if this can be fixed.

**Comment by hadim** [comment]
Ok I understand. That's not super convenient (at least for me). When I use 100 or 500, it's so fast that the variations disapear before I had time to see them.

**Comment by hadim** [comment]
Would that be possible to keep the heatmap until the Goban state is modified?

**Comment by yishn** [comment]
Yes, of course, but then there's some kind of synchronization issue we need to solve: Let's say the user navigates to another position. Even though Sabaki tells Leela to stop and removes the heatmap, Leela may still (in the very last second) send in one line of analysis directive that lets Sabaki redraw the heatmap on a (now wrong) board.

**Comment by hadim** [comment]
You're a boss!
