### ISSUE TITLE
New Feature "Save winrate values and visualizes them in a graph"

### ISSUE THREAD

**Issue by bdrose** [SabakiHQ/Sabaki#466]
It is unclear how to use the new feature
"Save winrate values and visualizes them in a graph"
I tried finding out how to do this by poking around 0.40.0 and could not find anything.

Also, with LeelaSabaki going away, is there a way to display the heatmap in Sabaki?

**Comment by yishn** [comment]
Yes, to have winrate values or show heatmap, you have to attach an engine that understands the `analyze` GTP command. Currently, only Leela Zero v0.16 supports it. After attaching, you can toggle analysis by pressing <kbd>F4</kbd> or clicking 'Engines' > 'Toggle Analysis' in the menu.

**Comment by yishn** [comment]
It seems that by limiting playouts to 2, Leela Zero is not able to respond properly to the analyze command.

**Comment by yishn** [comment]
I suggest to open an issue on Leela Zero's repository. Then, on Sabaki's side, we would have to find a way to fix #463.

**Comment by lz-google** [comment]
@yishn Hi, is this issue resolved or not? At least, I didn't found a way to "visualize winrate as graph" feature using latest sabaki and leelazero 0.16.  What is more, I also don't know what is "hotspot",  how to use guess mode and what does "find move" mean? There is no help documentation, and all these new feature is not intuitive at all after I click those menus. It will be very helpful to have some doc with illustrations on these new features. Thank you very much.

**Comment by yishn** [comment]
Well, #463 is closed, but Leela Zero still doesn't return anything when you limit playouts or visits to a small number. If you don't limit playouts or visits and give Leela a fair amount of thinking time, analysis data will come through including winrate. That is not a Sabaki issue.

SGF spec describes hotspot as:

> Node is a 'hotspot', i.e. something interesting (e.g. node contains a game-deciding move). [...] The property is not related to any specific place		on the board, but marks the whole node instead.		Sophisticated applications could implement the navigation		command next/previous hotspot.

Sabaki provides shortcuts to navigate between hotspots. You can also use them to 'bookmark' certain nodes.

Guess mode is fairly straight-forward: Click on the board where you think the next move will be. If you guessed correctly, Sabaki will go on to the next move. If it's not, some vertices will be grayed out indicating that the next move is not within the grayed out ones, and you can keep guessing.

Using find mode you can click on the board to find the node where a player as made a move on that vertex. Or you can search for a text that appears in the comments.

**Comment by yishn** [comment]
Oh, good point; the winrate graph is in the sidebar, so you have to have either game tree or the comment section visible to see the winrate graph.

**Comment by lz-google** [comment]
@yishn Thank you so much for explanation of guess mode, find and hotspot.  I previously thought guess mode is used in playing mode, so it doesn't work.  By the way, I still can't see winrate graph in sidebar with comment and game tree open

**Comment by yishn** [comment]
That’s curious; can you give us your full Leela Zero configuration? And maybe copy the log from the GTP console when you play against LZ.
