### ISSUE TITLE
missing board line in sabaki 0.40

### ISSUE THREAD

**Issue by zliu1022** [SabakiHQ/Sabaki#469]
Thanks for the great job of sabaki 0.40. The dynamic analysis  is wonderful and very very cool.
But in my mac book pro (macOS Mojave 10.14) the board line is missing.
Would you like take a look and help me to fix it?
![image](https://user-images.githubusercontent.com/3665494/47971163-bf758b00-e0c9-11e8-8a17-02f303b6bf16.png)

Thank you.

**Comment by yishn** [comment]
That is really weird behavior... All the lines should be exactly 1 pixel thick. Unfortunately, I don't have Mojave to test this on. I've improved board rendering on the master branch; can you [build Sabaki](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/building-tests.md) and test if this issue persists?

**Comment by zliu1022** [comment]
Hi, After I try more theme, I can give you more information first.

Default theme, no line:
![image](https://user-images.githubusercontent.com/3665494/47996160-9210f780-e132-11e8-9002-95ef3c5d6e54.png)

Wood theme, it's ok
![image](https://user-images.githubusercontent.com/3665494/47996180-a523c780-e132-11e8-8a56-36dd8b37d768.png)

Catoon theme, it's ok
![image](https://user-images.githubusercontent.com/3665494/47996230-cdabc180-e132-11e8-8fa0-49d268b6a9b4.png)

Photorealistic theme, no line
![image](https://user-images.githubusercontent.com/3665494/47996254-e1efbe80-e132-11e8-9084-8fd8555e1195.png)

Can you find something exactly?
If you still want me to recompile, I will try.

**Comment by yishn** [comment]
The wood (and cartoon) theme uses 2px lines all over. If you look closely, there are irregularities; some lines are only 1px thick. I don't thik this is intended. If you are able to build Sabaki on Mojave, please test it out.

**Comment by yishn** [comment]
@pcengine If you are able to [build Sabaki](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/building-tests.md) on Windows 7, please also try to build the master branch and see if this problem still persists.

**Comment by yishn** [comment]
Does resizing the window (by 1px, 2px) change the visibility of lines?

**Comment by zliu1022** [comment]
> Does resizing the window (by 1px, 2px) change the visibility of lines?

I think this can work , but only occasionally. I see some times all lines appears
By the way , the version you ask me to build has same issue. I hide the gtp console window , so it's a little easy to resize the window to get all lines appearing.
![image](https://user-images.githubusercontent.com/3665494/47999086-6135c000-e13c-11e8-939a-724599f1ae1b.png)

![image](https://user-images.githubusercontent.com/3665494/47999108-7874ad80-e13c-11e8-9711-456718908caa.png)

**Comment by yishn** [comment]
Hm... that's not the news I was hoping for. The master version should fix all sort of board rendering problems that can be solved through window resizing.

**Comment by zliu1022** [comment]
And I found if I hide gtp console window, then full screen , all line will appear.
![image](https://user-images.githubusercontent.com/3665494/47999705-5d0aa200-e13e-11e8-8230-2260bde4c139.png)

**Comment by geovens** [comment]
On two of my computers (both Window 10 x64):
when the system DPI setting is at 100%, the lines show fine;
when the system DPI setting is above 100%, the lines are irregular.
Same behaviour on release version or the current master version.

**Comment by yishn** [comment]
@geovens Just for clarification: Do you mean lines disappear completely, or do you mean, lines have different thickness? The latter is to be expected, but the former shouldn't happen.

**Comment by geovens** [comment]
The latter (different thickness but never disappear). For both version of Sabaki.

**Comment by fohristiwhirl** [comment]
I run Windows 8 with 125% general size (i.e. all content is made a bit larger) and also get some lines 1px, some lines 2px; which changes depending on the exact sizing of the board.

There seems to be some specific Chrome (and thus Electron) issue regarding this (e.g. [here](https://github.com/electron/electron/issues/9417)).

I can compensate by making the "app.zoom_factor" setting be 0.8 (which is 1 / 1.25) but this has the downside that opening and closing side windows (e.g. GTP console or game tree) causes the board to resize.

**Comment by xsaxy** [comment]
I have also encountered this problem, the solution is to delete the original configuration file.
(Window 7 x64 deletes all files in AppData\Roaming\Sabaki, leaving only configuration reconfiguration in settings.json)
It’s completely normal to run again, I don’t know if it can help, and it’s for reference only.

**Comment by ParmuzinAlexander** [comment]
Zoom Ctrl+Shift+= Ctrl+- Ctrl+0 doesn't fix it?
