### ISSUE TITLE
GTP console info can not auto scroll when 2 engine autoplay (0.40)

### ISSUE THREAD

**Issue by HenryHo2006** [SabakiHQ/Sabaki#470]

**Comment by HenryHo2006** [comment]
![image](https://user-images.githubusercontent.com/14534015/47976028-7a625080-e0eb-11e8-9db0-f26a184a9aa3.png)

**Comment by yishn** [comment]
Please make sure the console is scrolled to bottom before starting the game to enable autoscrolling.
