### ISSUE TITLE
Leela getting out of sync with the board; Synchronize not helping

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#471]
Reproduction:

* Set Preferences:
    * Start game right after attaching : OFF
    * Automatically generate engine moves : OFF
* Attach Leela Zero
* Toggle Analysis (to ON)
* Play a few sensible moves
* Suspend
* Toggle Analysis (to OFF)
* Toggle Analysis (to ON)

The analysis will now ignore the stones on the board. Clicking "Synchronize" doesn't help.

![untitled](https://user-images.githubusercontent.com/16438795/48033248-7fa6b600-e152-11e8-9e29-4f873b99bdb1.jpg)

**Comment by yishn** [comment]
Right, suspending an engine doesn't clear engine state in EngineSyncer. Forgot about that. 😓
