### ISSUE TITLE
Occasional analysis glitch

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#472]
(I'm now running on the latest code as of 20 minutes ago, but I've been seeing this all along.)

Do you ever get this?

![glitch](https://user-images.githubusercontent.com/16438795/48225301-4c536980-e394-11e8-983d-1cf9cbdc82d6.png)

**Comment by yishn** [comment]
My guess is the GPU is so busy with Go that it glitches out. 😅

**Comment by fohristiwhirl** [comment]
I was wondering if this was something you've seen yourself or if it's peculiar to me?

**Comment by yishn** [comment]
Yes, I see it sometimes as well. It glitched even more when heatmap CSS animation was on, which led me believe that this might be some GPU thing. The old Sabaki heatmap didn't glitch; I guess since it was stationary.

**Comment by vascopimenta** [comment]
I'm seeing the same thing on Sabaki 0.41.0, mac OS 10.14.2, on a Macbook (without dedicated GPU).

**Comment by yishn** [comment]
I'm closing this issue since I don't experience it anymore on master. If this is still an issue for you, please comment and I'll reopen.
