### ISSUE TITLE
How can I show prompts consistently?

### ISSUE THREAD

**Issue by Linuxwell** [SabakiHQ/Sabaki#474]
Hello, thank you for writing Sabaki, an excellent program.
I used Sabaki(0.40.1)+Leela Zero+leelasabaki-macos for my Mac.The program is running very well.But I have a few questions to ask:
1. I have added the "--heatmap" parameter. Why can't I display a red prompt area like before?
2, Like the figure 2, I have to manually call out "Toggle Analysis" every time, how can I make such a prompt automatically appear in every step?
3. What is the difference between the hint colors in figure 2?
Thank you very much!

<img width="1304" alt="1" src="https://user-images.githubusercontent.com/44936326/48308987-bcd3d380-e5aa-11e8-80bd-b366684b973b.png">
<img width="1304" alt="3" src="https://user-images.githubusercontent.com/44936326/48308988-bcd3d380-e5aa-11e8-8784-bec08ff82596.png">

**Comment by yishn** [comment]
LeelaSabaki does not work anymore in v0.40. You have to use 'Toggle Analysis' instead. If analysis is on, playing a move/generating a move will keep you in analysis mode.

The colours symbolize how good a move is, combining winrate and number of visits data from Leela Zero. Very good moves are green, good moves are blue, bad moves are purple, very bad moves are red.
