### ISSUE TITLE
Now,can I add engine in web vision?

### ISSUE THREAD

**Issue by hedy14** [SabakiHQ/Sabaki#477]
I see issues that somebody want to add engines in web version but failed in june. I start to learn js recently, so I have no idea what to do. Now can I have any way to make it? Thanks a lot.

**Comment by yishn** [comment]
No, it's not possible. Websites can't execute system processes; that would be a huge problem security-wise.

**Comment by hedy14** [comment]
Thanks, can I define some engines(include their path) in the code in advance? I just select engine when I played, so I can play with AI by web version? By this way, I don't need execute system processes. Maybe that would not be a security problem.

**Comment by yishn** [comment]
All engines are executable files that run on your computer. They'd have to be started, as a process on your system.

**Comment by hedy14** [comment]
Thanks again for your answer. I have another idea of putting some socket communicating javascript codes in sabaki-web project to attach my AI engines. Do you think this will work?

**Comment by yishn** [comment]
This sounds very vague, so I can't say anything about it. Why don't you try it out?

**Comment by beartung** [comment]
How about make a http server to proxy GTP to real GTP engines?  If possible, web version could run on an iPad while http server and gtp engine run on a PC/Mac.
