### ISSUE TITLE
How can I get the Win Rate Histogram Data?

### ISSUE THREAD

**Issue by CamusLee** [SabakiHQ/Sabaki#479]
Not Issue :)

When I use an Engine to analysis a history game, I found a Win-Rate histogram chart is at top of the Game Tree. It's a very useful function for me.

Can I get the original data of this chart? Or how can I get or export the data from somewhere?

I want to get the original win-rate data for each move so that I can do many many useful analysis.

Many thanks.

**Comment by yishn** [comment]
The data is saved in the SGF file. Each node has the extra property SBKV which contains the winrate of black.

**Comment by CamusLee** [comment]
@yishn 
Hi yishn, I found the extra property SBKV, thank you.

But I'm not sure which move the winrate is related. 

The below 4 lines are part of a .sgf file:
>   ;B[hq]SBKV[45.81]
>   ;W[dd]SBKV[45.71]
>   ;B[dc]SBKV[45.61]
>   ;W[ce]SBKV[45.64]

Would you please tell me which move B[dc] or W[ce] the winrate 45.61 is for ? 
Many thanks again.

**Comment by yishn** [comment]
45.61 refers to B[dc], that means black has 45.61% winrate. 45.64 refers to W[ce], which means white has 54.36% winrate.
