### ISSUE TITLE
me ,too ,I want to add Preferences' drawer to Sabaki-web?but failed!,I remove the replacement alias in the webpack config. but error !

### ISSUE THREAD

**Issue by yanxuejungit** [SabakiHQ/Sabaki#481]
ERROR in ./src/components/drawers/PreferencesDrawer.js
Module not found: Error: Can't resolve 'uuid/v1' in 'E:\Sabaki-web\src\components\drawers'
 @ ./src/components/drawers/PreferencesDrawer.js 285:19-37
 @ ./src/components/DrawerManager.js
 @ ./src/components/App.js

**Comment by yishn** [comment]
Duplicate of #397
