### ISSUE TITLE
I have added Leela Zero as engine, but how do I get it to analyze sgf?

### ISSUE THREAD

**Issue by AlvinNg89** [SabakiHQ/Sabaki#484]
Hello, non-programmer here. I managed to add Leela Zero as an engine (by following instructions in this video: https://www.youtube.com/watch?v=FV6dSjnx7jY) and i can play against it. 

Lets say I uploaded an sgf and want to use Leela to analyze it instead, how do i do it? I tried to press F4 but it keep sayings "You haven't attached any engine that supports analysis". 

Did i missed out on doing anything?

Many thanks in advance!

**Comment by yishn** [comment]
Follow the following steps:

- Open an SGF file
- Open game info drawer (e.g. by pressing <kbd>Ctrl+I</kbd>)
- Attach Leela Zero to either player
- Toggle analysis (e.g. by pressing <kbd>F4</kbd>)
