### ISSUE TITLE
Twice actions but press the Up/Down key once [MacOS]

### ISSUE THREAD

**Issue by CamusLee** [SabakiHQ/Sabaki#485]
I like to navigate the game tree by the Up/Down key because it's more correct than by mouse.

Sometimes, when I press the Down key once, the game is navigated to two moves.
For example,
Current move number is 5, when I press the Down key one time, the game will be navigated to 7. And at same time, I press the Up key once to go back up to the previous move(6), the game will be navigated back to 5, not 6. At this time, I have to be more careful to press the Up/Down key quickly, so that the game can be correctly navigated to move 6. 
The pressure on Up/Down keys to move number 5 is NOT different from before.

I don't know why.

**Comment by CamusLee** [comment]
Could you please tell me where settings.json is? I'm using MacOS.

**Comment by yishn** [comment]
Please follow [this guide](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/debugging.md).

**Comment by Phelanpt** [comment]
I've tried t

> 
> 
> You can adjust the `autoscroll.max_interval` key in `settings.json`. Maybe increase it to `400`ms? You can try playing with it and maybe we can adjust the setting for all users.

I've tried this and it seems to work, it's probably just keyboard being too sensitive. Thanks! :) 
(I'm not the OP, but I was having the same issue of moving twice through the game tree ocasionally)

**Comment by Phelanpt** [comment]
I tested 300 ms, and while I'm not sure it still has the same issue with moving twice, it seemed worse than 400 ms. Hope this helps :)
