### ISSUE TITLE
Documentation for "Analysis mode"? Cannot understand it...

### ISSUE THREAD

**Issue by jokkebk** [SabakiHQ/Sabaki#486]
Hi!

Newest version of Sabaki has a nice "Analysis mode" that shows winrates and variations, very nice. There seems to be occasional glitch in where two diagonal green tiles caused a solid green squares to appear instead of nice "glows", however..

I don't find any documentation on how to use this analysis mode. I open up an SGF file (or create one by hand), and select "Toggle analysis mode" and it says no supporting engines attached. Fair enough, I attach a couple of Leela instances (not having a need for a separate one for B and W would be nice future addition)... AND IT STARTS PLAYING. Well, I can stop that with ESC, so I only get one move generated. I can now move around in SGF, but if I want to try alternate move, IT STARTS PLAYING AGAIN. 

Well I can end that generation with ESC, but having a 25s time setting for the engine takes quite a while. I loaded up Leela instances with 500 visits, which is faster, but now it stops after those 500 visits. What I really would like would be a Lizzie type of action that runs Leela until I stop it (or for example until 100 000 visits) or play a move, after which it starts analyzing (not playing) again, allowing me to explore variations. At the current form it is nice, but seems that the user interaction isn't fully thought through.

Or maybe it is, but if so, it's not documented anywhere. This was the only piece of evidence found in documentation (i.e. Readme.md):

> Board analysis with engines which support it

PS. Superb work with Sabaki, I love it already, and use it a lot, thanks for all contributors and sorry for not being able to chime in with more than issues at the moment 😅

**Comment by yishn** [comment]
You can disable auto move generation in Preferences. That would me more like Lizzie.

**Comment by yishn** [comment]
You can disable auto move generation in Preferences. That would make  Sabaki more like Lizzie.

**Comment by agugglez** [comment]
Exactly what I was looking for @yishn, thanks
