### ISSUE TITLE
How can I get the console log that leela returned after genmove command?

### ISSUE THREAD

**Issue by xiarx2016** [SabakiHQ/Sabaki#495]
Dear yishn , when AI run a "genmove" command , how can I get all the GTP console information ?
I try to use the response after the code ： " let response = await getResponse() ” in handleCommandSent function, but I only get a vertex .
I want to get the other information that show in the GTP console drawer .
Thank you !

**Comment by yishn** [comment]
In the [`handleCommandSent` function in `App.js`](https://github.com/SabakiHQ/Sabaki/blob/master/src/components/App.js#L2109), every command that is sent to an engine and their responses are captured there. If you want to capture `stderr` lines, use the [`stderr` event on `syncer.controller`](https://github.com/SabakiHQ/Sabaki/blob/master/src/components/App.js#L2067).
