### ISSUE TITLE
How to send message from windows exe to sabaki?

### ISSUE THREAD

**Issue by hedy14** [SabakiHQ/Sabaki#497]
I'm using windows version sabaki to play with my local C++ engine. My engine work fine with foxGTP but had some problem with sabaki. I think the problem is that sabaki cannot receive any message from my engine. Here is my code.
 **My Question is How can I send message from my windows exe to sabaki? I tried cout, printf and fprintf(stfout), they all don't work.**
*This is a fake engine (simply play besides opponent's last move).*
```
#include <iostream>
#include <fstream>
#include <cstdio>
#include <stdio.h>
#include <string>
#include <cstring>
#include <assert.h>
using namespace std;

int main()
{
	std::cout.setf(std::ios::unitbuf);
	std::cerr.setf(std::ios::unitbuf);
	std::cin.setf(std::ios::unitbuf);
	setbuf(stdout, nullptr);
	setbuf(stderr, nullptr);
	setbuf(stdin, nullptr);
	while(1) {
		string message;
		getline(cin, message,'\n');
		ofstream fout("D:\\a.txt", ios::out | ios::app);
		assert(fout.is_open());
		if (message == "name") { 
			cout << "phgo" << endl; 
			fprintf(stdout, "phgo\n"); 
		}else if (message == "version") { 
			cout << "1.0" << endl;
			fprintf(stdout, "1.0\n");
		}else if (message == "protocol_version") { 
			fprintf(stdout, "2\n");
			cout << "2" << endl; 
		}else if (message == "list_commands") {
			fprintf(stdout, "name\nversion\n \
				protocol_version\nlist_commands\nquit\nclear_board\nboardsize\nkomi\ntime_set \
				tings\ntime_left\nplace_free_handicap\nset_free_handicap\nplay\ngenmove\nfina \
				l_score\nget_debug_info\nget_last_move_debug_info\n");
			cout << "name\nversion\n \
				protocol_version\nlist_commands\nquit\nclear_board\nboardsize\nkomi\ntime_set \
				tings\ntime_left\nplace_free_handicap\nset_free_handicap\nplay\ngenmove\nfina \
				l_score\nget_debug_info\nget_last_move_debug_info" << endl; 
		}else if (message == "komi 7.5") { 
			fprintf(stdout, "7.5\n");
			cout << "7.5" << endl; 
		} else {
			if (message[2] == NULL) {
			        message[1]= message[1] + 1; // Fake engine policy
			}
			else {
				message[2] = message[2] + 1; // Fake engine policy
			}
		}
		cout << message << endl;
		fout << message << '/n' << endl;
		fprintf(stdout, "%s\n", message.c_str());
		fout.close();
	};
}
```
When I choose my engine as white player and click "OK", my engine received following messages:
>name
>version
>protocol_version
>list_commands

Then I play a black move, my engine received following messages:
>komi 7.5

My engine didn't receive the black move command. Sabaki didn't receive any message and begin waiting message.

That's all. Sincere thanks

**Comment by yishn** [comment]
I think you may have gotten the GTP wrong. GTP responses need to start either with a `=` or a `?`. Look at the [GTP specification](http://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html), especially the section with [how to form proper responses](http://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION00044000000000000000).

**Comment by hedy14** [comment]
Thanks for your advice, I will look at the GTP specification for help and try.

**Comment by AlexWu20061107** [comment]
Where can I download FoxGTP?
