### ISSUE TITLE
Hang on engine 'pass'

### ISSUE THREAD

**Issue by dbosst** [SabakiHQ/Sabaki#498]
The analysis parsing for the engine hangs the engine when the last move is a 'pass' in pv -- so you have to detach/reattach the engine. This results in data in the chain having a null value when executing .map causing an Error.

The analysis parsing doesn't seem to handle pass at all, so it also seems any variation with a 'pass' in it will result in an erroneous variation (specifically, the current regex will pick up moves after the last pass). All the variations are x,y integer coords so I don't even know if/how pass is handled to fix it.

Temporarily to stop Sabaki from hanging with the engine I have filtered out pvs that are null in App.js:
`.filter(pv => pv != null)`
`.filter(({move}) => move.match(/^[A-Za-z]\d+$/))`

**Comment by yishn** [comment]
Thanks for the debugging! Could you please send in a pull request to fix this issue?

**Comment by Splee99** [comment]
So when can we get a release with this issue fixed? Now the Leela zero new weight really likes to add pass move, a fix is needed ASAP. Thank you so much.

**Comment by yishn** [comment]
I'm hoping to get #508 merged first, but right now I'm busy working on something else get published, so you just have to be patient. Alternatively you can build Sabaki from source yourself.
