### ISSUE TITLE
Area scoring & handicap stones

### ISSUE THREAD

**Issue by dbosst** [SabakiHQ/Sabaki#499]
Sabaki doesn't include handicap stones at all in the calculation for the Area Score.

Area scoring for handicap games involves adding the number of handicap stones to the white score (this follows Chinese area scoring rules) -- for example, [leela-zero does it this way.](https://github.com/gcp/leela-zero/blob/5958e02cf539d42ee20704b664043036d5c3c18b/src/FastState.cpp#L151)

If you are playing an engine with a close handicap game, this can result in a completely different outcome and you won't even realize it, since Sabaki doesn't bother checking with the engine at all using final_score.

**Comment by yishn** [comment]
Closed with #501
