### ISSUE TITLE
Why set dirty to true?

### ISSUE THREAD

**Issue by WingGao** [SabakiHQ/Sabaki#509]
https://github.com/SabakiHQ/Sabaki/blob/15dcc7a779d23ac208fd74f976474628eac64001/src/modules/enginesyncer.js#L155-L162

Is this a bug?

**Comment by yishn** [comment]
Why do you think this is a bug?

We set `dirty` to true when `enginesyncer` loses track of the engine state, forcing a `clear_board` command and a replay from the very beginning. [According to the GTP documentation](https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION00073200000000000000):

> In GTP version 1 [`boardsize`] also did the work of `clear_board`. This may or may not be true for implementations of GTP version 2. Thus the controller must call `clear_board` explicitly. Even if the new board size is the same as the old one, the board configuration becomes arbitrary.

We also set it here:

https://github.com/SabakiHQ/Sabaki/blob/15dcc7a779d23ac208fd74f976474628eac64001/src/modules/enginesyncer.js#L78-L80

**Comment by WingGao** [comment]
Thanks for your reply.
I understand these codes.
