### ISSUE TITLE
Game tree annotation feature request

### ISSUE THREAD

**Issue by MacroUniverse** [SabakiHQ/Sabaki#510]
It will be awesome if Sabaki can allow color mark and comment/annotation for the nodes in the game tree.
![234](https://user-images.githubusercontent.com/33382811/50986591-dc18af80-14cc-11e9-8540-163154e735ae.png)

**Comment by yishn** [comment]
There are two ways to annotate nodes:

**First method:**

- Navigate to the node you want to annotate
- Enter edit mode (<kbd>Ctrl+E</kbd> or click on pencil button in the comment box)
- Click on the down arrow button
- Select annotation

**Second method:**

- Navigate to the node you want to annotate
- Inspect board to find stone that is marked with a disc in the middle
- Right click on that stone
- Select annotation

**Comment by MacroUniverse** [comment]
Thank you so much. Sorry for taking you time.
