### ISSUE TITLE
Sabaki's colour scheme of leela-zero's win% 

### ISSUE THREAD

**Issue by gogre** [SabakiHQ/Sabaki#512]
Sabaki's colour scheme for Lz's win% is bright, but maybe could be more beautiful, as suggested at 03:28 in https://www.youtube.com/watch?v=OfL5XSrYuLo&feature=youtu.be

**Request:** bot programmers might want to know the exact numbers of win% and node visits, but to Joe Blower players like me who only want help from Lz, they just get in the way.  

Colours alone are enough, provided they are on a semiotic graduated colour scheme, such as:
> 80+% = yellow like the Sun
55-79% = green like the grass
45 - 54% = brown like the dirt
< 45% = red like blood

i suppose, if you wanted more precision, you could add intermediate colours such as 
greenish-brown = 55-64% 
and extremes such as:
<<45% = orange like Trump's boatrace

Then us average Joes can get the point at a glance, and focus on Lz's opinions instead of the extraneous little numbers in them, and won't have to remember whether purple is better than blue

**Comment by yishn** [comment]
Unfortunately, I have trouble to understand what the person is saying in the video. Here are some things I considered when picking the colors:

- No yellow or brown hues since they will be practically indistinguishable from the board
- Easy to understand, full-saturated colors that come in order of the [color wheel](https://en.wikipedia.org/wiki/Color_wheel). Purple moves are worse than blue since it's closer to red than green. (With your color scheme, you'd have to remember that yellow is better than green)
- These colors should correspond to SGF move annotations (good move, interesting move, doubtful move, bad move)
- Colors are not only based on win rate, but also on visit number, since these are the moves that Leela investigates the most and chooses in the end.
- We're operating on a relative scale, i.e. if you only have moves with a win rate between 5% - 10% (let's disregard visits for the moment) available, the best move with 10% win rate will be colored green since it's the best. In your color scale, they would all be colored red.
- The radius of the gradient depend on how good a move is as well. Better moves have bigger gradients, so you can even distinguish between moves that have the same color, without reading the numbers, if you pay enough attention.
- A lot of people want actual numbers in their analysis, and the numbers also help people who have trouble distinguishing the colors. 

I do believe that the color system right now is superior than your suggestion. If you don't want to read the numbers, you can just ignore them.

**Comment by gogre** [comment]
thank you for your thoughtful and comprehensive reply.  i understand
and appreciate your rationale for the colour scheme and size of
colours.  i think the underlying significance of the color wheel is
the colour's light frequency, so there is a mathematical relationship
between one colour and its neighbour in the wheel.

However, and this may not be by accident, but a product of evolution
which perhaps enables Man to easily discriminate between objects (or
parts of objects such as ears on a deer) of closely similar colour
frequencies, human perception of the meaning of colour may operate on
a totally different scale, one more associated with the way the colour
of, say, steel, changes with temperature.  i have often thought that
weather maps would be more intuitive if the mappers used a
"psychological colour" scale for such things as temperature and
humidity.

Since a picture says a thousand words, i have attempted to explain
what i mean by way of a picture, which is posted to the link below as
GitHub doesn't have a facility for putting pictures in messages.
https://www.lifein19x19.com/viewtopic.php?f=18&t=16345&p=240791#p240791

my artistic skills are pretty well non-existent, but i hope my picture
paints the picture i have in mind sufficiently for it to be legible.
But it is not completely self-explanatory, so here is the necessary
corroborative detail:

there is one colour graduation scale, which maps onto two different
logarithmic axes:
win% and d/dt(win%), where the latter is the difference between the
player's win% after her previous move (before the opponent's last
move).  So d/dt tells you whether a move is going uphill or downhill.

You will note that the brownish-olive colour used for "close to 50%"
is neutral, but sufficiently different from the background board
colour that it is easily seen.

i would guess that the higher the rank of the players, the greater the
significance of even a small swing, so i have rethought my colour
graduation scale; this new one uses olive as the colour of "no
significant change".

for win%, i arbitrarily chose 48-52% as meaning a close game; any
numbers high or lower than that meaning the game is definitely in the
favour of one side or the orther.

for delta(win%), ie d/dt(win%), i figure a small change makes a big
difference, so its axis is more stretched-out than win%.

Each Lz-proposed move for black is indicated by two coloured rings:
the inner ring colours win% and the outer ring colours delta(win%).  i
chose this arrangement because i figured that delta(win) is a harmonic
upon win.  So delta% tells you whether your move is (would be)
relatively good or bad, and win% tells you whether you are (would be)
ahead.

In the example, white has defended her right side and black has sente.
The question Ishida addresses is "what should be black's focus of
attention?"

Lz proposes her top 7 alternative moves.

The raw numbers of win% are all very high, but as this is a handicap
game, i feel some adjustment to them is desirable.  Precisely what
that adjustment should be i cannot say, but i would guess that the
real-world chance of black winning with a 6-stone handicap is about
50%, the same as an even game with komi.

All Lz's numbers were about 98%, so i arbitrarily decided that a raw
black 98% in a 6-stone game means a real-world 50%.

All Lz's top moves are in the range 97.8 - 98%, so the 0.2% difference
is significant, but not so significant as to warrant a qualitative
colour judgement of "really bad" upon P7.

But it is nonetheless second-best, and that difference must be shown
somehow.  That's why i chose the idea of two coloured-rings.  My
picture may not be quite accurate,  i exaggerated the significance of
-0.2%, and it may be that delta(win%) should be even more
stretched-out.

With regard to sizing colour marks according to node visit count,
whilst i can see that this statistic is of great interest to bot
writers, may i suggest that it is irrelevant to a player who only
wants to know how good or bad Lz thinks a move is?

For people who are colour-blind, maybe a monochrome scale would be
better: say from bright white to dark grey, but not as dark as the
black stones.  As they are hollow rings, there shouldn't be any
confusion with existing stones.

PS as the author of the video (the GitHub name "jaca" had already been
taken), i am taking on board your comment that its voiceover was
unintelligible.  That is ironic, for i had selected a French accent in
your honour, thinking that you were from a French family.  As it is my
intention that the video be intelligible, i will remake it with a new
voiceover.

**Comment by ParmuzinAlexander** [comment]
@gogre You can customize the colors as you want.
https://imgur.com/GI565XM
`.shudan-vertex .shudan-heat {
top: 50%;
left: 50%;
margin-left: -1px;
margin-top: -1px;
border-radius: 50%;
width: 1px;
height: 1px;
opacity: 0;
pointer-events: none;
transition: opacity .5s, box-shadow .5s;}
.shudan-vertex.shudan-heat_9 .shudan-heat {
background: #009900;
box-shadow: 0 0 0 .5em #009900;
opacity: 1;}
.shudan-vertex.shudan-heat_8 .shudan-heat {
background: #1974d2;
box-shadow: 0 0 0 .5em #1974d2;
opacity: 1;}
.shudan-vertex.shudan-heat_7 .shudan-heat {
background: #1974d2;
box-shadow: 0 0 0 .5em #1974d2;
opacity: 1;}
.shudan-vertex.shudan-heat_6 .shudan-heat {
background: #1974d2;
box-shadow: 0 0 0 .5em #1974d2;
opacity: 1;}
.shudan-vertex.shudan-heat_5 .shudan-heat {
background: #1974d2;
box-shadow: 0 0 0 .5em #1974d2;
opacity: 1;}
.shudan-vertex.shudan-heat_4 .shudan-heat {
background: #1974d2;
box-shadow: 0 0 0 .5em #1974d2;
opacity: 1;}
.shudan-vertex.shudan-heat_3 .shudan-heat {
background: #1974d2;
box-shadow: 0 0 0 .5em #1974d2;
opacity: 1;}
.shudan-vertex.shudan-heat_2 .shudan-heat {
background: #1974d2;
box-shadow: 0 0 0 .5em #1974d2;
opacity: 1;}
.shudan-vertex.shudan-heat_1 .shudan-heat {
background: #e32636;
box-shadow: 0 0 0 .5em #e32636;
opacity: 1;}
.shudan-vertex .shudan-heatlabel {
display: inline-block;
height: auto;
top: 50%;
left: 50%;
overflow: hidden;
color: white;
font-size: .36em;
line-height: 1.26;
text-align: center;
text-overflow: ellipsis;
text-shadow: none;
white-space: pre;
opacity: 1;
transform: translate(-50%, -50%);
pointer-events: none;}`

**Comment by yishn** [comment]
@gogre Your double circle visualization is too convoluted and complicated for my tastes. If you're interested in winrate diffs, I'd suggest you look at the winrate graph in the top right corner when you have the right sidebar open. 

Since an engine won't make moves on spots where there are stones already, I don't see any reason why analysis would be on top of already placed stones.

**Comment by yishn** [comment]
I guess there's always a compromise between cleanliness/simplicity and amount of information that we can show. In my opinion, Sabaki's visualization strikes a good balance, and it's what I personally find most useful.

BTW, Sabaki comes with its own influence map heuristic, which you can visualize by clicking on 'Play' > 'Estimate' in the menu, or on 'Estimate' in the hamburger button.

**Comment by gogre** [comment]
@Parmuzin as this is a closed thread, your suggestion is unlikely to
be seen by anyone else.  if you want anyone else to think about your
question, you can raise it as a New Issue, or as a discussion topic
in, eg, Life in 19x19 site.

node visit count could impact win% estimate, but not necessarily.

for example, people with fixed opinions don't change them, no matter
how many times they revisit the subject.

Lz is more objective, but there is an example in my video of her
visiting a node 17 times and still thinking that putting herself in
atari is a good idea :)
https://www.youtube.com/watch?v=OfL5XSrYuLo&feature=youtu.be
