### ISSUE TITLE
Sabaki's influence map

### ISSUE THREAD

**Issue by gogre** [SabakiHQ/Sabaki#513]
@Sabaki I guess there's always a compromise between cleanliness/simplicity and amount of information that we can show. 

Sabaki, comes with its own influence map heuristic, which you can visualize by clicking on 'Play' > 'Estimate' in the menu, or on 'Estimate' in the hamburger button.

_Originally posted by @yishn in https://github.com/SabakiHQ/Sabaki/issues/512#issuecomment-456029091_

**Comment by yishn** [comment]
I'm closing this because... there's no issue here?
