### ISSUE TITLE
trouble at mill

### ISSUE THREAD

**Issue by gogre** [SabakiHQ/Sabaki#522]
Sabaki used to work for me under Fedora, but after a change of os to Debian 9, now Sabaki places stones manually ok, but it's not making LZ moves, just apparently thinking forever with the spinning wheel cursor turning happily and nothing else happening.  

in desperation, i reduced every parameter i could think of and still no result.  pressing F4 produces: "You haven't attached any engines that supports analysis.  ... ok" which is very much not ok!

yet leelaz runs just fine from the command line, as you can see. and it runs with lizzie too.

what have i got wrong?

![troublesabaki](https://user-images.githubusercontent.com/46689669/52685530-c4ce5580-2f95-11e9-9055-a559e0ae4328.png)

**Comment by dbosst** [comment]
Could you enable GTP logging, (repeat the steps to give you the error), and post the log here?

**Comment by gogre** [comment]
re-run; log is same as before

[2019-02-14 05:40:53.133] W <Laizy>    (in) : name
[2019-02-14 05:40:53.140] W <Laizy>    (in) : version
[2019-02-14 05:40:53.143] W <Laizy>    (in) : protocol_version
[2019-02-14 05:40:53.145] W <Laizy>    (in) : list_commands
[2019-02-14 05:40:53.147] W <Laizy>    (in) : time_settings 1 1 1
[2019-02-14 05:40:53.149] W <Laizy>  (meta) : Engine Started
[2019-02-14 05:40:56.251] W <Laizy>    (in) : komi 7.5

i also followed the instructions in Debugging and saw this:

11
[Violation] Forced reflow while executing JavaScript took <N>ms
events.js:167 Uncaught Error: spawn /home/d/Documents/go/leela-zero/build/leelaz  ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229)
    at onErrorNT (internal/child_process.js:406)
    at process._tickCallback (internal/process/next_tick.js:63)

i've been moving files around a bit, tidying up my file structure - maybe i should rebuild leelaz in case somewhere there's a relative path that i've tripped up; i will do that anyway whilst you consider what could have caused the spawn error.

i get the same behaviour with both Sabaki41 and 42

i read this:
https://stackoverflow.com/questions/41218507/violation-long-running-javascript-task-took-xx-ms

but cant make head or tail of it!  it reads as if its something to do with browsers, but surely Sabaki doesn't use a browser, does it??

anyhow, environment is Debian 9, Gnome 3 something, Firefox

Debian installed OpenJDK and IcedTea JWS, but something else didnt like that - Lizzie i think it was - so i installed Oracle Java8, reset all the prefs and defaults i was told to set, and removed Iced Tea; then Lizzie was happy; Oracle's docs say its JWS comes with JRE

i've also shifted from Debian Mate back to Gnome because i couldnt find a way to launch .jars from Mate's panel, nor even from desktop unless i ran " run Application as Administrator", 

i am so happy to not be a programmer! :)

**Comment by dbosst** [comment]
The violation is just a warning I think you can ignore and is irrelevant 

`events.js:167 Uncaught Error: spawn /home/d/Documents/go/leela-zero/build/leelaz  ENOENT`

The real problem is it can't find the leelaz binary to spawn.  Are you sure the path is valid? From the error message it looks like there is an extra space or other character after 'leelaz'

**Comment by gogre** [comment]
"an extra space" - that's entirely possible, it's just the sort of thing i do!  

i rebuilt lz in a new subdirectory

Sabaki didnt seem to do anything, not even a circling yinyang, so i added a .gz to the lz weightsfile and reran - and everything worked!

i guess that's what you call a Debian and/or Gnome "feature" ...

you can mark this thread "solved" :)
