### ISSUE TITLE
Add shortcut key to Select Engine

### ISSUE THREAD

**Issue by CamusLee** [SabakiHQ/Sabaki#524]
Hi,
When I want to attach engine to analyse, I select the sub menu "Attach..." under "Engines" first.
I have to use mouse to click the "Down Arrow" button to select one engine for Black or White player.
Could you please add a shortcut key to open the select-engine menu, so that I can only use keyboard, without mouse?

Thank you.

**Comment by yishn** [comment]
We could add a submenu to the 'Attach' menu item under 'Engines' with two menu items: 'As Black' and 'As  White', both having a submenu with all the engines the user has defined.

**Comment by yishn** [comment]
I think this issue is outdated after the engines handling rewrite.
