### ISSUE TITLE
Zoom function

### ISSUE THREAD

**Issue by Naeit** [SabakiHQ/Sabaki#526]
Hi,

I recently downloaded Sabaki.
I was looking around the menues and found the zoom functions.
The Problem was that zooming in or out of the Board was not possible.
It just didn´t work.
What happens when I zoom is that the background changes.
Also only out/- and reset/0 work.
The +,-,0 on the NumPad don´t work for zooming at all. 

Images:

_Normal_
![zoom 0](https://user-images.githubusercontent.com/48308582/53981529-04aad780-4113-11e9-97f5-bcdf4c86ea7a.JPG)

_Zoomed out_
![zoom 1](https://user-images.githubusercontent.com/48308582/53981528-04aad780-4113-11e9-9ff4-a919b80e7aa7.JPG)

Specs:

Sabaki v0.42.0
Windows 10 Education

**Comment by yishn** [comment]
On Windows there's this Electron bug, that you need to press <kbd>Ctrl+Shift+Plus</kbd> to zoom in. I see that the second screenshot is at a zoomed out state. You can notice it by the smaller sidebar/bottom bar. Can you post a screenshot of a zoomed in state?

**Comment by Naeit** [comment]
Interesting...

here in the zoomed in state

![zoom 2](https://user-images.githubusercontent.com/48308582/53987950-a38b0000-4122-11e9-8651-65683fe0718c.JPG)

**Comment by yishn** [comment]
See? The sidebar and bottom bar are slightly bigger, so I don’t see any problems here.

**Comment by Naeit** [comment]
But it does not make sense to me why this function is named zoom.
I would call it window size or so... because zoom sounds like you can zoom in and out of the board.

**Comment by yishn** [comment]
It basically zooms in the font size. The board will always try to fit in the window.
