### ISSUE TITLE
Blurred background

### ISSUE THREAD

**Issue by ParmuzinAlexander** [SabakiHQ/Sabaki#531]
Screenshots https://yadi.sk/i/zaOK6pEGfw1d2A
Sabaki v0.43 Windows 8.1 x64

**Comment by yishn** [comment]
Interesting... The board texture doesn't seem blurry at all, but the background is really blurry. I haven't changed anything related to the background, so I assume it's related to the major Electron bump.

**Comment by ParmuzinAlexander** [comment]
This depends on the vertical size of the window. If the number of pixels is even the background is not blurred.
Also default stone 1px less in v43...

**Comment by ParmuzinAlexander** [comment]
I think I found the solution, need change background-position center to left top `background: #C2CB9C url('../img/ui/tatami.png') left top;`
