### ISSUE TITLE
"View/Show Move Numbers" does not work in Edit mode

### ISSUE THREAD

**Issue by GopherAl** [SabakiHQ/Sabaki#533]
Various issues around this. For example, when "View/Show Move Numbers" is showing as ticked (turned on), selecting Edit mode takes the move numbers off the displayed stones on the goban.

**Comment by yishn** [comment]
This is Sabaki-related, so I moved the issue there. This behavior is intentional, because when editing, the user usually wants to see the actual markers, not the move numbers.
