### ISSUE TITLE
Flip board (reflection)

### ISSUE THREAD

**Issue by GopherAl** [SabakiHQ/Sabaki#534]
Enhancement to be added to the Tools menu. Along with the ability to rotate the board in 2 dimensions (**Tools/Rotate Clockwise** & **Tools/Rotate Anticlockwise**) it would be useful to be able to flip the board (equivalent to reflecting the board or rotating it through 3 dimensions):
(1) **Horizontally**  (for example, around column K on the 19x19 goban) so that the left edge column (column A) is swapped with the right edge column (eg 19x19 goban column T), etc;
(2) **Vertically** (for example, around row 10 on the 19x19 goban) so that the top row (eg 19x19 goban row 19) is swapped with the bottom row (row 1).
I suggest that the new commands be named **Flip up** and **Flip right**.

**Comment by fohristiwhirl** [comment]
@yishn - Since I did the rotation, would you like me to have a go at the flips as well? I see things have changed a little and it now returns a function, but I'll probably figure it out...
