### ISSUE TITLE
Sabaki on the Google Cloud

### ISSUE THREAD

**Issue by jslechasseur** [SabakiHQ/Sabaki#537]
I set up a VM on the google cloud and I can run Lizzie on my laptop using their Tesla V100. When I try to do the same thing with Sabaki, the connection fails, even though I use the same command. Here's the setup.

<img width="1163" alt="Screen Shot 2019-03-25 at 8 21 50 PM" src="https://user-images.githubusercontent.com/35378510/54962556-b3388000-4f3b-11e9-95ee-95d56c2a227e.png">

Has anyone managed to do something similar with Sabaki? I feel leelaz runs slower in lizzie than in the terminal, so I was curious to see how it performs in Sabaki.

**Comment by apetresc** [comment]
This should definitely work almost exactly as you're doing it - the only problem is that you have `ssh` in the arguments list. It's already set in the first field (the command) - if you remove the `ssh` token from the arguments it should be good.

**Comment by jslechasseur** [comment]
Ah, good point. Like this?

<img width="1129" alt="Screen Shot 2019-03-26 at 1 37 50 AM" src="https://user-images.githubusercontent.com/35378510/54973808-e5f86d80-4f67-11e9-9528-b8e0829d1f33.png">

To my surprise, it still doesn't work... Here's what I get in the gtp console:

<img width="1440" alt="Screen Shot 2019-03-26 at 1 39 50 AM" src="https://user-images.githubusercontent.com/35378510/54973873-3243ad80-4f68-11e9-9e01-cac628cf6233.png">

**Comment by fohristiwhirl** [comment]
I don't know at all, but don't you perhaps need some sort of flag and maybe quotation marks to tell ssh to actually run the thing after the connection info? Some googling suggests it might be...

`-t "jeansebl777_gmail_com@35.225.111.165 /leela-zero/build/leelaz --gtp --lagbuffer 0 --weights /home/jeansebl777_gmail_com/LZ214.gz"`

**Comment by jslechasseur** [comment]
Thanks for the tips. I tried all of them, but sadly I get the same error message :(

**Comment by yishn** [comment]
@jslechasseur Maybe you can show us what happens when you type in the full command in the Terminal?

**Comment by jslechasseur** [comment]
It runs Leelaz on the VM  as expected:
<img width="1440" alt="Screen Shot 2019-03-26 at 12 17 36 PM" src="https://user-images.githubusercontent.com/35378510/55014437-57183f00-4fc1-11e9-924d-b47a4c405851.png">
(and the missing bit)
<img width="586" alt="Screen Shot 2019-03-26 at 12 22 22 PM" src="https://user-images.githubusercontent.com/35378510/55014722-dd348580-4fc1-11e9-9458-736d00fa438d.png">

From here, Leelaz is waiting for instructions. For example, I could ask it to play a black move, and it works:

<img width="1440" alt="Screen Shot 2019-03-26 at 12 29 40 PM" src="https://user-images.githubusercontent.com/35378510/55015250-e3773180-4fc2-11e9-972a-4b02cb96d773.png">


Also, if you are familiar with Lizzie, inserting this exact same command in the config.txt file as follows works perfectly:

<img width="1440" alt="Screen Shot 2019-03-26 at 12 20 33 PM" src="https://user-images.githubusercontent.com/35378510/55014577-99da1700-4fc1-11e9-949d-0059dc49aa98.png">
<img width="1440" alt="Screen Shot 2019-03-26 at 12 31 59 PM" src="https://user-images.githubusercontent.com/35378510/55015469-42d54180-4fc3-11e9-8622-24f7b98ca3c5.png">

**Comment by fohristiwhirl** [comment]
Actually - `connection failed` is what Sabaki prints when it can't start the process at all, i.e. probably ssh isn't starting. Is it certainly in `/usr/bin/` and not some other location?

**Comment by yishn** [comment]
Sabaki should work with environment variables, so you could also try to just specify `ssh` instead of `/usr/bin/ssh`.

**Comment by jslechasseur** [comment]
This fixed my problem, thanks a lot!
