### ISSUE TITLE
Arrow keys are wrongly assigned?

### ISSUE THREAD

**Issue by nemja** [SabakiHQ/Sabaki#543]
I think the behaviour of up/down and left/right arrows are the wrong way around.

In general UI practice up/down steps a complete line (a large unit). And left/right are the most common, smallest step in the natural flow/direction of documents.

I suppose the convention was ignored to match the visuals of the game tree, but I (as a new user) still found it confusing and hard to get used to. Could this be configured?

**Comment by yishn** [comment]
I have no idea what you’re saying. Can you be more specific what you expect Sabaki to do when you press the arrow keys?

**Comment by nemja** [comment]
I would expect left/right to step one move back/forward (as in other go boards), and up/down to make a bigger jump like moving to previous/next variation.

**Comment by yishn** [comment]
It just does not work that way and this won't be changed.

**Comment by nemja** [comment]
As I wrote I understand that and the (supposed) reason behind it. That's why I suggested some kind of custom key configuation (maybe for other commands as well) instead of directly changing it.

It is rather painful not to have something that works everywhere else, even in movie players, youtube, and all other gobans.
