### ISSUE TITLE
Connection Failed On Third Move (Most of the Time)

### ISSUE THREAD

**Issue by Nyquixt** [SabakiHQ/Sabaki#544]
For some reasons, the Sabaki client always has a connection failed on the third move (B's second move) in self-play mode. I'm trying to test 3x3 board size out. Worked **_once_**!
The params I passed in look like **-g -t 1 -p 500 --noponder -w $[PATH-TO-WEIGHTS-FILE]** with the initial commands **time_settings 0 10 1**.
<img width="2560" alt="Screen Shot 2019-04-06 at 11 19 44 PM" src="https://user-images.githubusercontent.com/34199633/55678644-c3991500-58c2-11e9-89a9-eb75df6df959.png">

**Comment by fohristiwhirl** [comment]
Is this a special version of Leela for 3x3? What happens if you run it in the terminal?

**Comment by Nyquixt** [comment]
I just went to the config.h file in /src and change the board size to 3. The engine runs like 19x19 with **./leelaz -w 3x3_weights.txt** in terminal. Just that when I run leelaz in Sabaki, it seems that the third move always causes the connection fail.

**Comment by fohristiwhirl** [comment]
I mean it seems like it's going to be an issue with this special version of Leela. Did you try running it with the very same command line options (except maybe `-g`) and play for a few moves?

**Comment by Nyquixt** [comment]
Yeah. It works totally fine.

**Comment by apetresc** [comment]
Can you attach the `3x3_weights.txt` file so we can try to reproduce?

**Comment by Nyquixt** [comment]
Hm. I think it’s because of the computer. Today it works fine for every game so I think there’s nothing wrong with sabaki.
