### ISSUE TITLE
Sabaki adding large amounts of whitespace in some cases

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#550]
Here's an annotated SGF file I produced (with my own [analysis script](https://github.com/fohristiwhirl/leela_zero_analysis)). If you open it in Sabaki and re-save it, its size will balloon up by about 1000%, due to added whitespace...

This is due to indenting of variations, I think. How much value does this have, really? SGF is barely human-readable anyway...

[annotated.sgf.txt](https://github.com/SabakiHQ/Sabaki/files/3077351/annotated.sgf.txt)

**Comment by yishn** [comment]
It's useful for debugging purposes. I'm changing to no unnecessary whitespace by default, adding `sgf.format_code` setting key.
