### ISSUE TITLE
Inconsistent state due to pass node after resuming engine game.

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#556]
I don't believe this is related to #553.

I am able to get the process into some inconsistent state by the following procedure:

* Attach two copies of Leela.
* Play until Leela resigns.
* Delete the pass node that Sabaki generates.
* Restart the engines.

I think what happens is that Sabaki sends an undo, but the engines aren't aware any pass node was ever generated. I've always felt it shouldn't be.

In order to make this test happen fairly quickly, I recommend settings like "-p 1 --resignpct 30" or such.

**Comment by yishn** [comment]
This is happening because we didn't consider passes as actual engine moves in the move history. I fixed it in https://github.com/SabakiHQ/Sabaki/commit/8f19febe20c07c010a2d7f8e834ea0ad7d909559.

**Comment by GoPlayers** [comment]
In my stuation there is no pass? There is resign before and undo.
