### ISSUE TITLE
Handicap stone location wrong if changing size

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#568]
* Start a game at some size, e.g. 19.
* Make a handicap game (e.g. H4) at size 17.
* The stones are in the wrong place.

New as of  commit 918f97a I think. [Edit: or not.]

**Comment by fohristiwhirl** [comment]
Actually this goes back a bit, at least it's in 43.2

**Comment by yishn** [comment]
It originates from the restructuring of Sabaki to use immutable game trees.
