### ISSUE TITLE
Browse the Chinese commentary for garbled characters

### ISSUE THREAD

**Issue by xsaxy** [SabakiHQ/Sabaki#573]
When the new version browses past sgf files, the comments are garbled. There are many such sgf files.
![1](https://user-images.githubusercontent.com/26270850/57567130-6a635a80-7407-11e9-953b-ea013d3f6e23.png)

**Comment by yishn** [comment]
Can you direct us to an SGF file we can test this on?

**Comment by xsaxy** [comment]
test sgf file
https://github.com/xsaxy/Sabaki-zh-CN/tree/master/test/sgf

wuqiyuan.sgf

**Comment by yishn** [comment]
Seems to be related to [this iconv-lite issue](https://github.com/ashtuchkin/iconv-lite/issues/204).
