### ISSUE TITLE
Opening SGF requires reloading of an engine.

### ISSUE THREAD

**Issue by lukaszlew** [SabakiHQ/Sabaki#574]
Analyzing multiple games with an engine requires to reattach an engine (5 clicks), waiting for it to start (which can be lengthy) and re-enabling analysis mode with F4. This is cumbersome if you are using it to play multiple games in [cyborg mode](https://en.wikipedia.org/wiki/Advanced_Chess).

Would it be possible to not reload an engine when SGF is opened?

**Comment by yishn** [comment]
Of course it would be possible, but since currently the way to attach an engine is via the game info drawer, it would be weird if all the game metadata is bound to a game and the engines aren't.

**Comment by yishn** [comment]
This probably should be solved via #575.

**Comment by yishn** [comment]
I‘m closing this in favor of #575.
