### ISSUE TITLE
Flexible engine connection

### ISSUE THREAD

**Issue by lukaszlew** [SabakiHQ/Sabaki#575]
Sometimes one wants to attach an engine w/o assigning it to a particular color.
A more rare use-case is when one wants to observe 2 engines playing and display analysis by 3rd of them.
The proposal is to decouple engine connecting (which can be slow due to startup time) from assigning a function. 
I.e. one could connect 3 engines (or just one) and in a separate place define who plays white, who plays black and who is doing the analysis.

**Comment by yishn** [comment]
Yes, I agree. The current state of engine handling of Sabaki can be improved upon.

**Comment by lukaszlew** [comment]
Can this change be broken up into smaller changes that could be coded separately? 
If yes, could you sketch that?
If no, is there perhaps a hacky way to achieve the desired functionality (importantly #574) ?

**Comment by ivysrono** [comment]
+1, add third engine to analysis.
