### ISSUE TITLE
Language support in I18N files?

### ISSUE THREAD

**Issue by xsaxy** [SabakiHQ/Sabaki#578]
First of all, thank you for your amazing work.
I guess this is the case, but not. Please teach me.

src/lang/zh-CN.js

{
    'menu.file' : {
        '&File' : '文件',
        '&New' : '新建',
    },
    
    'menu.play' : {
       '&play' : '对局中',
       '&Toggle Player' : '切换对局者'
    }
}

**Comment by yishn** [comment]
Thanks for your interest, but I need to work on i18n a little bit more. I will write an article on i18n in the documentation once it’s ready. Please subscribe to #144 for updates.
