### ISSUE TITLE
Adding games to the Manage Games screen don't stay in the library

### ISSUE THREAD

**Issue by aheavyburden** [SabakiHQ/Sabaki#582]
I'm running the latest Sabaki on my MacOS (Mojave). If I add some SGFs to my library, then restart Sabaki, all the games I added are gone when I check "Manage Games" again. 

It seems Sabaki just isn't remembering all the games I added.

Am I doing something incorrectly here? Or is this a bug?

**Comment by yishn** [comment]
The 'Manage Games' feature isn't application specific, it's file specific. You have to save the SGF file to persist it; opening the saved SGF file will show that it contains multiple games.

**Comment by aheavyburden** [comment]
Ah okay, I understand now. Thanks a bunch!
