### ISSUE TITLE
Disappearing comments.

### ISSUE THREAD

**Issue by acosmicjoke** [SabakiHQ/Sabaki#584]
When i write or change a comment than leave edit mode right after i input the last character the content of the comment field changes back to what it was before i started editing it. If i wait a few seconds before leaving edit mode there is no issue, but it is still really irritating to write out sentences several times because i tried to do it too fast.

**Comment by fohristiwhirl** [comment]
Can confirm.

**Comment by CoolBoots** [comment]
Same issue for me. Quite frustrating to lose the comment if it was quite long.
