### ISSUE TITLE
Preserve window maximized state

### ISSUE THREAD

**Issue by ivysrono** [SabakiHQ/Sabaki#586]
as title.

**Comment by yishn** [comment]
We should probably save the window state along with window dimensions when closing.

**Comment by mdm** [comment]
I'd like to work on this if nobody else is.

**Comment by yishn** [comment]
I'm unassigning this issue since there are no updates.

**Comment by ivysrono** [comment]
```
const {screen} = require('electron')
const display = screen.getPrimaryDisplay()
const dimensions = display.workAreaSize
let defaults = {
  'window.height': dimensions.height,
  'window.width': dimensions.width
}
```

`Error: The 'screen' module can't be used before the app 'ready' event`

**Comment by ivysrono** [comment]
#670

**Comment by yishn** [comment]
Please don't close this issue until a PR is merged.
