### ISSUE TITLE
feature request: show KataGo endstate on every point 

### ISSUE THREAD

**Issue by ivysrono** [SabakiHQ/Sabaki#589]
Newest Lizzie for KataGo:
![图片](https://user-images.githubusercontent.com/2649544/60186826-20bbbb80-985f-11e9-955d-05d11a711089.png)

**Comment by yishn** [comment]
I don't get it. What's the difference to the analysis mode we have now? Please elaborate.

**Comment by ivysrono** [comment]
[](https://user-images.githubusercontent.com/2649544/60392256-821aad80-9b31-11e9-9054-4a8778953055.png)
By KataGo, Lizzie displays three parameters: winning rate, calculation amount, and endstate. And the option can determine which parameters are displayed.
LizGoban displays the endstate and the amount of calculation by default.
Now Sabaki can only display the first two, no endstate.
I hope to show the third and the most inportant: endstate.

**Comment by ivysrono** [comment]
@yishn Are you still need more info now?

**Comment by yishn** [comment]
What does endstate mean and how do you get it?

**Comment by yzyray** [comment]
> What does endstate mean and how do you get it?

https://github.com/lightvector/KataGo/issues/25#issuecomment-504013115

use kata-analyze command and lizzie displayed the "scoreMean" on suggestions points

**Comment by Nihisil** [comment]
https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md

The attribute was renamed to the `scoreLead`:

> scoreLead - The predicted average number of points that the current side is leading by (with this many points fewer, it would be an even game).

**Comment by ivysrono** [comment]
Is there any progress？
@yishn

**Comment by egri-nagy** [comment]
I agree that the score estimate is more informative for analysis. I do a lot of game reviews (for a university course) and beginners often get a flat line in the winrate graph (definite loss or win), so there is no information whehter the moves are good or not after some deciding blunder in the beginning. On the other hand the score estimate can still go up and down in a meaningful way.

So I can confirm, that displaying the average score estimate would be a useful addition.

**Comment by yishn** [comment]
Sabaki can't integrate with features that are only available in `kata-analyze` because `kata-analyze` doesn't conform to our [analyze command standards](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/engine-analysis-integration.md).
