### ISSUE TITLE
Komi is not supported by engine

### ISSUE THREAD

**Issue by dan201303** [SabakiHQ/Sabaki#591]
Error: Komi is not supported by engine
Windows7 with phoenixgo engine

**Comment by yishn** [comment]
Most likely a phoenixgo issue.

**Comment by dan201303** [comment]
Thank Yichuan-------- 原始邮件 --------主题：Re: [SabakiHQ/Sabaki] Komi is not supported by engine (#591)发件人：Yichuan Shen 收件人：SabakiHQ/Sabaki 抄送：dan201303 <270239297@qq.com>,Author Most likely a phoenixgo issue.
