### ISSUE TITLE
"gtp engine ouput has stopped" warning in Sabaki

### ISSUE THREAD

**Issue by Etincelle8** [SabakiHQ/Sabaki#592]
Hello,

I keep getting a "gtp engine output has stopped" popup in Sabaki whenever it is leelaz turn.

I am not very good with computers and my english is not perfect 
although I did some research, watched videos, unsuccessful :/ 

Leela Zero
Path: D:\Téléchargements\Firefox\leela-zero-0.17-win64\leelaz.exe
Arguments: -g -t4 -q -–noponder -p2500 -w 06e03050a20e0afb4fd1002883e44f8e19463b207550338a16b0f5b49f9b514a4

Can someone helps me ?

Thank you

**Comment by fohristiwhirl** [comment]
Your `--noponder` argument appears to have an ndash in it, replace that with double ASCII dashes, i.e.

```
-–noponder    // wrong
--noponder    // right
```

Also check the path of the weights file. It's not in a networks folder, is it? If yes, it would be

`-w networks/06e03050a20e0afb4fd1002883e44f8e19463b207550338a16b0f5b49f9b514a4`

or sometimes:

`-w networks/06e03050a20e0afb4fd1002883e44f8e19463b207550338a16b0f5b49f9b514a4.gz`

**Comment by Etincelle8** [comment]
Oh perfect it works, thank you !

I changed for --noponder and I added .gz

By cons, I expected to see the statistics appear after each play. Do you know what I can do for that?

**Comment by fohristiwhirl** [comment]
Delete -q from your options.

**Comment by Etincelle8** [comment]
Done, what does it change ?

Still no stats after each play.

**Comment by fohristiwhirl** [comment]
Open the GTP console, if you haven't already: Engines menu --> Toggle GTP console

**Comment by Etincelle8** [comment]
Yes I already have this.

In fact, when I talked about posting statistics, I wanted to tell the sites of potential plays.

**Comment by Etincelle8** [comment]
No idea ?

**Comment by fohristiwhirl** [comment]
That stuff shows up if you use the Toggle Analysis command (or press F4).

**Comment by Etincelle8** [comment]
Oh ok I'm a noob ^^'

Thank you it works good ;)
