### ISSUE TITLE
Engine won't stay suspended

### ISSUE THREAD

**Issue by yang-james** [SabakiHQ/Sabaki#594]
when I assign white to an engine and I play black. In the middle of the game, I want to suspend the engine and make a move for it. But the engine will start to play black. I have to suspend it again. I thought it should stay suspended until I click on "start playing".  Also restart should be faster than attach the engine again.

**Comment by yishn** [comment]
Suspension of engines is currently doing the following:

- Terminate engine process
- Leave the engine "attached", so there's no need to attach engine again
- On next command, start engine process, do state sync, etc. while pretending the engine process never got terminated

So for the application user there's no behavior change (except for waiting a little bit longer when we restart the engine).
