### ISSUE TITLE
What do the meanings of score and Estimate?

### ISSUE THREAD

**Issue by xiaominghe2014** [SabakiHQ/Sabaki#601]
I'm confused with the results bettwen score and Estimate.
score result is W+77.5, but Estimate result is B+102.5

**Comment by yishn** [comment]
If the game is finished, choose 'Score' to determine the winner. If the game is unfinished, choose 'Estimate' to get an idea how much a player is ahead or not. In both cases, the result vary depending on what stones you choose are dead.

**Comment by zzj0402** [comment]
> If the game is finished, choose 'Score' to determine the winner. If the game is unfinished, choose 'Estimate' to get an idea how much a player is ahead or not. In both cases, the result vary depending on what stones you choose are dead.

What do you mean by "choosing dead stones"?
