### ISSUE TITLE
Sorry, looking for documentary/help how to create tree (variations)

### ISSUE THREAD

**Issue by deegeebee** [SabakiHQ/Sabaki#602]
I'm using Sabaki the first time and want to use it for analyzing varations of a game.
How do I create and navigate variations?
I'm not able to find a documentary / help page. Advice?? Thank you!

**Comment by yishn** [comment]
Navigate to the node where you want to start a variation (by up/down keys, mouse wheel, game tree) and click on the board to place stones for the new variation.

Unfortunately, there's no user guide/help page right now.
