### ISSUE TITLE
Layout broken on linux. 

### ISSUE THREAD

**Issue by lukaszlew** [SabakiHQ/Sabaki#605]
Board is a tiny square on top edge.
Broken in e76c6475c5d012782f38c978f4e38dcbd0629407

Fix below.

-----

~~~
diff --git a/style/index.css b/style/index.css
index ae6cbb4f..57e18ce6 100644
--- a/style/index.css
+++ b/style/index.css
@@ -9,7 +9,6 @@
 }
 
 #main {
-        position: relative;
         z-index: 10;
     }
     main {
~~~

**Comment by yishn** [comment]
Thanks for the report! Can you submit a PR for this, please?

**Comment by lukaszlew** [comment]
I'm not sure whether this is the right fix, I never edited CSS before :)
I just bisected the CLs and then bissected the offending CL for a single line.
Sorry, I'm not going to learn to submit PRs now.

**Comment by Nihisil** [comment]
I have checked `cec6f95007f6d137a81e2dc6f7f431ae2f434563` version on Ubuntu Linux and the main screen looks fine: 

![image](https://user-images.githubusercontent.com/475367/67762831-47923480-fa81-11e9-82c0-c2109054f557.png)

So, an issue could be related not to the Linux itself, but to something else.

Also, if you apply the proposed patch, the left part of the screen for the engine output will be gone, and there will be only the game board window.

**Comment by lukaszlew** [comment]
Where did you check it in? is this some branch?

**Comment by Nihisil** [comment]
`cec6f95007f6d137a81e2dc6f7f431ae2f434563` refers to the commit hash. It is latest commit in the master branch.

**Comment by lukaszlew** [comment]
Ah indeed. I got confused by the September commit date. 
Big thanks.

**Comment by lukaszlew** [comment]
It displays in this way on my debian/cinnamon:
![Screenshot from 2019-10-30 10-34-06](https://user-images.githubusercontent.com/37749/67883190-dc884280-fb00-11e9-92a0-2cc951629ec1.png)

Do you have an idea how to proceed with debugging?
