### ISSUE TITLE
Load a new sfg file without having to reload an engine

### ISSUE THREAD

**Issue by hadim** [SabakiHQ/Sabaki#606]
At the moment, when I have a game loaded with an engine attached to it, if I drag and drop a new SGF file after Sabaki opens it the engine previously attached is gone.

If making engine independent from an opened game is too complicated, we could imagine a workflow where I open the second SGF file in a new window and copy/paste the entire game to the first loaded game (that has the engine attached to it).

**Comment by yishn** [comment]
This is part of the engines handling rewrite that is in progress right now.
