### ISSUE TITLE
Watch leela zero during self training

### ISSUE THREAD

**Issue by hadim** [SabakiHQ/Sabaki#607]
Leela zero allows anyone to contribute by executing a game between two different networks. Would be cool to be able to watch in live those game.

The command is `./autogtp/autogtp`. Then it's just a matter of parsing the output and sending it to Sabaki:

```
Got new job: selfplay
net: 901e04ded97854dc028f574b77839c0b226e265914d68161c47ee9363b1c27fc.
Engine has started.
time_settings 0 1 0
Starting GTP commands sent.
1 (B R4) 2 (W R16) 3 (B C16) 4 (W D3) 5 (B P17) 6 (W E16) 7 (B E17) 8 (W F17) 9 (B D17) 10 (W F16) 11 (B Q15) 12 (W R15) 13 (B Q14) 14 (W R13) 15 (B C14) 16 (W K16) 17 (B C5) 18 (W E4) 19 (B O3) 20 (W M17) 21 (B P12) 22 (W M3) 23 (B H15) 24 (W D16) 25 (B C17) 26 (W H16) 27 (B K15) 28 (W P3) 
```

There is a program called Leela Watcher that does this already but Sabaki is a much nicer client.

Could we add this as a Sabaki plugin?

**Comment by yishn** [comment]
I think this feature is out of scope of Sabaki.

**Comment by hadim** [comment]
I agree it's out of scope. That's why I was asking if we could think about adding it as a plugin.
