### ISSUE TITLE
Display last move win-rate % change

### ISSUE THREAD

**Issue by ashleylester** [SabakiHQ/Sabaki#610]
Hi Yishn

Thanks again for the great software. Leela Zero is working great with Sabaki.

I was wondering if you could tweak the UI to show the "Last Move Win Percentage Gained / Lost". This is a feature which I miss from the Lizzie interface. This shows, as a percentage, how far the played move was, in comparison with the optimal evaluation. 

Otherwise I find myself having to remember the win percentage and then deduct the "new" win percentage after I play a move. This gets a bit irritating because I like to click through my games and look at moves at-a-glance with a win percentage difference over 5% as "worth checking out".

You can see it in the top-left of the main Lizzie screenshot, just above the win-rate line chart here, where it says "Last Move: -5.2%":

https://github.com/featurecat/lizzie

**Comment by ivysrono** [comment]
+1

**Comment by yishn** [comment]
I'm merging this issue with #620. Please subscribe there for updates.
