### ISSUE TITLE
Sabaki not working in WSL (Ubuntu 18.04)

### ISSUE THREAD

**Issue by wolves2810** [SabakiHQ/Sabaki#611]
I cannot open the appimage file in both GUI and command.
When I tried to open the file, nothing happened.
Even it didn't any error message.
How to run sabaki in WSL?

**Comment by yishn** [comment]
Why not run Sabaki under Windows using Windows binaries? WSL isn’t able to run all Linux binaries, especially those with GUI.

**Comment by wolves2810** [comment]
Actually, it works in my laptop, but I want to run sabaki through google cloud platform, because the laptop's performance is really bad. (My graphic card is hd graphics 4000 in cpu.)
Yeah.. I know it's a very odd way.

**Comment by yishn** [comment]
I don't get it. What does WSL have anything to do with the Google Cloud Platform?

**Comment by wolves2810** [comment]
I created VM instance(ubuntu) in Google Cloud Platform. I tried to run sabaki through that vm instance. If I connect the VM instance in Windows, is it ubuntu? or WSL? Honestly I'm confused.

**Comment by yishn** [comment]
It's probably Ubuntu, then. I'm not familiar with GCP at all, so I can't really help. You can try running Chrome in the VM, though. If Chrome doesn't start, then it's unlikely that Sabaki can start on GCP.

**Comment by wolves2810** [comment]
Okay. Thanks for replying.
