### ISSUE TITLE
KataGO with Sabaki

### ISSUE THREAD

**Issue by ulgr** [SabakiHQ/Sabaki#612]
I am running KataGO without problems natively (MacOSX). Adding this engine with the path set as requested I also get "connection failed". What is wrong? The dettings have been attached.
Thanks a Lot
Ulrich 
![katago1](https://user-images.githubusercontent.com/24019239/70069627-604ab880-15f2-11ea-9573-9afce064a7a0.png)
![katago2](https://user-images.githubusercontent.com/24019239/70069628-604ab880-15f2-11ea-8fe2-d5fe3a8fda12.png)
![katago3](https://user-images.githubusercontent.com/24019239/70069659-6b9de400-15f2-11ea-8301-f424d9f32aa7.png)

**Comment by ulgr** [comment]
I changed the directory from "Document" to "Desktop", anything als is the same. Now it is working. A miracle for me, but it is working. See the attached file (KataGO-2 is working, KataGO not)
![katago-new](https://user-images.githubusercontent.com/24019239/70153781-c9dccc80-16af-11ea-9acb-60685107315e.png)

**Comment by yishn** [comment]
I see in KataGO you have a whitespace before the actual path starts. Maybe that was the reason it didn't work...
