### ISSUE TITLE
Goban visualisation in 3D

### ISSUE THREAD

**Issue by ALROCHARARI** [SabakiHQ/Sabaki#614]
Dear,

When using a great goban editor, we all want to have the most efficient solution and also **the most realistic / like in the real life** experience.  This editor is adding a lot to this latest point with the nearly random positionning of the stones on their spots.  

To make it really like when we play with human opponents in real life, I think what we miss the most is a **three dimensional view of the goban**.

Advantages: 

     - Like in real life

     - Same pre-visualisation of territories 
       (groups on opponent side are looking smaller but are of the same value)

     - Esthetic

     - Reduce feeling differences between real life and computer based games

I think that if "**An elegant Go board and SGF editor for a more civilized age.**" is your target, than this ultimate improvement should be the solution.

A low quality example: http://www.pandanet.co.jp/English/glgo/
![GlGo_3D](https://user-images.githubusercontent.com/26901310/70683113-f90cc280-1cdb-11ea-972f-85c9753f22e3.jpg)

With my best regards,

**Comment by fohristiwhirl** [comment]
> When using a great goban editor, we all want to have the most efficient solution and also the most realistic / like in the real life experience.

I absolutely disagree. Go is inherently a 2D game.

**Comment by Chiefman** [comment]
> To make it really like when we play with human opponents in real life, I think what we miss the most is a **three dimensional view of the goban**

Sound good only if its an option and you can still swap and choose the current 2D format

**Comment by yishn** [comment]
I'm closing this as this is unlikely to be included into Sabaki.
