### ISSUE TITLE
Command + W and Command + Q Do not Work

### ISSUE THREAD

**Issue by MacErlang** [SabakiHQ/Sabaki#625]
Hi all,

Below are two issues I have:

1. For a standard Mac program, pressing Command + w would close an open window
(but not the program). This does not work for Sabaki.

2. Pressing Command + q would normally quit a program. Again this does not happen
for Sabaki.

Any comments?

Thanks,
Shun

**Comment by yishn** [comment]
The behavior of 'Quit' is a known bug of Electron. Subscribe to #157 for updates.
