### ISSUE TITLE
How to make sabaki to support other game, like Gomoku?

### ISSUE THREAD

**Issue by zliu1022** [SabakiHQ/Sabaki#627]
Hi, @yishn 

I like Sabaki UI very very much.
And I wish to modify Sabaki to support Gomoku (five-in-a-row) which follow gtp protocol well, which means NOT to check the stone list's liberty and clean the stone with 0 liberty.
I check the code and just guess it should be in sabaki/go-board?
I don't know node.js well, I can only do very little modification inside sabaki main program, so I don't know how to modify this requirement.

Can you give me some tip?

Thank you.

**Comment by friedrichren** [comment]
This would be a lot of work, so maybe you should fork Sabaki and then start by trying to remove all the components that's not needed for Gomoku.

**Comment by yishn** [comment]
You can copy the code from [the `GoBoard` class from `@sabaki/go-board`](https://github.com/SabakiHQ/go-board/blob/v1.4.1/src/GoBoard.js) and modify the function `makeMove` to your liking. Then, adjusting the code in Sabaki, replace all occurences of `require('@sabaki/go-board')` with `require('path/to/your/modified/GoBoard.js')`.
