### ISSUE TITLE
Use GTP engine running remotely

### ISSUE THREAD

**Issue by kota7** [SabakiHQ/Sabaki#628]
Will it be possible to run a GTP engine for the analysis remotely on cloud (e.g. AWS, GCP)?  
Lizzie supports that for leela-zero by setting like

```
"engine-command": "ssh -i key123.pem ubuntu@ec2-18-213-3-208.compute-1.amazonaws.com leela-zero/src/leelaz --weights leela-zero/best-network --gtp --lagbuffer 0 --threads 2"
```

I wonder if such functionality is already supported for Sabaki.

**Comment by yishn** [comment]
Yes, see e.g. #537.
