### ISSUE TITLE
Need Help ! GTP engine output has stopped warning

### ISSUE THREAD

**Issue by misakamikoko** [SabakiHQ/Sabaki#631]
I have examined the path to the core text file several times but nothing changed.
Path: C:\Go\leela-zero-0.17-win64\leelaz.exe
statement: -g -t4 -w brain.txt --noponder --playouts 3000
initial command: time_settings 0 20 1

**Comment by yishn** [comment]
Try executing your command in the command line. What does it say?

**Comment by misakamikoko** [comment]
Thank you for replying, I have changed the extension name of the weigh file, it runs well now.
