### ISSUE TITLE
Is it possible to comment a link to a variation node?

### ISSUE THREAD

**Issue by ClaytonHughes** [SabakiHQ/Sabaki#633]
I (accidentally) linked to a node in the main sequence by typing `#1, #2, and so on` into the comments of a file I was creating.

I'm wondering if there is any way to do something similar to link to a node in a variation, e.g. by referring to `#6a` (although obviously not that: it doesn't work).

I had an idea to create a similar "Table of Contents" to @yishn's proposal in [this comment on #488](https://github.com/SabakiHQ/Sabaki/issues/488#issuecomment-449178597).

**Comment by yishn** [comment]
Hi, no it's currently not possible. The feature you're describing is exactly what #488 is for.
