### ISSUE TITLE
Feature suggestion: Click & Drag recent move

### ISSUE THREAD

**Issue by CoolBoots** [SabakiHQ/Sabaki#635]
As show by the application in this video (time code 16:14): https://youtu.be/1Zw8-FLk_3g?t=974  

I keep 'Show Remove Node Warning' turned on to prevent accidental clicks, but it results in the annoying dialog box and Windows alert sound each time I need to move the most recent stone. This feature would solve this issue, and would also be useful for demonstration purposes, as in the above video.

A slight delay before the user 'picks up' the stone could prevent accidental moving.

**Comment by yishn** [comment]
You can undo stone placement or node deletion by <kbd>Ctrl/Cmd+Z</kbd>.
