### ISSUE TITLE
Estimate score using engine

### ISSUE THREAD

**Issue by benjaminvdb** [SabakiHQ/Sabaki#640]
Is it possible to estimate the score using an engine, e.g. KataGo?

**Comment by yishn** [comment]
You can type and execute any GTP command in the GTP console and KataGo supports the command `final_score`.

**Comment by benjaminvdb** [comment]
Thank you for the quick response, @yishn. I was hoping this information could perhaps be integrated into the UI, rather than in the GTP console. In the end, all features of KataGo can be used from there, but it's Sabaki that makes it so much easier to use 😃

I understand there are no plans to integrate KataGo scoring into the Sabaki UI?

**Comment by yishn** [comment]
Then you're probably looking for https://github.com/SabakiHQ/Sabaki/issues/619. Subscribe there for updates.
