### ISSUE TITLE
Windows defender alerts virus detected in sabaki-v0.50.0-win-x64-setup.exe on win10 1909

### ISSUE THREAD

**Issue by spindensity** [SabakiHQ/Sabaki#641]
Windows defender alerts virus detected in sabaki-v0.50.0-win-x64-setup.exe on win10 1909 and deletes the file, it should be a false warning, could repackaging the installer or reporting to Microsoft solve the problem?

**Comment by yishn** [comment]
Please do report as a false positive since [no other anti-virus detects anything](https://www.virustotal.com/gui/url/9115d4c8c4fb6155a2c299b6d7736628796958222d1886fe1f934a985880e51a/detection).

**Comment by yishn** [comment]
I've reuploaded the Windows binaries manually again, and it seems like Windows Defender is not complaining anymore.
