### ISSUE TITLE
Winrate graph stop working

### ISSUE THREAD

**Issue by SHKD13** [SabakiHQ/Sabaki#645]
For SAI and Leela Zero engines it has gone completely (while it is **enabled** in View).
For KataGo it is not working properly: only blue vertical line is moving forfard without graph itself.
I had to go back to v0.43 to make all things work properly.
What is wrong?

**Comment by yishn** [comment]
It works for me. Please post a screeenshot. Keep in mind you need to activate analysis to record winrate data in the first place.

**Comment by SHKD13** [comment]
There is no winrate curve in top right corner like it was before for SAI and Leela Zero. It's gone for them:

![Screenshot_46](https://user-images.githubusercontent.com/39368053/76671255-bb9b2800-659d-11ea-9f13-8e672f509089.png)

For KataGo It shows only vertical blue line without a curve colored by grey.
Here how it was in v0.43 with a normal winrate graph:

![Screenshot_47](https://user-images.githubusercontent.com/39368053/76671312-36644300-659e-11ea-993d-ea76aff50696.png)

How can I bring it back?

**Comment by yishn** [comment]
How does it look for KataGo in v0.50.0? And if you're making a comparison using screenshot, please at least show the same file on the same position.

If you don't mind losing all your settings data, you can also try to reset Sabaki by deleting the `%APPDATA%\Sabaki` folder.

**Comment by SHKD13** [comment]
There is only vertical blue line in the top right corner for KataGo, no winrate curve colored by grey. And absolutely nothing for others.

I have deleted 0.50, load 0.43 back and the winrate curve immediately starts to work properly for SAI, LZ and Kata engines. 
Seems like a bug for new version. That's why I opened this issue.

**Comment by yishn** [comment]
Please post a screenshot for KataGo in v0.50.0. Did you try to reset Sabaki yet?

**Comment by SHKD13** [comment]
Screenshot for SAI & Leela Zero didn't help me, how Kata's screen will help?  
I already loaded back the v0.43 and have not so much aspiration update it again while this issue won't explain for me what is the problem with 0.50.1

**Comment by yishn** [comment]
I can't explain it to you if I don't get the necessary information to make an educated guess. If you don't feel like helping us investigate this issue further, I can just close this issue and move on with my life.

**Comment by SHKD13** [comment]
What do you men I don't want to help you with issue? I made a full description and a screenshots!
How the vertical blue line in top corner without winrate curve will help you more than my screenshot from SAI and Leela Zero?

**Comment by SHKD13** [comment]
Never ever heard on GiitHub nothing like "**I can just close this issue, do nothing and go to hell with the bugs of my software!**"
Totally new experience.
Are you sure there is no other man to help with this problem?
