### ISSUE TITLE
Both engines provide winrate in chart

### ISSUE THREAD

**Issue by barrtgt** [SabakiHQ/Sabaki#646]
Prior to 0.50.0 in engine vs engine games, Sabaki used to provide the winrate from both engines and it was nice to see how they would differ in their analysis. Is there any chance this feature could make a comeback?

**Comment by yishn** [comment]
The winrate from two different engines could produce an inconsistent graph, with far too many jumps from one move to another. How would that help game analysis?

**Comment by yauwing** [comment]
Theoretically, it is possible that one engine is more accurate for game analysis during the end game, while the other engine is better during the opening or middle game.
(showing both saves the trouble to switch)
Showing both win rate may also help game analysis indirectly by helping the users to choose the more accurate engine for future analysis. (choose the one that predicts correctly more often)
This is especially useful for comparing engines that have frequent updates.

**Comment by yishn** [comment]
Switching from one engine to another isn't too cumbersome, and also the user can make the switch explicitly.

Determining which engine is more accurate is best left to thorough, rigorous testing, not by a one time game between two engines. This is not the purpose of Sabaki, so I'm closing this issue.
