### ISSUE TITLE
Winrate graph for v0.50.1 still not working

### ISSUE THREAD

**Issue by SHKD13** [SabakiHQ/Sabaki#648]
Come on, if you built a software, help to users!
Why are you doing nothing and closing the issue?
I will open it again to fix the problem!

I updated to v0.50.1 again and this time winrate graph is not working even for KataGo:

![Screenshot_48](https://user-images.githubusercontent.com/39368053/76680762-09427f80-65f4-11ea-940d-4ef246cdbf50.png)

![Screenshot_49](https://user-images.githubusercontent.com/39368053/76680764-0cd60680-65f4-11ea-9e42-31c7cfd680d0.png)

Do something. You can't just made a buggy software and refuse people in help, am I wrong?

**Comment by SHKD13** [comment]
Please, anyone other who can help me with, gimme advice how to fix this problem

**Comment by yishn** [comment]
Can you please try to reset Sabaki by deleting the `%APPDATA%\Sabaki` folder. Make a backup of that folder if you do not want to lose all your settings.

**Comment by yishn** [comment]
> You can't just made a buggy software and refuse people in help

I can and in fact the [MIT license](https://github.com/SabakiHQ/Sabaki/blob/master/LICENSE.md) clearly states:

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED

**Comment by SHKD13** [comment]
Very nice of you for "I CAN".
For many years on GitHub you are the first developer i have ever seen who is doing this way to users.
Great new experience.

Is this folder do you mean to delete?

![Screenshot_50](https://user-images.githubusercontent.com/39368053/76680991-7525e780-65f6-11ea-941f-f40fc360bb4f.png)

**Comment by yishn** [comment]
No, it's located at `AppData\Roaming\Sabaki`. For further investigation, you can also try to open the following SGF file, which has winrate data included, to see if the winrate graph appears:

[1_Go-Seigen-Kitani-Minoru-1.zip](https://github.com/SabakiHQ/Sabaki/files/4332623/1_Go-Seigen-Kitani-Minoru-1.zip)

**Comment by SHKD13** [comment]
Aha, I found it:

![Screenshot_51](https://user-images.githubusercontent.com/39368053/76681015-d8b01500-65f6-11ea-8878-8ed29d28e8e6.png)

Delete everything?

**Comment by yishn** [comment]
Yes, don't forget to make a backup copy.

**Comment by SHKD13** [comment]
I can see people showing dislikes to my problem (yeah, this is so fun) and heart to your right do not help to me.
Guys, what is wrong with you here? I cannot even imagine anything like this in Leela Zero, KataGo, MiniGo or Lizzie repos on GitHub! 
Unreal.

Your idea is not working. I have deleted that folder with no effect

![Screenshot_52](https://user-images.githubusercontent.com/39368053/76681137-5e809000-65f8-11ea-938a-47911b3b68ff.png)

The bug is still here

**Comment by yishn** [comment]
Have you tried opening the sample SGF that I sent?

**Comment by SHKD13** [comment]
Here is SAI: **interactive** winrate graph is not working

![Screenshot_53](https://user-images.githubusercontent.com/39368053/76681850-d0100c80-65ff-11ea-8bb9-ec61b3d47ff3.png)

Here is your sgf file: **non** interactive winrate graph is present

![Screenshot_54](https://user-images.githubusercontent.com/39368053/76681894-29783b80-6600-11ea-8ead-10e940b30cd1.png)

No idea what is wrong with interactive graph during engine's work. It is working perfectly for v0.43, but is dead in v0.50.1

**Comment by SHKD13** [comment]
I reinstalled the v0.43. Everything is working as it should be:

![Screenshot_55](https://user-images.githubusercontent.com/39368053/76682066-6690fd80-6601-11ea-82ff-e2682c01235d.png)

**Comment by yishn** [comment]
Please make sure you have analysis mode activated by pressing <kbd>F4</kbd> or assigning SAI the analyzer role.

**Comment by SHKD13** [comment]
I mean NOT an analysis mode, but **playing** mode for engines. It is NOT a positions analysis on my screenshots, it is my interactive games with engines.
This is what I need to work. In v0.50.1 it is F10 mode - make engine play with you.
I like to analyze with ZBaduk online because of my GPU is not the fastest one and never use F4 option.

**Comment by yishn** [comment]
I see the confusion, in the old version, winrate data will be recorded regardless of whether you activated analysis mode or not. In v0.50.0 you need to assign an engine as an analyzer before winrate will be recorded.

**Comment by SHKD13** [comment]
Hmmm, I'll try once again.
Maybe I am dumb, but if this is the solution, it might be useful to indicate such an interface changes during the program start. 
Or maybe just by adding the Readme file with short instructions about serious interface changes. I haven't found them here: https://github.com/SabakiHQ/Sabaki/releases

**Comment by SHKD13** [comment]
1) Winrate graph start working
2) But it is showing the candidate moves **just on board**! How to disable them? I don't need this during the game. I have disabled everything I could, but it is still on board :(

![Screenshot_57](https://user-images.githubusercontent.com/39368053/76682324-e1f3ae80-6603-11ea-8025-7beca7962849.png)

![Screenshot_58](https://user-images.githubusercontent.com/39368053/76682326-e91abc80-6603-11ea-9024-3c1f070d6276.png)

**Comment by yishn** [comment]
Unfortunately, this is currently not possible. I've opened a new issue https://github.com/SabakiHQ/Sabaki/issues/649 for that. Please subscribe there for updates.
