### ISSUE TITLE
The lag issue of the analysis result

### ISSUE THREAD

**Issue by ebifrier** [SabakiHQ/Sabaki#650]
I am trying analysis mode with Sabaki,
I have one problem with the display lag of the analysis result.

Sabaki is much slower at displaying analysis results after make move than Lizzie.
I investigated the reason here, the cause was in the handling of the GTP protocol.

Sabaki cannot start the next 'lz-analyze' without processing
all 'info' commands corresponding to the previous 'lz-analyze'.
But Lizzie immediately starts the next 'lz-analyze', because Lizzie disregards any 'info' of the old phase.

When I checked the @sabaki/gtp source, Sabaki seemed to send and receive each command in pairs.
It seems difficult to fix it with the current architecture, but I want to fix it.
Do you have any ideas?

**Comment by yishn** [comment]
I doubt the the processing of `info` directives is the main cause of the "lag". Lizzie is syncing the engine immediately when the user is navigating the game tree, while Sabaki only syncs the engine after a delay determined by the `game.navigation_analysis_delay` setting (which defaults to half a second). The reason for this is to maintain good performance while the user navigating the game rapidly using scrubbing.

You can try to lower the delay, or even set to `0`, and see what happens by changing the setting directly. [Locate `settings.json`](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/debugging.md) and look for `game.navigation_analysis_delay`.

**Comment by ebifrier** [comment]
Thank you for your advice!
I tried it, and the response became smoother.

However, the lag is still longer compared to Lizzie.
I took a video and checked it.
It took about 2.3 seconds for the result to be displayed on Sabaki, and about 0.6 seconds for Lizzie.
If possible, I hope to reduce it by about one second.
Do you have any other advice?

**Comment by yishn** [comment]
Out of curiosity, which value did you set `game.navigation_analysis_delay` and what version of Sabaki are you using? What you can also adjust is `board.analysis_interval`. Lizzie's default value for the setting is `10`.

**Comment by ebifrier** [comment]
I'm so sorry.
In fact, I was using an old version of Sabaki, and testing with the new version did not cause any problems.
Thank you so much !
