### ISSUE TITLE
Bot not able to play first move on its own.

### ISSUE THREAD

**Issue by zelanter** [SabakiHQ/Sabaki#652]
Hi,

since version 0.50, when playing against a bot, (katago, haven't tried with others) the bot is not able to play the first move. It was working before that version. This applies to even games where bot is black and to handicap games where bot is white, so in short whenever the first move is played by the bot. In case of handicap games, it is possible to play normal game through using editing tools to remove a black stone, then change turn to black and replay the move, after which white starts playing.

I have not looked deeply at the code, but based on release commits, at first sight this commit might be the reason why it is behaving differently now: https://github.com/SabakiHQ/Sabaki/commit/a50c0e734b66ede020985da17e00d50e3a8240da.

edit: seems to apply to human vs bot games only, if using "engine vs engine" option, it works as expected, but of course that's useless if you want to play against the bot :).

**Comment by yishn** [comment]
Yes, this is intended; you need to explicitly request a move now. Use 'Engines' > 'Generate Move' or <kbd>F10</kbd> to let the engine assigned to the current player generate a move.

**Comment by zelanter** [comment]
At first I thought of something like that but I guess I was looking in the wrong menu. It's a bit counterintuitive and not well documented from what I see., but oh well, now that I know I'm happy, thank you.
