### ISSUE TITLE
No chessboard displayed

### ISSUE THREAD

**Issue by WenJiaFu** [SabakiHQ/Sabaki#654]
After I update from 0.43.3 to 0.50.1, the chessboard will not be displayed on the interface after I start sabaki, and any menu keys will not respond. I've used a theme called submitted v2.0.0. Does that have anything to do with it? My operating system is win10

**Comment by yishn** [comment]
Please try using the default theme. You can also try resetting Sabaki by deleting the folder `%APPDATA%\Sabaki`.

**Comment by WenJiaFu** [comment]
Cool..it's worked
