### ISSUE TITLE
Local settings folder for portable app

### ISSUE THREAD

**Issue by ivysrono** [SabakiHQ/Sabaki#656]
After we reinstall the system, or when we use Sabaki between several different computers, we want a file to record the settings modified by the user. The content of this file is equal to settings.json, but has higher permissions. LizGoban, Firefox and other open source projects provide this feature.

**Comment by yishn** [comment]
Why not just use `settings.json`?

**Comment by ivysrono** [comment]
First, it can be modified once and used everywhere;
Second, settings.json may be modified during major version updates, and a separate user configuration file can avoid version conflicts.

**Comment by yishn** [comment]
`settings.json` can also be used everywhere. If there's need to modify settings during an upgrade, this would also have to affect your custom settings file.

**Comment by ivysrono** [comment]
emm, settings.json is hard to store and sync. Could we custom it's path?

**Comment by yishn** [comment]
How does Firefox support changing the settings path?

**Comment by ivysrono** [comment]
[User.js file - MozillaZine Knowledge Base](http://kb.mozillazine.org/User.js_file)
[1.1 Overview · ghacksuserjs/ghacks-user.js Wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview)

There are more disadvantages of direct sync `settings.json`:
As # 586 has not been resolved, users may need to customize the width and height, but their settings may not apply to another computer.

LizGoban support `[config.json](https://github.com/kaorahi/lizgoban#to-configure-it)` to set sth, for example, engines, path, and so on.

I would like to put `config.json` into the same folder as `sabaki-**-portable.exe`, to get realy `portable`.

**Comment by yishn** [comment]
Maybe for the portable version, say `path\to\sabaki-**-portable.exe`, we will resolve the settings folder as `path\to\sabaki-profile`, and for non-portable, it stays at `%APPDATA%\Sabaki`

**Comment by ivysrono** [comment]
IMO, it is ok.

**Comment by yishn** [comment]
Would you like to submit a PR? We set the setting folder path in [setting.js, line 7](https://github.com/SabakiHQ/Sabaki/blob/master/src/setting.js#L7).

**Comment by ivysrono** [comment]
I'll try the next few days.

**Comment by ivysrono** [comment]
> 
> 
> Would you like to submit a PR? We set the setting folder path in [setting.js, line 7](https://github.com/SabakiHQ/Sabaki/blob/master/src/setting.js#L7).

Why sabaki always use sync function?
Could we use async?
Or [node-fs-extra](https://github.com/jprichardson/node-fs-extra/blob/master/docs/outputFile.md) which is depended by electron?

**Comment by yishn** [comment]
Because we are not a server, we don’t need to serve multiple users at the same time, it’s not that critical to use async functions. Also, it simplifies control flow and removes the need to show a busy indicator in the UI.
