### ISSUE TITLE
Prisoners are added to the score of the wrong player.

### ISSUE THREAD

**Issue by acosmicjoke** [SabakiHQ/Sabaki#658]
![2020-03-16-183918_1920x1053_scrot](https://user-images.githubusercontent.com/51533695/76785633-160ed100-67b6-11ea-9315-ecaf3b6bf6eb.png)

See picture attached. I got this in the 0.50.1 release build.

**Comment by fohristiwhirl** [comment]
@yishn - Can I urge you to make a new release? Giving the wrong score is a very serious issue, that's bound to confuse players ([example](https://old.reddit.com/r/baduk/comments/ftkjx6/help_with_understanding_resignation_in_position/)).

**Comment by yishn** [comment]
You're right, I've released v0.51.0 just now.
