### ISSUE TITLE
when the game tree was going bigger, sabaki slowed down

### ISSUE THREAD

**Issue by lj739** [SabakiHQ/Sabaki#660]

**Comment by lj739** [comment]
This would never happened in sabaki0.43

**Comment by yishn** [comment]
Do you have an example file?

**Comment by lj739** [comment]
It exists  everywhere.  I usually load a katago engine as a black player and meanwhile a white player, turning on analynasing and turning off winrate,  then using genmove to play as black or white myself. Because analying was turned on, engine generate a move very fast just like pondering was turned on. When the game was going on to about one hundred moves the sabaki interface interaction becames very slow.

**Comment by lj739** [comment]
When two engines were loaded, if you interacted with it , as the game going on tp 100 moves around, sabaki interface interaction becames very slow as well, especially at game end (200 moves around).

**Comment by lj739** [comment]
When two engines were loaded, if you interacte with it , as the game going on to 100 moves around, sabaki interface interaction becomes very slow as well, especially at game end (200 moves around).

**Comment by yishn** [comment]
Again, do you have an example file? Additionally, does Sabaki slow down if you stop the engine?

**Comment by lj739** [comment]
stop engine won't help

**Comment by lj739** [comment]
You can have a try, big game tree won't  inevitably slow down the interface, maybe interacting with engines slow down the interface.

**Comment by yishn** [comment]
Can you try opening the Kogo's Joseki Dictionary and see if it slows down for you?

**Comment by lj739** [comment]
I can open a 2.5mb sgf file  to broswe it without slowing down

**Comment by lj739** [comment]
I'm wondering that it is the engine cache file slowed down the interface.  I use katago's clear_cache command in gtp console, but it doesn't work.

**Comment by yishn** [comment]
Seems like engines are competing with Sabaki for resources, I don’t think that’s something we can fix anything on our side.
