### ISSUE TITLE
Sabaki 50.1 Hangs when Loading Some SGF Files

### ISSUE THREAD

**Issue by MacErlang** [SabakiHQ/Sabaki#663]
Hello,

I am attaching four sgf files that I downloaded from the web. The current version of Sabaki hangs
when I tried to load any of these files. However, all of these files open just fine in Sabaki 35.1. There are other files with similar issues. Possible bugs?

Best,
Shun

[Test Files.zip](https://github.com/SabakiHQ/Sabaki/files/4346399/Test.Files.zip)

**Comment by MacErlang** [comment]
Extra spaces or empty lines in the file might have something to do with this issue.

**Comment by yishn** [comment]
The hanging of the file `珍珑棋局-1200手 - Original.sgf` is of particular interest here: We use recursive functions to process all the nodes in a game tree and for some reason we hit the maximum stack size with `gametree.getHeight()` even though the game tree "only" has 3603 moves with no variations whatsoever. Furthermore, it seems the game tree object of that file is so big that `JSON.stringify()` also hits the maximum stack size. This is now fixed.

**Comment by MacErlang** [comment]
@yishn WOW, thank you.
