### ISSUE TITLE
Move Numbering and Markup Cannot Coexist?

### ISSUE THREAD

**Issue by MacErlang** [SabakiHQ/Sabaki#666]
The attached file has markups/labels like A, B, .... However, when "Show Move Numbers" are
enabled, these labels all disappear. Can they not coexist?

Best,
Shun

[5-1 点三三 - 星小飞尖.sgf.zip](https://github.com/SabakiHQ/Sabaki/files/4349935/5-1.-.sgf.zip)

**Comment by yishn** [comment]
No, they cannot.

**Comment by MacErlang** [comment]
Can this be an enhancement, if technically possible? One can of course keep toggling
"Show Move Numbers", but that seems tedious. If a markup is on a stone, could it overlay with
the number for that stone?

**Comment by yishn** [comment]
No, it can't overlay. Not only is it technically not possible, the number would also be unreadable. I recommend just disabling move numbers. There's no good reason to show them anyway.
