### ISSUE TITLE
When game.navigation_analysis_delay is small, the analysis result will not be displayed

### ISSUE THREAD

**Issue by ebifrier** [SabakiHQ/Sabaki#669]
In the analysis mode, when the value of game.navigation_analysis_delay is small and navigation is performed quickly (for example, if you repeat make move / undo), the result will not be displayed.
This error occurs when game.navigation_analysis_delay is less than about 100 in my environment.

**Comment by yishn** [comment]
We're not supporting custom settings that are not configurable through the UI. Custom settings always comes with the risk that it might break Sabaki.
