### ISSUE TITLE
Windows defender detected a trojan in 0.51.0 setup file

### ISSUE THREAD

**Issue by isty2e** [SabakiHQ/Sabaki#679]
It claims that [Trojan:Win32/Fuery.C!cl](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fFuery.C!cl&threatid=2147718736) is detected. It could be a false positive, but does anybody experience the same?

**Comment by moonewxp** [comment]
the same trojan

**Comment by yishn** [comment]
Please report it as a false positive whenever possible. We don't have any control over Antivirus software.
