### ISSUE TITLE
Hi. The Windows 64 bit executable won't install on my Windows 10 machine because windows insists it contains a virus or other unwanted software. Apparently no option to override it.

### ISSUE THREAD

**Issue by jrf1968** [SabakiHQ/Sabaki#682]

**Comment by VojMi** [comment]
The same issue here. It was classified as "**Win32/Unwaders.A!ml**"
https://malwarefixes.com/threats/adwarewin32-unwaders-aml/

**Comment by yishn** [comment]
You can [exclude files or folders from Windows Defender scans](https://www.windowscentral.com/how-exclude-files-and-folders-windows-defender-antivirus-scans).

**Comment by mute2120** [comment]
So the program is not going to be updated to remove the trojan, instead you are suggesting hard bypassing antivirus and allowing it to install?
