### ISSUE TITLE
Download of newest version of Sabaki doesn't work

### ISSUE THREAD

**Issue by MC1306** [SabakiHQ/Sabaki#685]
When I click on update, the window closes and nothing happens.

**Comment by Vandertic** [comment]
I confirm this. The 64 bit installer is marked as virus under Windows 10 and Chrome download. Don't know if it's one or the other.
![image](https://user-images.githubusercontent.com/27057329/78807717-bd051800-79c4-11ea-9b34-d25daea10d36.png)

**Comment by yishn** [comment]
Please report it as a false positive whenever possible. We don't have any control over Antivirus software.
