### ISSUE TITLE
Windows 10 report Virus detected and refuse to execute

### ISSUE THREAD

**Issue by yauwing** [SabakiHQ/Sabaki#686]
Tried to download sakaki-v0.51.0-win-x64-setup.exe on Windows 10 but failed,  Windows 10 reported Couldn't download - Virus detected

Downloaded on a Mac (my Mac is not as fast as my PC) and tried to execute. Windows 10 refused to execute saying virus or unwanted software detected.

Is there a safe way to get around?

**Comment by yishn** [comment]
You could make an exception for Sabaki in your anti-virus software. Please report it as a false positive whenever possible. We don't have any control over Antivirus software.
