### ISSUE TITLE
Unreadable SGF file

### ISSUE THREAD

**Issue by sudosandwich** [SabakiHQ/Sabaki#687]
I am not sure how I would debug that (I am a C++ developer) but the attached SGF cannot be parsed.
[x.sgf.txt](https://github.com/SabakiHQ/Sabaki/files/4461207/x.sgf.txt)

**Comment by yishn** [comment]
There is a syntax error in your SGF at line 1, column 297:

~~~
…US[Matsuyama[3d]]…
~~~

needs to be

~~~
…US[Matsuyama[3d\]]…
~~~
