### ISSUE TITLE
win32-x64 release v0.51.0 seems to be compromised

### ISSUE THREAD

**Issue by avysk** [SabakiHQ/Sabaki#691]
1. Windows Defender removes the file immediately after download, claiming that it is infected.
2. Windows Defender is happy with the very same installer if I build it from the source.
3. Here is the scan result for the release provided here: https://www.virustotal.com/gui/file/7d7bb2a9900a00bf19323b9d1239282bdd21bffbb623e530c4e7631478615bfb/detection
4. Here is the scan result for self-built release: https://www.virustotal.com/gui/file/ee9b380dcbc0e3cbd2cb5bffb7204bc3e55144ca479e385870dfd480674f9475/detection

Notice the obvious difference: it's not just "false positive", it's different results for the locally built installer and what's here.

And no, "go build the release yourself if you don't trust it" is not a good way to close such tickets.

**Comment by yishn** [comment]
So what is your proposed solution then? I'm automating the [release creation with GitHub Actions](https://github.com/SabakiHQ/Sabaki/blob/master/.github/workflows/create-release.yml). I can release 7z archives instead of installers for Windows in the future.

The different hash you're getting for your local build can be explained in several ways, for example different dependency versions or builds are based on different commits.

**Comment by avysk** [comment]
Of course I am not talking about different hash, but rather about different views antivirus engines have on the file.

Can you reproduce my results locally? Can you re-trigger GitHub actions and check if it's reproducible as well (could it be that it pulled in some vulnerable dependency via `npm` which is now updated to a fixed version)? Is there a way to see which versions npm pulled in exactly during the build? Can you add `npm audit` step into the automated build?

After all, the previous releases of Sabaki didn't trigger the warning.

**Comment by avysk** [comment]
You see, the whole point of having Windows release is to provide an easy installer for the people who have no skills to compile the stuff for themselves -- and those people won't be able even download the installer, because it is immediately removed by Windows Defender (it's not a matter of just "wait, I don't like this file", it's "by the way, I've deleted this file").

**Comment by yishn** [comment]
It seems the newer v0.51.1 release [triggers less false positives](https://www.virustotal.com/gui/file/463bb5adc78182a2acac36f5dd0f6c0d38fdd710d50983b74f9a9d5a3f21cdee/detection).

**Comment by avysk** [comment]
Yes, it is the same as my local build now.

**Comment by GopherAl** [comment]
Actually Avast Antivirus, for one, is even more unhappy with v0.51.1 than with the earlier releases. Speaking with absolutely no knowledge of how these things work, **it may be related to GitHub Actions**, as referred to by @avysk. I had the same warning re infection with Win32:Malware-gen when installing the latest LizGoban 2 days ago as is occurring now with Sabaki. I'm having more trouble than ever with installing this release.

It would be greatly welcomed by me and other non-technical folk if this could be followed up and remedied.

![image](https://user-images.githubusercontent.com/47664082/79097055-1fce2900-7da2-11ea-9571-1eb4ca3aa3c3.png)

**Comment by tealv** [comment]
Why is this issue closed? It is still an issue. How am I supposed to know if the malware is a false positive or not. I will try compiling it myself, but I agree with Avsk that it is not a solution to the issue.
