### ISSUE TITLE
Portable version can't load katago

### ISSUE THREAD

**Issue by lj739** [SabakiHQ/Sabaki#692]

**Comment by ebifrier** [comment]
Could you try specifying all the paths for KataGO executables, configs, etc. with absolute paths?

**Comment by yishn** [comment]
@lj739  Please provide more information.

**Comment by lj739** [comment]
{
  "app.always_show_result": false,
  "app.enable_hardware_acceleration": true,
  "app.hide_busy_delay": 200,
  "app.lang": "zh-Hans",
  "app.loadgame_delay": 100,
  "app.startup_check_updates": true,
  "app.startup_check_updates_delay": 3000,
  "app.zoom_factor": 1,
  "autoplay.max_sec_per_move": 99,
  "autoplay.sec_per_move": 1,
  "autoscroll.delay": 400,
  "autoscroll.diff": 10,
  "autoscroll.max_interval": 200,
  "autoscroll.min_interval": 50,
  "board.analysis_interval": 50,
  "board.analysis_type": "scoreLead",
  "board.show_analysis": true,
  "board.variation_replay_interval": 500,
  "board.variation_replay_mode": "move_by_move",
  "cleanmarkup.annotations": false,
  "cleanmarkup.arrow": true,
  "cleanmarkup.circle": true,
  "cleanmarkup.comments": false,
  "cleanmarkup.cross": true,
  "cleanmarkup.hotspots": false,
  "cleanmarkup.label": true,
  "cleanmarkup.line": true,
  "cleanmarkup.square": true,
  "cleanmarkup.triangle": true,
  "cleanmarkup.winrate": false,
  "comments.commit_delay": 500,
  "comments.show_move_interpretation": true,
  "console.max_history_count": 1000,
  "debug.dev_tools": true,
  "edit.click_currentvertex_to_remove": true,
  "edit.copy_variation_strip_props": [
    "AP",
    "CA",
    "FF",
    "GM",
    "ST",
    "SZ",
    "KM",
    "HA",
    "AN",
    "BR",
    "BT",
    "CP",
    "DT",
    "EV",
    "GN",
    "GC",
    "ON",
    "OT",
    "PB",
    "PC",
    "PW",
    "RE",
    "RO",
    "RU",
    "SO",
    "TM",
    "US",
    "WR",
    "WT"
  ],
  "edit.flatten_inherit_root_props": [
    "BR",
    "BT",
    "DT",
    "EV",
    "GN",
    "GC",
    "PB",
    "PW",
    "RE",
    "SO",
    "SZ",
    "WT",
    "WR"
  ],
  "edit.history_batch_interval": 500,
  "edit.max_history_count": 1000,
  "edit.show_removenode_warning": true,
  "edit.show_removeothervariations_warning": true,
  "engines.analyze_commands": [
    "analyze",
    "kata-analyze",
    "lz-analyze"
  ],
  "engines.gemove_analyze_commands": [
    "genmove_analyze",
    "kata-genmove_analyze",
    "lz-genmove_analyze"
  ],
  "engines.list": [
    {
      "name": "kata20",
      "path": "engine/katago/katago.exe",
      "args": "-g -model engine/katago/g170e-b20c256x2-s2971705856-d633407024.bin.gz -config engine/katago/gtp_example.cfg"
    }   
  ],
  "file.show_reload_warning": true,
  "find.delay": 100,
  "game.default_board_size": "19:19",
  "game.default_handicap": 0,
  "game.default_komi": 7.5,
  "game.goto_end_after_loading": false,
  "game.navigation_analysis_delay": 500,
  "game.navigation_sensitivity": 40,
  "game.show_ko_warning": true,
  "game.show_suicide_warning": true,
  "gamechooser.show_delay": 100,
  "gamechooser.thumbnail_size": 153,
  "graph.delay": 100,
  "graph.grid_size": 22,
  "graph.node_size": 4,
  "gtp.console_log_enabled": false,
  "gtp.console_log_path": null,
  "gtp.engine_quit_timeout": 3000,
  "gtp.move_delay": 300,
  "infooverlay.duration": 2000,
  "score.estimator_iterations": 100,
  "scoring.method": "territory",
  "setting.overwrite.v0.19.1": [],
  "setting.overwrite.v0.19.3": [],
  "setting.overwrite.v0.30.0-beta": [],
  "setting.overwrite.v0.33.0": [],
  "setting.overwrite.v0.33.4": [],
  "setting.overwrite.v0.41.0": [],
  "setting.overwrite.v0.43.3_4": [],
  "setting.overwrite.v0.50.1": [],
  "sgf.comment_properties": [
    "C",
    "N",
    "UC",
    "GW",
    "DM",
    "GB",
    "BM",
    "TE",
    "DO",
    "IT"
  ],
  "sgf.format_code": false,
  "sound.capture_delay_max": 500,
  "sound.capture_delay_min": 300,
  "sound.enable": true,
  "theme.current": null,
  "theme.custom_background": null,
  "theme.custom_blackstones": null,
  "theme.custom_board": null,
  "theme.custom_whitestones": null,
  "view.animated_stone_placement": true,
  "view.coordinates_type": "A1",
  "view.fuzzy_stone_placement": false,
  "view.leftsidebar_minwidth": 100,
  "view.leftsidebar_width": 250,
  "view.peerlist_height": 130,
  "view.peerlist_minheight": 58,
  "view.properties_height": 50,
  "view.properties_minheight": 20,
  "view.show_comments": true,
  "view.show_coordinates": false,
  "view.show_graph": true,
  "view.show_leftsidebar": true,
  "view.show_menubar": true,
  "view.show_move_colorization": true,
  "view.show_move_numbers": false,
  "view.show_next_moves": true,
  "view.show_siblings": true,
  "view.show_winrategraph": true,
  "view.sidebar_minwidth": 100,
  "view.sidebar_width": 200,
  "view.winrategraph_blunderthreshold": 5,
  "view.winrategraph_height": 90,
  "view.winrategraph_invert": true,
  "view.winrategraph_maxheight": 250,
  "view.winrategraph_minheight": 30,
  "window.height": 1137,
  "window.maximized": true,
  "window.minheight": 440,
  "window.minwidth": 526,
  "window.width": 2064
}

**Comment by lj739** [comment]
[2020-04-14 15:07:32.426] <kata20>    (in) : name
[2020-04-14 15:07:32.436] <kata20>    (in) : version
[2020-04-14 15:07:32.438] <kata20>    (in) : protocol_version
[2020-04-14 15:07:32.440] <kata20>    (in) : list_commands
[2020-04-14 15:07:32.441] <kata20>  (meta) : Engine Started
[2020-04-14 15:07:32.498] <kata20>  (meta) : Connection Failed
[2020-04-14 15:07:32.499] <kata20>  (meta) : Connection Failed
[2020-04-14 15:07:32.500] <kata20>  (meta) : Connection Failed
[2020-04-14 15:07:32.501] <kata20>  (meta) : Connection Failed

**Comment by yishn** [comment]
The `args` paths need to be relative to the path specified in `path`. Can you try:

~~~
-g -model g170e-b20c256x2-s2971705856-d633407024.bin.gz -config gtp_example.cfg
~~~

**Comment by lj739** [comment]
thanks. problem solved.
