### ISSUE TITLE
Engines do not honor system paths on Linux

### ISSUE THREAD

**Issue by skatbude** [SabakiHQ/Sabaki#695]
I use ssh to run my engines remotely on a more powerful machine.

For v0.43.3 and v0.50.0 I used "ssh" as my engine, works fine.
For v0.51.1 "ssh" doesn't work anymore, "/usr/bin/ssh" has to be specified.

Basically this is the same problem as pointed out in [issue 117](https://github.com/SabakiHQ/Sabaki/issues/117).

Sabaki version: v0.51.1
OS: Linux (SparkyLinux based on Debian testing branch, Kernel 5.6.0)

I think the issue has been introduced in [this commit](https://github.com/SabakiHQ/Sabaki/commit/f9bd1f30f63bd631064aff9f32f2d82a24491ac1).

**Comment by yishn** [comment]
Thanks for the investigation! You're right about the commit that caused this, but unfortunately, it is needed to make relative paths work on the portable version. I'm not sure how to resolve this properly...

**Comment by skatbude** [comment]
The problem apparently is that

> If no path segments are passed, path.resolve() will return the absolute path of the current working directory [1].

Indeed "ssh" works if I execute Sabaki from "/usr/bin".

Maybe it's possible to use the "shell" spawn option (in conjunction with the already apparent "cwd") [2]. This should pass all name resolution duties over to the shell.

[1] [https://nodejs.org/api/path.html#path_path_resolve_paths](https://nodejs.org/api/path.html#path_path_resolve_paths)
[2] [https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)

**Comment by yishn** [comment]
This won't really solve the problem. In the portable version, if we don't have an explicit filename resolution, relative paths to engines don't work (relative to Sabaki path).

**Comment by ebifrier** [comment]
One idea is to use the absolute path of a given executable file if it exists, and to to the path as is if the file does not exist.

**Comment by yishn** [comment]
Sounds sensible; the only problem I see is that the file extension can't be omitted for relative paths, but that is probably just a minor detail and only affects Windows.

**Comment by ebifrier** [comment]
Another idea is to call spawn in the relative path, and if it fails, call spawn again in the absolute path. But we need to write a little dirty code to determine that an error occurred due to spawn specification problem. I think a simpler way would be better, and if the path is relative, it's the specification that even the extension has to be matched.

I've written the code. Can I PR it?

**Comment by yishn** [comment]
Sounds good, please do 😊
