### ISSUE TITLE
Trouble attaching engines on MacOS

### ISSUE THREAD

**Issue by standstill100** [SabakiHQ/Sabaki#701]
Hi there! 

I'm having trouble getting GNUGo attached to Sabaki as an engine. (Or any attaching any engine for that matter.)

I haven't compiled anything I've downloaded and don't know how, but I have Xcode. Sorry if that's the problem and is a simple solution, haha.

When I run GNUGo in Terminal, it works fine. I downloaded their most recent universal binary.

I've tried pointing the path to different areas of the GNUGo folder I downloaded:

<img width="435" alt="Screen Shot 2020-04-21 at 6 53 55 PM" src="https://user-images.githubusercontent.com/64065953/79932108-93ef7900-8401-11ea-88c9-a370a38f6e4b.png">
<img width="326" alt="Screen Shot 2020-04-21 at 6 54 00 PM" src="https://user-images.githubusercontent.com/64065953/79932109-94880f80-8401-11ea-99ae-cd1c58ac120d.png">
<img width="385" alt="Screen Shot 2020-04-21 at 6 54 04 PM" src="https://user-images.githubusercontent.com/64065953/79932110-9520a600-8401-11ea-9b5d-4ee1aa42747d.png">

Once I've "added" an engine I always get this on the sidebar:
<img width="243" alt="Screen Shot 2020-04-21 at 6 40 05 PM" src="https://user-images.githubusercontent.com/64065953/79931282-8638f400-83ff-11ea-8670-bcab64a3fbc9.png">

Nothing ever connects. When I try to start a game with the engines, the little arrow next to the engine turns red. Does that mean there's an issue?

<img width="258" alt="Screen Shot 2020-04-21 at 7 24 50 PM" src="https://user-images.githubusercontent.com/64065953/79933790-d4e98c80-8405-11ea-8d75-ec0782ec7383.png">

I'm sure the solution is simple and obvious for anyone else on GitHub, haha. Appreciate the help in advance!

**Comment by MacErlang** [comment]
You need to point (in Sabaki) to the executable program gnugo, not a folder.
I believe the executable is located in /usr/local/bin after compilation. You can of course
move this file to a different location. If you did not compile yourself, just try to locate
the gnugo program and point to it.

**Comment by standstill100** [comment]
Thank you so much for the response and patience with the simple question!

I should have been clear: I believe I found the executable program gnugo. It says "unix exectuable" and when I run it in Terminal it works perfectly as a Go bot.

I've tried to point Sabaki to this program but it's greyed out in the "find path" finder. When I just type it in manually it never seems to catch or connect.

<img width="153" alt="Screen Shot 2020-04-22 at 10 57 49 AM" src="https://user-images.githubusercontent.com/64065953/80016595-29cde700-8488-11ea-8341-8233be0f6881.png">

Also when I do that I get this little "!" symbol to remind me I'm doing everything wrong, haha.

<img width="61" alt="Screen Shot 2020-04-22 at 10 57 06 AM" src="https://user-images.githubusercontent.com/64065953/80016600-2dfa0480-8488-11ea-862a-3d47928075c0.png">

Is that the executable program? Is there a problem with how I'm pointing to it?

<img width="148" alt="Screen Shot 2020-04-22 at 10 55 34 AM" src="https://user-images.githubusercontent.com/64065953/80016630-39e5c680-8488-11ea-897a-07d54836124f.png">
<img width="279" alt="Screen Shot 2020-04-22 at 10 56 10 AM" src="https://user-images.githubusercontent.com/64065953/80016634-3a7e5d00-8488-11ea-85ea-fece50ae6174.png">


So appreciate all the help. And sorry again. Can't wait to use this thing, haha

**Comment by vanfaktor** [comment]
> Hi there!
> 
> I'm having trouble getting GNUGo attached to Sabaki as an engine. (Or any attaching any engine for that matter.)
> 
> I haven't compiled anything I've downloaded and don't know how, but I have Xcode. Sorry if that's the problem and is a simple solution, haha.
> 
> When I run GNUGo in Terminal, it works fine. I downloaded their most recent universal binary.
> 
> I've tried pointing the path to different areas of the GNUGo folder I downloaded:
> 
> <img alt="Screen Shot 2020-04-21 at 6 53 55 PM" width="435" src="https://user-images.githubusercontent.com/64065953/79932108-93ef7900-8401-11ea-88c9-a370a38f6e4b.png">
> 
> <img alt="Screen Shot 2020-04-21 at 6 54 00 PM" width="326" src="https://user-images.githubusercontent.com/64065953/79932109-94880f80-8401-11ea-99ae-cd1c58ac120d.png">
> 
> <img alt="Screen Shot 2020-04-21 at 6 54 04 PM" width="385" src="https://user-images.githubusercontent.com/64065953/79932110-9520a600-8401-11ea-9b5d-4ee1aa42747d.png">
> 
> Once I've "added" an engine I always get this on the sidebar:
> <img alt="Screen Shot 2020-04-21 at 6 40 05 PM" width="243" src="https://user-images.githubusercontent.com/64065953/79931282-8638f400-83ff-11ea-8670-bcab64a3fbc9.png">
> 
> Nothing ever connects. When I try to start a game with the engines, the little arrow next to the engine turns red. Does that mean there's an issue?
> 
> <img alt="Screen Shot 2020-04-21 at 7 24 50 PM" width="258" src="https://user-images.githubusercontent.com/64065953/79933790-d4e98c80-8405-11ea-8d75-ec0782ec7383.png">
> 
> I'm sure the solution is simple and obvious for anyone else on GitHub, haha. Appreciate the help in advance!

Hi! I've solved it by adding "--mode gtp --level 5", so now it's looking like that: 
<img width="676" alt="Screenshot 2020-06-05 at 18 26 36" src="https://user-images.githubusercontent.com/66487988/83905813-3bc6c900-a75a-11ea-8247-6126ec063e14.png">
I've installed GnuGo through brew and added it to Sabaki by navigating to /usr/local/bin/.
I've already tried a few games and it's working perfectly fine. Even engine vs engine games are working. 

The only problem that left it's Sabaki not quitting correctly. I have to force quit it every time.

**Comment by standstill100** [comment]
That's it! It works perfectly! You're the best. I can't thank you enough. It's perfect. I was totally lost! 

(And I've had that problem with quitting Sabaki as well. I usually just tap cmd-q twice and it works, haha)
