### ISSUE TITLE
Window mode does not scale properly to screen resolution

### ISSUE THREAD

**Issue by langmeister** [SabakiHQ/Sabaki#702]
On smaller displays (480px vertical resolution), the bottom of the window is cut off, and does not allow resizing using window controls. 

Full screen is fine.

**Comment by yishn** [comment]
Can you provide more information, such as your OS and a screenshot or a video.

**Comment by langmeister** [comment]
Screenshot will be difficult. OS is raspbian (raspberry pi) running bare-bones Pixel desktop at a resolution of 720x480.

**Comment by yishn** [comment]
Try adjusting the `window.height` and `window.minheight` settings in your `settings.json` that is located in `$XDG_CONFIG_HOME/Sabaki` or `~/.config/Sabaki`.

**Comment by langmeister** [comment]
That was easy - thank you.
