### ISSUE TITLE
macOS: "PageUp" and "PageDown" menu item shortcut indicators are visually too similar to "Up" and "Down"

### ISSUE THREAD

**Issue by GoGameSpace** [SabakiHQ/Sabaki#704]
See the attached screenshot of the "Navigation" menu. It took me a long time to realize that these are different shortcuts and not the same shortcut used for two items.

Also when using a shortcut like "CmdOrCtrl+Shift+1" renders as "⌘!", not as "⌘⇧1". This is just a minor thing, but I find "⌘⇧1" clearer than "⌘!".

But I guess that the way this is drawn is due to Electron and not Sabaki.

<img width="261" alt="sabaki-navigation-menu-shortcuts" src="https://user-images.githubusercontent.com/60425018/80763099-11239800-8b3e-11ea-944c-fa851b94ee0e.png">

**Comment by yishn** [comment]
Yes, please open an issue for Electron.
