### ISSUE TITLE
Cannot load the sgf file with over 3000 moves

### ISSUE THREAD

**Issue by Dreamkeeper66666** [SabakiHQ/Sabaki#709]
Hi! I just happened to find a game with 3600 moves in it. It turns out that Sabaki was not able to open it. Instead I opened it with multigo and it worked. So I am wondering if there is some limitation in Sabaki like maximum move or something? Thanks a lot!

**Comment by yishn** [comment]
No, there's no explicit limitation in Sabaki like this. Maybe you can share your SGF?

**Comment by Dreamkeeper66666** [comment]
Here is the link to the sgf file: http://gokifu.com/f/358e.sgf. Thanks!

**Comment by Dreamkeeper66666** [comment]
> No, there's no explicit limitation in Sabaki like this. Maybe you can share your SGF?

Here is the link to the sgf file: http://gokifu.com/f/358e.sgf. Thanks!

**Comment by Dreamkeeper66666** [comment]
By the way, it would be great if autoplay speed can be set as some decimal numbers like 0.1 s/move. Although it's not common, it will take an hour to autoplay the whole game with 3600 moves in it.

**Comment by cryptpark** [comment]
This sgf opens SmartGo. and there is autoplay 0.1 s and faster. reminded Conway's Game of Life. where is it from? funny i recently did something similar

**Comment by ebifrier** [comment]
In my environment, that sgf file can be load with almost no lag. Could you tell me the version of Sabaki and what OS you are running?
Also, Sabaki's sgf reading has been much improved since v0.51.0, so if you have an older version, please try the new one.

Certainly it looks like Conway's Game of Life. lol

**Comment by Dreamkeeper66666** [comment]
> This sgf opens SmartGo. and there is autoplay 0.1 s and faster. reminded Conway's Game of Life. where is it from? funny i recently did something similar

This is considered to be the longest Tsumego so far. The author is 森长宏明( Chinese name)
Here is the link: https://www.101weiqi.com/book/30485/0/41011/

**Comment by Dreamkeeper66666** [comment]
> In my environment, that sgf file can be load with almost no lag. Could you tell me the version of Sabaki and what OS you are running?
> Also, Sabaki's sgf reading has been much improved since v0.51.0, so if you have an older version, please try the new one.
> 
> Certainly it looks like Conway's Game of Life. lol

Thanks, I just downloaded the latest version of Sabaki and it worked.
