### ISSUE TITLE
Sabaki gets slow when console gets full

### ISSUE THREAD

**Issue by tterava** [SabakiHQ/Sabaki#716]
If you have Engines Sidebar open, after a while when enough text has accumulated, there will be a very noticeable delay when placing new stones. Probably 1-2 seconds after clicking the board before the new move is registered. This also affects engine vs. engine play and makes it slower.

Right clicking the console and clearing it fixes the issue until the console gets full again.

**Comment by yishn** [comment]
We're currently limiting the log entries to 1000. Maybe that's still too high? You can try lowering the value in `settings.json` for the key `console.max_history_count` and see what value works for you. Then we can also adjust the default setting.

Locate the file in:

   - `%APPDATA%\Sabaki` on Windows
   - `$XDG_CONFIG_HOME/Sabaki` or `~/.config/Sabaki` on Linux
   - `~/Library/Application Support/Sabaki` on macOS

**Comment by tterava** [comment]
Lowering the setting to some 50 seemed to do the trick. I guess the value corresponds to the number of log entries instead of just a raw row count. Even with 50 it still maintains a fair amount of log which is sufficient for my needs.
