### ISSUE TITLE
Embedding engine analysis in SGF

### ISSUE THREAD

**Issue by hadim** [SabakiHQ/Sabaki#717]
Is that possible to embed the engine's analysis results in the SGF so it can be "replayed" without having to attach an engine?

The other use would be to generate the analysis using other tools that Sabaki (for example a command-line tool that run analysis on SGF batches) to generate analysis.

Is that something Sabaki could support if this is possible considering the SGF format of course?

**Comment by yishn** [comment]
Not a big fan of this, to be honest. Analysis is designed to be ephemeral, to persist analysis variations, use the 'Add Variation' feature.
