### ISSUE TITLE
Feature request: Shift Left & Shift Right repeat facility

### ISSUE THREAD

**Issue by GopherAl** [SabakiHQ/Sabaki#718]
I often wish to move a variation many positions to the left or right in the game tree. It is tedious to have to look for the new position of the relevant node and then have to reselect Shift Left (or Right) from the mouse Right Click menu.

I suggest what is hopefully a fairly simple solution - add some code to redisplay the node (in its new position) with "Shift Left" (or Right) displayed each time the user clicks on it. (For example, the user clicks ""Shift Left", the node is shifted left one position in the game tree, and the Game Tree updates to show the node in its new position with "Shift Left" displayed, ready for action, in the drop-down menu.) Then the user simply has to keep clicking on it until the variation has arrived at the desired position in the game tree.

This will also require the display of the game tree to update, with each click on Shift Left/Right, to show the selected node in its new position. The cursor would have to track (be "glued to") the "Left Click" or "Right Click" option in the menu as it redisplays. The user turns this operation off by moving the cursor off the menu display, as usual (or clicking elsewhere on the screen).

![image](https://user-images.githubusercontent.com/47664082/82670411-6d329580-9c80-11ea-9d9d-b7b2e53826df.png)

**Comment by yishn** [comment]
Sorry, this is simply technically not possible using the Electron framework.
