### ISSUE TITLE
Restart Analysis?

### ISSUE THREAD

**Issue by romulusmare** [SabakiHQ/Sabaki#726]
If I use any engine and set it as analyzer, then stop the engine, is it possible in anyway to restart it and show the heatmap again? If I press stop, then press start no heatmap is displayed. Also synchronize almost never works. It either crashes, or most probably does nothing.

**Comment by apetresc** [comment]
In what way are you "stopping the engine"? Detaching it or just toggling analysis mode?

If you detach the engine, the process exits and it's state is lost, nothing Sabaki can do about that. But toggling analysis on/off already works and resumes fine. Please re-open and explain if something unexpected is happening 🙂
