### ISSUE TITLE
How to configure a remote engine?

### ISSUE THREAD

**Issue by dinohsu1019** [SabakiHQ/Sabaki#728]
If I want to configure a remote engine for sabaki (Lizzie is ok), are the following fields filled correctly?

Name: lz270
Path: C:/Program Files/PuTTY/plink.exe -ssh -pw pp uu@iiii C:/leela-zero-0.17-win64/leelaz.exe
Parameters: -g -b 0 -w C:/leela-zero-0.17-win64/lz270.gz
Initial Commands: (empty)

Please shed some light on me, thanks in advance.

**Comment by yishn** [comment]
No, everything after `plink.exe` in "Path" need to go into "Parameters"

**Comment by dinohsu1019** [comment]
First success with remote engine, will continue to test functionalities, thanks. 

![image](https://user-images.githubusercontent.com/30600848/89655087-286fdf80-d8fc-11ea-8479-8171f577cd98.png)
