### ISSUE TITLE
What are the top move playouts or time limits in an engine vs. engine game?

### ISSUE THREAD

**Issue by dinohsu1019** [SabakiHQ/Sabaki#733]
The following screenshot is the game between Leela Zero 275 vs. 268 (remote engines), I have no control over the top move playouts or time limits, what are they in this case? Thanks in advance. 

![image](https://user-images.githubusercontent.com/30600848/89712645-c333f100-d9c4-11ea-81a7-5efd7a4fecb0.png)

**Comment by yishn** [comment]
Use GTP commands and/or command line arguments to configure your engine.
