### ISSUE TITLE
How the Handicap Match Begins

### ISSUE THREAD

**Issue by kusumotonorio** [SabakiHQ/Sabaki#736]
When I play a handicap match with black as myself and white as a computer such as Leeza Zero, white will not move automatically until after the handicap stone is placed, white's stone is placed manually and then my black stone is placed again.

When I play a handicap match on Leela, which has its own GUI, the computer places the white stone on the board with the handicap stone on it and the game starts. This is different from what happens in Sabaki, and it feels right to me.

Am I setting things up wrong?

**Comment by yishn** [comment]
Attaching engines won't start the game automatically anymore, because people wanted it to behave like Lizzie IIRC. Press <kbd>F10</kbd> to generate a move from an attached engine.
