### ISSUE TITLE
Entry in menu or shortcut to quit sabaki

### ISSUE THREAD

**Issue by rekstein** [SabakiHQ/Sabaki#741]
Hi there,

First of all, thank you all for this great piece of software. Sabaki is neat and fantastic.

As I use a tiling window manager in GNU/Linux (i3wm) without UI border (ie. without a cross in an upper corner to close the window), I can't close Sabaki via a menu entry or a shortcut (ex. ctrl+w or alt+F4).
Thus I have to directly kill the Sabaki process. It's not really clean and convenient.
It would be great if quitting will be possible directly from Sabaki itself and not by killing its process or it's window.

Thank you by advance!
Regards,

**Comment by yishn** [comment]
Does your tiling window manager not have a shortcut to close windows? Normally, <kbd>Alt+F4</kbd> closes a window as implemented by the OS.

**Comment by rekstein** [comment]
@yishn 
Unfortunately none of the classic shortcuts (ie. ctrl+w ; ctrl+q ; ctrl+x ; ctrl+c ; ctrl+z ; alt+F4 etc.) work with Sabaki.
They work with other applications but not with Sabaki.
 when I list processes related to Sabaki I have :  
`
F S UID          PID    PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S myname      1481    1478  9  80   0 - 159623 -     16:58 ?        00:00:00 /tmp/.mount_sabakiFVtE3c/sabaki
1 S myname      1484       1 13  80   0 -  2903 -      16:58 ?        00:00:01 sabaki
4 S myname      1489    1481  0  80   0 - 48083 -      16:58 ?        00:00:00 /tmp/.mount_sabakiFVtE3c/sabaki --type=zygote
1 S myname      1491    1489  0  80   0 - 48083 -      16:58 ?        00:00:00 /tmp/.mount_sabakiFVtE3c/sabaki --type=zygote
0 S myname      1514    1481  2  80   0 - 84831 -      16:58 ?        00:00:00 /tmp/.mount_sabakiFVtE3c/sabaki --type=gpu-process --field-trial-handle=641201844416698950,1
0 S myname      1526    1481  1  80   0 - 63070 -      16:58 ?        00:00:00 /tmp/.mount_sabakiFVtE3c/sabaki --type=utility --field-trial-handle=641201844416698950,15696
0 S myname      1534    1481 13  80   0 - 2774226 -    16:58 ?        00:00:01 /tmp/.mount_sabakiFVtE3c/sabaki --type=renderer --field-trial-handle=641201844416698950,1569
0 S myname      1556    1481  0  80   0 - 126859 -     16:58 ?        00:00:00 /tmp/.mount_sabakiFVtE3c/sabaki --type=utility --field-trial-handle=641201844416698950,15696
`
This when I launch a single instance of Sabaki.
This I have to kill the firts one (PID 1481 in this case) and not the second one which is called simply 'sabaki' (PID 1484 in this case), maybe it is the reason why classic shortcuts don't work.

Regards,

**Comment by yishn** [comment]
Under Ubuntu, standard shortcuts (except <kbd>Ctrl+W</kbd> and <kbd>Ctrl+Q</kbd> which I do not consider standard) work as expected last time I checked. So maybe this is missing from your Linux distribution? I guess we can have an extra menu entry under 'File' to exit the application with <kbd>Ctrl+Q</kbd>, but I can't do anything about all the standard shortcuts.

**Comment by rekstein** [comment]
Thanks for your reply.
Unfortunately I encounter this problem only with Sabaki.
Maybe we can give a try with an extra menu entry under 'File' as you suggest it.
Nevertheless I made a small shell script binded to a global shortcut to exit Sabaki.

**Comment by HiggsTardigradeTau** [comment]
I can likely work on adding a 'Quit' option under 'File' if there is a consensus that doing so is necessary.

**Comment by rekstein** [comment]
Thank you all!
