### ISSUE TITLE
Where is the function to identify the name of the step

### ISSUE THREAD

**Issue by simonguoxm** [SabakiHQ/Sabaki#744]
Where is the function to identify the name of the step? I can not find it in the source code.

**Comment by yishn** [comment]
What do you mean by "the name of the step"?

**Comment by simonguoxm** [comment]
When I play one step, the name of the step is shown in the comments box (and If I hover over it , sometime it can highlight on the board).
![Screenshot 2020-09-17 141237](https://user-images.githubusercontent.com/4695131/93516954-5c252880-f8f0-11ea-91a1-af38207bb78f.png)

**Comment by yishn** [comment]
The automatic title is being generated by the our [boardmatcher module](https://github.com/SabakiHQ/boardmatcher). To add edit/add patterns modify the [`library.sgf`](https://github.com/SabakiHQ/boardmatcher/blob/master/library/library.sgf) file.
