### ISSUE TITLE
SAI periodically disconnects in Sabaki

### ISSUE THREAD

**Issue by cryptsport** [SabakiHQ/Sabaki#745]
SAI 0.17.6 when playing against lz (or another engine) periodically stops and you have to start the match further. SAI 0.17.5 works without problems. this is observed with Sabaki 0.41.0, 0.43.3, 0.51.1. but works fine with older versions 0.33.4, 0.35.1, 0.40.0, 0.40.1. more information https://github.com/sai-dev/sai/issues/123

**Comment by cryptsport** [comment]
SAI 0.18.1. stops after a few moves, often does not even make 1 move. with sai network and lz network.
noticed that this bug also manifests itself with Leela Zero, but rarely

**Comment by apetresc** [comment]
Closing this since it seems the issue was on SAI's end, not Sabaki's.
