### ISSUE TITLE
Support for Non-Square Board Sizes

### ISSUE THREAD

**Issue by yewang** [SabakiHQ/Sabaki#75]
It appears that non-square board sizes are not currently supported (at least in the web version). This would be a nice feature to have.

**Comment by yishn** [comment]
It's not compatible with the GTP protocol, so I don't have any motivation to allow that.

**Comment by yewang** [comment]
Some websites (such as online-go.com) allow games to be played on non-square boards. Without this feature, one cannot even properly open those valid SGF game records with Sabaki. This is a use case where GTP compatibility is irrelevant, since a user wouldn't need to connect to a go bot just to view a game record.

**Comment by yishn** [comment]
I see, we could just disallowing engines to attach to non-square boards. I'll keep this open then.

**Comment by alreadydone** [comment]
KataGo's GTP engine now supports non-square boards through `boardsize x y` or `rectangular_boardsize x y`. UI support is there, and it would be nice if Sabaki would send these commands as well!

**Comment by yishn** [comment]
Interesting; it shouldn't be too difficult to integrate this.
