### ISSUE TITLE
Zoom functions reversed?

### ISSUE THREAD

**Issue by David53bcg** [SabakiHQ/Sabaki#759]
The Zoom functionality seems to operate in reverse. What should decrease, increases. What should increase, decreases.

**Comment by apetresc** [comment]
I agree it's not super-clear, but what is being "zoomed" are the interface elements (game tree, font size, etc), so as those things grow and take up more space, the board itself has to get smaller to accommodate. The board always takes up all remaining available space, and there's no compelling use-case for zooming in on a subset of the board, so I think we should keep this definition of "Zoom"ing.
