### ISSUE TITLE
Feature request: modifier-click to go to position

### ISSUE THREAD

**Issue by goodger** [SabakiHQ/Sabaki#763]
When reviewing a game, it's a useful shortcut to go to the position where a certain move was played. Just control-click (or shift-click or right-click) on a stone or on an intersection, and the game will advance/rewind to the position where that stone was played. In CGoban this is done with shift-click.

Is this already possible in Sabaki?

**Comment by goodger** [comment]
Just discovered "Find mode": control-F then click a stone/intersection. Glad to see the functionality is already mostly there.

It would still be useful to have a keyboard shortcut for this, as described above.

At least this feature request may serve as future documentation for others searching for this feature.

**Comment by yishn** [comment]
Simply use a <kbd>Ctrl/Cmd+F</kbd> as the shortcut to enter find mode. Press <kbd>Esc</kbd> to leave find mode.
