### ISSUE TITLE
Turned off the menu. And now I can't turn it on again

### ISSUE THREAD

**Issue by radago88** [SabakiHQ/Sabaki#767]
Hello. I have the latest version of sabaki installed on windows 7 (64 bit). I studied the application menu and closed the menu display. How can I restore it? Tell me please.

![2021-01-15_21-09-29](https://user-images.githubusercontent.com/77506619/104763006-56dccb00-5776-11eb-98cc-c3ad2be799e6.png)

**Comment by yishn** [comment]
Tap <kbd>Alt</kbd>.

**Comment by radago88** [comment]
Thank you very much
