### ISSUE TITLE
a bug in edit

### ISSUE THREAD

**Issue by g101418** [SabakiHQ/Sabaki#776]
When Click on "Edit" and place black piece, the bottom column will be lifted, only return to normal when switching to white piece.

**Comment by apetresc** [comment]
Can you provide a screenshot of what you mean? I'm not sure what you mean by "the bottom column will be lifted"

Thanks 😀

**Comment by g101418** [comment]
![WeChat2c19805f00ef7972dcd035d9358dc0a2](https://user-images.githubusercontent.com/11593346/109606480-b42fae80-7b61-11eb-9e25-763ed077e2e4.png)
![WeChat5849668e1ee962b72eac2df4718cff94](https://user-images.githubusercontent.com/11593346/109606487-b5f97200-7b61-11eb-9acc-aa5c9aededc1.png)
![Xnip2021-03-02_14-15-01](https://user-images.githubusercontent.com/11593346/109606488-b6920880-7b61-11eb-9ac7-b32a41d46662.png)

**Comment by g101418** [comment]
I am not sure if you understand what I mean, if not please contact me ( :

**Comment by apetresc** [comment]
Ah, I was finally able to reproduce this! Will investigate closely soon.

**Comment by FanJeldmann** [comment]
Hi there.

I already solved it in my fork and made a pull request (without me knowing that there was an open ticket for this). I just now realized that there are contributing guidelines that I should have read first. Sorry about that. I'm new to the world of open source. :/

**Comment by apetresc** [comment]
Thanks to @FanJeldmann, this has been fixed in b28d2525a0f and will be released in v0.52.0 soon!
