### ISSUE TITLE
GTP engine can't be synced to current state.

### ISSUE THREAD

**Issue by Jamagoal** [SabakiHQ/Sabaki#777]
Hello

![image](https://user-images.githubusercontent.com/61111169/107627378-7d9bfd80-6c5f-11eb-9219-65c6883f7cbb.png)
![image](https://user-images.githubusercontent.com/61111169/107627422-90aecd80-6c5f-11eb-80b5-805f21c9ec0f.png)

I don't have more informations about

Here I have no problem 
![image](https://user-images.githubusercontent.com/61111169/107627600-d1a6e200-6c5f-11eb-96af-fbb473cca9ac.png)

Someone can help me please?

**Comment by hope366** [comment]
In my environment, writing a statement that specifies the engine on the second line resulted in an error.
Try deleting the part before "gtp" on the second line.

gtp -model D: \ GO \ katago-v1.8.0-opencl-windows-x64 \ kata1-b40c256-s6169484032-d1487890711.bin.gz -config D: \ GO \ katago-v1.8.0-opencl-windows-x64 \ gtp_custom.cfg

**Comment by Jamagoal** [comment]
I tried but I have the same problem

**Comment by Jamagoal** [comment]
Did nothing but now it's working... thanks anyway
