### ISSUE TITLE
Sunjang Baduk support

### ISSUE THREAD

**Issue by Qiangong2** [SabakiHQ/Sabaki#780]
I'm trying to play a round of Sunjang Baduk, but am unable to play as I cannot start the game with the standard piece placement

**Comment by apetresc** [comment]
Why not? You should be able to use the black/white stone placement tool in Edit mode to set up whatever starting position you want, no?

**Comment by Qiangong2** [comment]
nvm, I can start a game, but auto scoring does not work for Sunjang Baduk. It's not supported

**Comment by apetresc** [comment]
Does Sunjang Baduk have different scoring rules, somehow, from one of the existing rulesets?

**Comment by Qiangong2** [comment]
https://senseis.xmp.net/?SunjangBadukCounting

**Comment by apetresc** [comment]
Ah, I see. I don't think Sabaki is going to support that anytime soon. It doesn't appear that any of the mainstream engines support it either.
