### ISSUE TITLE
How to load an SGF file?

### ISSUE THREAD

**Issue by dinohsu1019** [SabakiHQ/Sabaki#785]
![image](https://user-images.githubusercontent.com/30600848/114307015-5ef79d00-9b10-11eb-86fd-734029246f14.png)
I try to look ups and downs, anyone shows me how to load an SGF file? Thanks in advance.

**Comment by apetresc** [comment]
It looks like you've just turned off the menu bar; you can bring it back by just pressing `Alt`. (Then you can keep it on permanently from View->Toggle Menu Bar). Once you have the menu bar, just use the File->Open dialog.

(Alternatively, use `Ctrl+O` even without a menu bar)
