### ISSUE TITLE
Problem opening .sgf files

### ISSUE THREAD

**Issue by MandiYang** [SabakiHQ/Sabaki#786]
Platform: Ubuntu 20.04 
Sabaki version: 0.51.1
Image:
![Screenshot from 2021-04-25 18-36-29](https://user-images.githubusercontent.com/64307609/116001536-359d3d80-a5f5-11eb-93b4-ac39460e3a54.png)

It doesn't show the stones.
**Comment to get more information**

**Comment by apetresc** [comment]
Can you paste/attach the SGF file causing this problem?

**Comment by MandiYang** [comment]
(;GM[1]FF[4]CA[UTF-8]AP[Sabaki:0.51.1]KM[6.5]SZ[19]DT[2021-04-25]GN[play1]GC[Unfinished];B[cd];W[pp];B[ed];W[cp])

**Comment by apetresc** [comment]
![image](https://user-images.githubusercontent.com/14872/116088294-bd279280-a66f-11eb-84b8-4fe54d7491e3.png)

It seems to load fine for me. You can't navigate the tree with the up/down arrows?

**Comment by MandiYang** [comment]
Aha, so it's the tree thing, thank's, looks like I need to look at the documantation about sabaki.
