### ISSUE TITLE
adding a Markdown table to comment hangs UI

### ISSUE THREAD

**Issue by goodger** [SabakiHQ/Sabaki#788]
Steps to reproduce:

1. In an open .sgf file, toggle edit mode with Ctrl-E.
2. In the comments area paste in a Markdown table, e.g. the text below.
3. Ctrl-E to toggle edit mode doesn't work: edit mode remains. The UI becomes unusable. After zooming the window to full-screen, the board remains at its original size. Clicking on the board produces the stone-click sound, but nothing is visible (no cursor, no new stones, nothing). Ctrl-N brings up a confirmation dialog as usual, but the UI isn't reset for the new file/record.

```
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column
```

Expected behavior: Ideally the table should be rendered as a table by Markdown. As a failsafe, the text should be shown as text. This should not hang the UI.

My environment: Sabaki 0.51.1 on Ubuntu Linux 20.10

**Comment by apetresc** [comment]
Should be good now!

![2021-07-04-21 58 28](https://user-images.githubusercontent.com/14872/124408136-90e55d80-dd13-11eb-8dab-3134b91c05dc.png)

Will be released in v0.52.0 soon.
