### ISSUE TITLE
Sabaki not working on Mac Big Sur 11.4?

### ISSUE THREAD

**Issue by trankhavy** [SabakiHQ/Sabaki#792]
I downloaded Sabaki sabaki-v0.51.1-mac-x64.7z but when I opened the app, it's just a black screen. I could not create a new file or do anything. Additionally, the app does not quit and I need to force quit it every single time. Anyone has any idea on why this is the case?
<img width="1440" alt="Screen Shot 2021-06-14 at 4 55 26 PM" src="https://user-images.githubusercontent.com/21098425/121973170-8433a200-cd31-11eb-9e2f-2f6891754a06.png">

**Comment by tydra-wang** [comment]
the same problem!!!

**Comment by apetresc** [comment]
Super strange; I've never encountered this and I use Big Sur daily. Just to confirm, is this on an M1 or Intel Mac?

**Comment by tydra-wang** [comment]
Intel Mac.

> Super strange; I've never encountered this and I use Big Sur daily. Just to confirm, is this on an M1 or Intel Mac?

**Comment by apetresc** [comment]
Would you be able to give the current `master` branch a try? (If not, I can prepare a prerelease build for you!)

**Comment by tydra-wang** [comment]
It's ok if you tell me how to run the source code

**Comment by apetresc** [comment]
Okay I'm pretty sure I fixed what was wrong with master (though still not your original issue), but just in case - can you try the prerelease binary from https://github.com/SabakiHQ/Sabaki/releases/tag/v0.52.0 ?

**Comment by tydra-wang** [comment]
Nice, it works now.

another problem in this release, a warning message when starting:
```
You have an invalid log folder for GTP console logging in your settings.

Please make sure the log directory is valid and writable, or disable GTP console logging.
```
but I can just ignore it.

**Comment by apetresc** [comment]
Yay, glad to hear it!

For the second issue, what is the value of `gtp.console_log_path` in your `~/Library/Application Support/Sabaki/settings.json`?

**Comment by tydra-wang** [comment]
```
"gtp.console_log_path": null,
```

**Comment by apetresc** [comment]
Hmm. And is ` "gtp.console_log_enabled": true` by any chance?

**Comment by tydra-wang** [comment]
```
cat ~/Library/Application\ Support/Sabaki/settings.json | grep gtp
  "gtp.console_log_enabled": true,
  "gtp.console_log_path": null,
  "gtp.engine_quit_timeout": 3000,
  "gtp.move_delay": 300,
```

After I changed it to `false`, the warning disappeared.
Maybe `settings.json` is created by old versions?

**Comment by apetresc** [comment]
I'm fairly certain there's been no changes to that part of the settings code in a long time. I'm not exactly sure how it got into that state, maybe you accidentally clicked the "Enable GTP logging" checkbox without filling in the path box on the right at some point. Either way, setting it back to `false` is the right solution :)

Thanks for helping me test out the prerelease build!

**Comment by 7468696e6b** [comment]
https://github.com/SabakiHQ/Sabaki/releases/tag/v0.52.0 check the latest release
