### ISSUE TITLE
落子后，棋子在棋盘上线不是对称的

### ISSUE THREAD

**Issue by wunongruanyu** [SabakiHQ/Sabaki#793]

**Comment by sente361** [comment]
**[1]**
![image](https://user-images.githubusercontent.com/47664082/121987236-6fabe400-cddb-11eb-8ef6-ac2b77dc8391.png)

**[2]**
![image](https://user-images.githubusercontent.com/47664082/121987372-b4377f80-cddb-11eb-9a41-b93e0ddda552.png)

**[3]**
![image](https://user-images.githubusercontent.com/47664082/121987597-21e3ab80-cddc-11eb-8e46-93d12814e852.png)

**Comment by apetresc** [comment]
Thank you for the translation and explanation, @sente361 :)
