### ISSUE TITLE
Snapback capture is labeled suicide

### ISSUE THREAD

**Issue by Yodo13** [SabakiHQ/Sabaki#800]
A tiny flaw. I believe that a snapback capture should be labeled "Take" instead of "Suicide".

I took this example: https://senseis.xmp.net/?Snapback

Here is a screen shot:
![snapback_capture](https://user-images.githubusercontent.com/64555156/124721365-580ed980-df09-11eb-8d3d-b1c1454965aa.png)

**Comment by ParmuzinAlexander** [comment]
There are a lot of errors in this module. We need a serious code change, which will not happen. It doesn't make sense to write about every mistake.

**Comment by apetresc** [comment]
This should technically be filed against [SabakiHQ/boardmatcher](/SabakiHQ/boardmatcher), but yeah, like @ParmuzinAlexander mentioned, it's an eternal game of whack-a-mole that will never end. A simple static inventory of move names will always have millions of edge cases. Nothing short of some sort of AI-trained model is going to accomplish this reliably.
