### ISSUE TITLE
menu command "Navigation → Go to Main Variation" doesn't work

### ISSUE THREAD

**Issue by goodger** [SabakiHQ/Sabaki#801]
Regression in Sabaki v0.52.0: "Navigation → Go to Main Variation" no longer navigates to the main variation. It navigates up, but not all the way left. It worked in Sabaki v0.51.1.

OS: Ubuntu Linux 21.04

**Comment by apetresc** [comment]
Thanks, I can reproduce this locally; it's very strange since I didn't think this release touched this codepath at all. Will investigate ASAP!

**Comment by apetresc** [comment]
Hmm, strangely enough while this bug doesn't occur in the v0.51.1 _release_ build, it _does_ occur if I just build the `v0.51.1` tag manually. So something unusual happened with that release, probably with the vendoring of the `@sabaki/immutable-gametree` dependency where this bug appears to reside.

**Comment by apetresc** [comment]
It appears to be SabakiHQ/immutable-gametree#3 to blame, but I have _no_ idea how that is working in the v0.51.1 release build which predates that PR.

**Comment by apetresc** [comment]
This is fixed in master and will go out in v0.52.1!

**Comment by goodger** [comment]
> This is fixed in master and will go out in v0.52.1!

Great, thanks!
