### ISSUE TITLE
Selecting "View/Show Move Numbers" clears edits on the goban

### ISSUE THREAD

**Issue by sente361** [SabakiHQ/Sabaki#802]
This applies to v0.51.1. (I haven't moved to v0.52 yet due to the issues already reported for it.) See screenshots for clarification:
![image](https://user-images.githubusercontent.com/47664082/125075642-3c225800-e102-11eb-8935-1b8af9a8b454.png)

Selecting "View/Show Move Numbers" wipes annotations on the goban that had previously been shown:
![image](https://user-images.githubusercontent.com/47664082/125076206-fb770e80-e102-11eb-98a7-b962be7ed7b6.png)

**Comment by sente361** [comment]
Another example; not all edits are wiped:
![image](https://user-images.githubusercontent.com/47664082/125078702-1dbe5b80-e106-11eb-87b8-09b072639438.png)

![image](https://user-images.githubusercontent.com/47664082/125078766-36c70c80-e106-11eb-85d5-9b3e591cce46.png)

**Comment by apetresc** [comment]
Can reproduce, very strange. Thanks!

**Comment by apetresc** [comment]
Okay, it was pretty easy to fix markers on the board itself, but at the moment Sabaki can't draw multiple markers on the same spot, so there's no good way to display both, say, a triangle and the move number on the same stone. So in this case we need to decide what to do:

- Display the move number, ignore the marker
- Display the marker, ignore the move number
- Modify Shudan to allow multiple markers on the same stone, and then figure out what that means for a bunch of corner cases:
  - editing; would we also allow users in the edit panel to put two symbols on the same stone?
  - textual markers and move numbers - would they just overlap?
  - etc

Happy to hear anyone's thoughts :)

**Comment by sente361** [comment]
> Display the move number, ignore the marker

Not desirable if "Show Move Numbers" is selected; for example, it is likely that the user will not realise that there is an undisplayed marker.

> Display the marker, ignore the move number

Not desirable: for example the user may spend an age looking for the missing move number.

> Modify Shudan to allow multiple markers on the same stone

This would be a nice enhancement. However it might be a lot of work both in adding this facility and then fixing assorted bugs that may arise. 

I suggest doing nothing further at this stage; leave things as they are until such time as multiple markers are requested (or a developer takes it on as an interesting challenge/project). I would make use of a multiple marker feature but it is not of great importance to me.

If anyone was to work on multiple markers I suggest that move numbers are displayed in small black font and any other markers on the stone are large and translucent (size depending on the number of markers on the stone). The object would be for the move number to show through any other markers on a stone. Being able to select a variety of colors for markers and move numbers would be another nice feature but is not at all important.

**Comment by yishn** [comment]
@sente361 Just for clarification, we don't actually clear the markers from the file. If "Show Move Numbers" is activated, we simply hide all the SGF custom markers since, as stated, we can't display two markers at the same time and it will be very messy if we did. This is as designed.

**Comment by sente361** [comment]
@yishn Thanks for the clarification.

**Comment by ldeng-ustc** [comment]
Is it possible to display move number and annotations only when there is no conflict? In a joseki book, characters are usually used to indicate the point of choice, which is usually on the board, while the number is used to indicate the order of the pieces and so appears only on the pieces (as shown below). But sabaki cannot display both at the same time, making it difficult to learn joseki or Life and Death with Sabaki.
![image](https://user-images.githubusercontent.com/37360259/222960678-ca9d8238-efb6-4f47-b7fe-b89eb7ed2ab1.png)
