### ISSUE TITLE
Add the ability to paste a text link to another node in the game comments

### ISSUE THREAD

**Issue by Hendeca** [SabakiHQ/Sabaki#805]
It would be very useful for making reference SGF files to be able to link to another node in the game comments. For example, if you wanted to do a tewari analysis on a given position, you could link to a completely different branch to show that the position is the same as another position reached but reached in a different way.

An example of the type of linking I'm thinking of can be seen here: https://online-go.com/joseki/15554

I know that this is a bit different since it uses URLs in a browser, but if the same kind of functionality could be incorporated within sabaki, this would be very useful.

**Comment by sente361** [comment]
You can achieve the same result by using _Find Mode._ Label the relevant nodes in _Edit Mode_, for example "Pos 1A" and "Pos 1B". Then type "Pos 1" in the Find Mode text box. Pressing F3 will then cycle through all nodes that include the text "Pos 1"

**Comment by Hendeca** [comment]
@sente361 I see that with find mode I can paste in the node label and jump to it, but is it possible to create a clickable link? I still think this would be a very useful functionality if it's not yet possible, but I will use this workaround for now.

Thank you!

**Comment by apetresc** [comment]
Interesting idea, but I believe we'd be going way outside of SGF's native capabilities to implement it. As far as I'm aware, there's no canonical identifier for a node in an SGF that would make sense in an implementation-independent way 🙁. And I'm virtually certain that the project is uninterested in creating custom extensions to the SGF spec.

I agree this would be wonderful to have. I believe the first step would be to either have an SGF spec expert fill us in on how this can be implemented within the existing spec, or it needs to be added to a future revision of SGF.

**Comment by Hendeca** [comment]
@apetresc Ok, that's reasonable. I have heard that perhaps this functionality could be possible in an as-yet unimplemented SGF spec, but I have not looked at the spec myself. If I do come across it I'll post it here. Thank you!

**Comment by yishn** [comment]
@Hendeca FWIW, your idea sounds similar to https://github.com/SabakiHQ/Sabaki/issues/488#issuecomment-449120494.
