### ISSUE TITLE
How to open a PR for a theme

### ISSUE THREAD

**Issue by billhails** [SabakiHQ/Sabaki#812]
Hi, I spent a pleasant Sunday morning creating a new theme for Sabaki and I'd like to share.

It's completely CG rendered with my own procedural textures so there are no copyright issues.

I'm fairly comfortable with the actual process of opening a PR, It's just not clear what I should change.

Here's the Theme if you want to take a look: https://github.com/billhails/SabakiThemes (under `yunzi`)

**Comment by apetresc** [comment]
Gorgeous 😃 (Especially the stones).

Themes are released separately by each author, there's nothing for Sabaki itself to merge. You already did the right thing by having an `.asar` file as a release.

Perhaps you wanted to add it to Sabaki's [theme directory](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/theme-directory.md)? Just open a PR against the file in `docs/guides/theme-directory.md` pointing to your repo and I'll be happy to include it!

**Comment by billhails** [comment]
Thanks! I opened a PR for theme-directory.md.
