### ISSUE TITLE
"Sabaki.app" is damaged and can't be opened. You should move it to the Trash"

### ISSUE THREAD

**Issue by g101418** [SabakiHQ/Sabaki#860]
macOS Monterey 12.3(21E230)
MacBook pro(14', 2021)
Apple M1 pro

Unable to open APP
Display the following information:
"Sabaki.app" is damaged and can't be opened. You should move it to the Trash"

**Comment by g101418** [comment]
sabaki-v0.52.0-mac-arm64.7z

**Comment by jason-ash** [comment]
I had the same issue, and was able to fix it by following the steps in #817. Good luck!
