### ISSUE TITLE
What application can open Sabaki?

### ISSUE THREAD

**Issue by qugi2646** [SabakiHQ/Sabaki#870]
I tried opening the download from github and recieved an error. 

There is no application set to open the document “sabaki-v0.52.0-mac-x64.7z”.

 it asks me to choose an application or search the app store for one. I'm not good with computers and don't know how to open it.

im using a mac os Sierra 10.12.6   2.5GHz intel i7 processor. 

will i even be able to handle a good engine If i can figure out how to get Sabaki? 

Thanks for any and all help in advance.

**Comment by HackYardo** [comment]
7z is a compress format for smaller size of a file. You can search "7z mac how" to find a way to open it. e.g. https://www.imymac.com/powermymac/how-to-open-7z-files-on-mac.html

And if it solve your issue, you should close it.

**Comment by qugi2646** [comment]
thank you for reply my problem is resolved
