### ISSUE TITLE
Error when executing .AppImage on Pop_OS

### ISSUE THREAD

**Issue by TheIronMarx** [SabakiHQ/Sabaki#878]
When trying to execute the x64 .appimage on Linux, I'm returned an error. A quick search shows that this has been a problem on other Electron apps trying to run on Linux. Digging into those bug tickets and forum posts, I didn't find anything that seemed like a valid solution to this issue. 

Here's the output when I run `./sabaki-v0.52.0-linux-x64.AppImage`

```
[615620:0710/103635.918289:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

I feel like this is a problem with my setup and Electron, but I'm not sure how to go about debugging. Any thoughts?

**Comment by HackYardo** [comment]
Have you tried this https://github.com/LedgerHQ/ledger-live-desktop/issues/4253 ?

**Comment by TheIronMarx** [comment]
Success!

The problem sounds like there's an issue with Electron interfacing with Ubuntu and its forks. It is unclear if there is a fix in an updated Electron version.

In mean time, I was able to run the .AppImage by using the `--no-sandbox` flag. Apparently this is a fairly longstanding tweak for several or all Electron apps with this issue.
