### ISSUE TITLE
Unable to install themes on Mac

### ISSUE THREAD

**Issue by qnpnpmqppnp** [SabakiHQ/Sabaki#897]
Receive "Installation Failed" error when attempting to install themes (.asar packages) on MacOS 12.5.1, using Sabaki 0.52.1.

![SCR-20220823-jrd](https://user-images.githubusercontent.com/111876350/186155646-d8a19f4f-95cc-4761-b9b9-001da50c9a6b.png)

![SCR-20220823-jru](https://user-images.githubusercontent.com/111876350/186155672-25f2916e-8b8f-4dca-bd3f-4505ab52a4b6.png)

**Comment by apetresc** [comment]
Thanks for the report! This has been fixed on the master branch - if you know how to build from master feel free to give it a spin and confirm that everything is working fine now 🙂 Otherwise it'll be released in v0.52.2 which should be ready soon.
