### ISSUE TITLE
Play number markup in comments is not being rendered into links

### ISSUE THREAD

**Issue by goodger** [SabakiHQ/Sabaki#898]
Sabaki 0.52.1 on MacOS 12.4.

Play number markup in comments, e.g. "#55", is not being rendered into hyperlinks. This worked fine in Sabaki 0.52.0.

**Comment by apetresc** [comment]
Indeed, I can reproduce this everywhere, not just on macOS. It seems to have been broken by the react-markdown version bump, but it's very unclear to me why. Investigating now.

**Comment by apetresc** [comment]
Thanks for the report! This has been fixed on the master branch - if you know how to build from master feel free to give it a spin and confirm that everything is working fine now :) Otherwise it'll be released in v0.52.2 which should be ready soon.

**Comment by goodger** [comment]
I can confirm that play number markup is working now. Your change fixed another issue in 0.52.1 that I noticed since reporting: coordinates (like "Q3") were also not being rendered into links. Both types of links are being rendered correctly now.

I didn't actually build from master. I just "git pull"ed the changes on the master branch and used the "npm start" method to launch Sabaki.

Thanks for the fix, and thanks for Sabaki!

**Comment by apetresc** [comment]
> I can confirm that play number markup is working now. Your change fixed another issue in 0.52.1 that I noticed since reporting: coordinates (like "Q3") were also not being rendered into links. Both types of links are being rendered correctly now.

Awesome, glad to hear it works for you as well :) And yes, fixing this led me to a bug that was affecting all sorts of custom linking in Sabaki's Markdown.

> I didn't actually build from master. I just "git pull"ed the changes on the master branch and used the "npm start" method to launch Sabaki.

That's precisely what I meant by "build from master" :) Anyway, v0.52.2 is now released, so you can just upgrade normally.
