### ISSUE TITLE
[SGF] A standard about the meaning of `SGF markups`?

### ISSUE THREAD

**Issue by HackYardo** [SabakiHQ/Sabaki#899]
https://www.red-bean.com/sgf/user_guide/index.html
SGF has some markups, but no their meanings. 
For example, which sgf markup should be used in order to represent the final_status_list seki of the GoTextProtocol?
TR, CR, or SQ?
Is there a standard tells that:
TR = key stones
SQ = a group of stones
CR = seki stones
DD = ownership (territory or area)
?

**Comment by goodger** [comment]
There is no such standard. It is up to the SGF comments or external text accompanying the diagram to explain the meaning of the various markup shapes. E.g. "The 🜂 stones are in trouble" or "The marked stones are in atari".

**Comment by HackYardo** [comment]
Thank you @goodger very much.
