### ISSUE TITLE
Why the generated move is not the highest score move in analysis

### ISSUE THREAD

**Issue by horaceho** [SabakiHQ/Sabaki#914]
In analysis (F4), the highest move is H8:

<img width="2374" alt="Screenshot 2022-12-02 at 10 13 31 PM" src="https://user-images.githubusercontent.com/6657/205312543-266ca42c-2a8d-4c26-b9ea-b59304436a11.png">

However, when a move is generated (F10), it is J11:

<img width="2374" alt="Screenshot 2022-12-02 at 10 12 28 PM" src="https://user-images.githubusercontent.com/6657/205312760-802a6285-4bfd-4e6a-a381-de53e06ee615.png">

Why?

**Comment by apetresc** [comment]
I'm not sure, but it's almost certainly related to Katago, not Sabaki. The GTP log on the left shows that Sabaki is correctly interpreting the engine's response to play J11, so there's not much we can do about this on our end.
