### ISSUE TITLE
Sabaki Go-board turns red in Windows 11

### ISSUE THREAD

**Issue by tororopark** [SabakiHQ/Sabaki#918]
When I turn on analysis mode in Sabaki program in Windows 11, the entire Go-board turns red.

Computer Specs

Computer OS: Windows 11 Home x64 (22H2: Version)
RAM: 32 GB
CPU: Intel i7 12700KF
Gaphics: GeForce RTX 4080

**Comment by apetresc** [comment]
Can you post a screenshot, and which theme you're using?

**Comment by tororopark** [comment]
![2022-12-20_(1)](https://user-images.githubusercontent.com/121224487/210785867-76d8bb45-4098-4fb8-8371-494f6cfafa19.png)

**Comment by apetresc** [comment]
Oh, I see. THat's not a bug! That's just the heatmap showing that katago has visited those points at least once. It will happen especially in the very early stages of the game with the default parameters. It's up to the engine which points to visit and how to report them.

There are some flags in Katago that you can set (I think?) to limit the width of its search tree if you really want. But overall this is expected and desired behaviour.
