### ISSUE TITLE
sabaki 无法识别101围棋网上的有些以utf8 with bom编码的棋谱。

### ISSUE THREAD

**Issue by zalois** [SabakiHQ/Sabaki#932]
sabaki 无法识别101围棋网上的有些以utf8 with bom编码的棋谱。
[101围棋网_镰仓十番棋之一_黑木谷实_VS_白吴清源_utf8_with_bom.zip](https://github.com/SabakiHQ/Sabaki/files/10704605/101._._._VS_._utf8_with_bom.zip)

**Comment by rooklift** [comment]
The issue with this file is not the BOM.

The issue with this file is there are 2 places where a comment C tag has an unescaped ] character.

![image](https://user-images.githubusercontent.com/16438795/226122867-af107470-8479-4829-aed2-184896133449.png)

**Comment by apetresc** [comment]
Thanks for the diagnosis, @rooklift :)
