### ISSUE TITLE
My sabaki missing font. I wanna what font should I have?

### ISSUE THREAD

**Issue by Fufu-S** [SabakiHQ/Sabaki#935]
![1](https://github.com/SabakiHQ/Sabaki/assets/43800368/7fd1c4dc-1b6f-488f-bb50-fec62d00713d)

**Comment by Fufu-S** [comment]
OS: openSUSE Leap 15.4 x86_64 
Host: MS-7C94 1.0 
Kernel: 5.14.21-150400.24.63-default 
Uptime: 2 hours, 14 mins 
Packages: 1 (dpkg), 2824 (rpm), 10 (snap) 
Shell: bash 4.4.23 
Resolution: 1920x1080 
DE: Plasma 5.24.4 
WM: kwin 
WM Theme: Breeze 微风 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
GPU: AMD ATI Radeon RX 6600/6600 XT/6600M 
Memory: 3027MiB / 15904MiB

**Comment by apetresc** [comment]
Are you using the AppImage or some other Linux package?

**Comment by Fufu-S** [comment]
> y

I didn't run into this issue when I was using AppImage. Back then, I had Sabaki installed through Snap (link here: https://snapcraft.io/install/sabaki/opensuse). But now I've switched to using AppImage and this problem doesn't bother me anymore.

**Comment by Fufu-S** [comment]
> Are you using the AppImage or some other Linux package?

I didn't run into this issue when I was using AppImage. Back then, I had Sabaki installed through Snap (link here: https://snapcraft.io/install/sabaki/opensuse). But now I've switched to using AppImage and this problem doesn't bother me anymore.
