### ISSUE TITLE
Mobile app with the same name

### ISSUE THREAD

**Issue by PJTraill** [SabakiHQ/Sabaki#947]
A recent Reddit thread (https://www.reddit.com/r/baduk/comments/15ubrff/sabaki_app/) brought to light an app for iPhone and Android by one Li Yusuo calling itself “sabaki” and looking similar. Does anyone here know how that is related to this project?

I gather from #207 that in 2017 (the date of the above app) no mobile version was planned, but that it could run in a browser, though not optimised for a small screen.

Apps at
https://apps.apple.com/us/app/sabaki/id1242870286 ,
https://play.google.com/store/apps/details?id=sabaki.altechnology.sg&hl=en

**Comment by apetresc** [comment]
Yeah there's no affiliation there. It looks like just some shovelware developer took the web version and wrapped it in an app. Unfortunate, but I don't really think there's anything we can reasonably do about it :(
